//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
//! SQLCipher key application, and plaintext↔encrypted migration for `meridian.db`.
//!
//! # Who calls this
//! - [`open_pool_with_key`] backs both [`crate::db::open_existing`] (tray/dashboard,
//!   no migrations) and the daemon's `setup_db` (`src/db/meridian.rs`), which also
//!   runs migrations afterward through the same pool.
//! - [`is_plaintext_sqlite`] / [`encrypt_in_place`] are called once by the tray on
//!   startup, after it resolves an encryption key (`tray/src-tauri/src/db_key.rs`),
//!   to transparently upgrade an existing plaintext `meridian.db` in place.
//! - [`export_plaintext`] backs the `meridian db-export-plaintext` CLI command
//!   (`src/main.rs`), which `packages/meridian-mcp` shells out to because its
//!   `sql.js` reader (WASM, no SQLCipher support) cannot open an encrypted file
//!   directly.
//!
//! # Key format
//! A key is exactly 64 lowercase/uppercase hex characters — 32 raw bytes / 256
//! bits — generated by `tray/src-tauri/src/db_key.rs`. It is applied via
//! SQLCipher's raw-key syntax (`PRAGMA key = "x'<hex>'"`), NOT as a passphrase:
//! this skips PBKDF2 key derivation (we already hand SQLCipher full-entropy key
//! material, so KDF stretching only adds latency, not security) and avoids any
//! string-escaping ambiguity a passphrase would raise.
//!
//! # Related
//! - [`crate::db`] — the pool opener this module's key-application logic backs.

use anyhow::{bail, Context};
use sqlx::sqlite::{SqliteConnectOptions, SqlitePoolOptions};
use sqlx::{ConnectOptions, Executor, SqlitePool};
use std::path::Path;
use std::str::FromStr;

/// The plain SQLite file-header magic (`"SQLite format 3\0"`). A SQLCipher-encrypted
/// file has no recognizable header — its first bytes are ciphertext.
const SQLITE_MAGIC: &[u8; 16] = b"SQLite format 3\0";

/// Validate that `key_hex` is exactly 64 hex characters (32-byte raw key).
///
/// Applied to any key before it is interpolated into a `PRAGMA key` string —
/// this is the one place that string gets built from external input (an env
/// var or a keychain entry), so validating the character set here is what
/// keeps that interpolation safe rather than a raw-SQL injection risk.
pub fn validate_key_hex(key_hex: &str) -> anyhow::Result<()> {
    if key_hex.len() != 64 || !key_hex.bytes().all(|b| b.is_ascii_hexdigit()) {
        bail!(
            "encryption key must be exactly 64 hex characters (32-byte raw key), got {} chars",
            key_hex.len()
        );
    }
    Ok(())
}

fn key_pragma(key_hex: &str) -> String {
    format!("PRAGMA key = \"x'{key_hex}'\"")
}

/// Open a pool at `uri`, applying the SQLCipher key (if any) as the FIRST
/// statement on every new physical connection, before any other pragma.
///
/// Deliberately does NOT use `SqliteConnectOptions`'s `.journal_mode()` /
/// `.synchronous()` / `.pragma()` builder methods for this: sqlx does not
/// guarantee those run in the order given relative to each other on a fresh
/// connection (launchbadge/sqlx#2009), and SQLCipher requires `PRAGMA key` to
/// be the literal first statement executed against a connection — anything
/// else first (including WAL mode) silently fails against an encrypted file.
/// `after_connect` gives full, explicit control over statement order, and runs
/// on every new physical connection the pool opens (required — SQLCipher's key
/// is per-connection state, not per-file).
pub async fn open_pool_with_key(
    uri: &str,
    key_hex: Option<&str>,
    create_if_missing: bool,
    extra_pragmas: &'static [(&'static str, &'static str)],
) -> anyhow::Result<SqlitePool> {
    if let Some(k) = key_hex {
        validate_key_hex(k)?;
    }
    let opts = SqliteConnectOptions::from_str(uri)
        .with_context(|| format!("invalid SQLite URI: {uri}"))?
        .create_if_missing(create_if_missing);

    let key_owned = key_hex.map(|s| s.to_string());
    let pool = SqlitePoolOptions::new()
        // A stale/wrong key can make SQLCipher stall (rather than error
        // cleanly) on the first pragma that touches an undecryptable page,
        // observed directly while testing this module. sqlx's own default
        // acquire timeout is 30s; a bad key on the daemon's hot path
        // shouldn't be able to hang startup that long. 10s still comfortably
        // covers a slow disk on the correct-key path.
        .acquire_timeout(std::time::Duration::from_secs(10))
        .after_connect(move |conn, _meta| {
            let key_owned = key_owned.clone();
            Box::pin(async move {
                if let Some(k) = &key_owned {
                    conn.execute(key_pragma(k).as_str()).await?;
                }
                conn.execute("PRAGMA journal_mode=WAL;").await?;
                conn.execute("PRAGMA synchronous=NORMAL;").await?;
                conn.execute("PRAGMA busy_timeout=5000;").await?;
                for (name, value) in extra_pragmas {
                    conn.execute(format!("PRAGMA {name}={value};").as_str())
                        .await?;
                }
                Ok(())
            })
        })
        .connect_with(opts)
        .await
        .with_context(|| format!("failed to open SQLite at {uri}"))?;
    Ok(pool)
}

/// Open a READ-ONLY pool at `uri`, applying the SQLCipher key (if any) as the
/// first statement on every new connection, same rationale as
/// [`open_pool_with_key`]. Used by the daemon's health checker
/// (`src/health/daemon.rs`), which must never create the file or take a write
/// lock, only inspect it.
pub async fn open_pool_with_key_readonly(
    uri: &str,
    key_hex: Option<&str>,
) -> anyhow::Result<SqlitePool> {
    if let Some(k) = key_hex {
        validate_key_hex(k)?;
    }
    let opts = SqliteConnectOptions::from_str(uri)
        .with_context(|| format!("invalid SQLite URI: {uri}"))?
        .read_only(true);

    let key_owned = key_hex.map(|s| s.to_string());
    let pool = SqlitePoolOptions::new()
        .acquire_timeout(std::time::Duration::from_secs(10)) // see open_pool_with_key
        .after_connect(move |conn, _meta| {
            let key_owned = key_owned.clone();
            Box::pin(async move {
                if let Some(k) = &key_owned {
                    conn.execute(key_pragma(k).as_str()).await?;
                }
                Ok(())
            })
        })
        .connect_with(opts)
        .await
        .with_context(|| format!("failed to open SQLite (read-only) at {uri}"))?;
    Ok(pool)
}

/// Does `path` look like a plaintext (unencrypted) SQLite file? `false` for a
/// SQLCipher-encrypted file (no recognizable header), a missing file, or a
/// file too small to hold the 16-byte magic (treated as "not plaintext" so a
/// migration attempt is skipped and the caller's own open surfaces the real
/// problem instead of this heuristic guessing wrong).
pub fn is_plaintext_sqlite(path: &Path) -> bool {
    use std::io::Read;
    let Ok(mut f) = std::fs::File::open(path) else {
        return false;
    };
    let mut magic = [0u8; 16];
    matches!(f.read_exact(&mut magic), Ok(())) && &magic == SQLITE_MAGIC
}

/// Migrate an existing plaintext `meridian.db` to SQLCipher encryption at rest,
/// in place. No-op if `path` doesn't exist yet (fresh install — the caller
/// creates it encrypted from scratch) or is already encrypted.
///
/// Safety: the original file is never modified or removed until the encrypted
/// export has been fully written and verified — on any failure partway through,
/// `path` is left exactly as it was, so a failed migration degrades to "still
/// plaintext, retry next startup" rather than risking data loss. The plaintext
/// original is kept alongside the encrypted result (renamed with a timestamped
/// suffix), not deleted, so a bad migration is always recoverable by hand.
pub async fn encrypt_in_place(path: &Path, key_hex: &str) -> anyhow::Result<()> {
    validate_key_hex(key_hex)?;
    if !path.exists() || !is_plaintext_sqlite(path) {
        return Ok(());
    }

    let uri = path.display().to_string();
    // `create_if_missing(true)` here is a no-op for THIS file (already checked
    // to exist above) — it's needed because SQLite's ATTACH inherits the main
    // connection's open flags, so the encrypted target ATTACHed below can't be
    // created at all unless the main connection itself was opened with the
    // create flag set.
    let mut conn = SqliteConnectOptions::from_str(&uri)
        .with_context(|| format!("invalid SQLite path: {uri}"))?
        .create_if_missing(true)
        .connect()
        .await
        .context("encrypt_in_place: failed to open existing plaintext database")?;

    // Fold the WAL into the main file so the export below sees every committed
    // write, and the plaintext original's -wal/-shm sidecars are safely
    // empty/removable afterward.
    conn.execute("PRAGMA wal_checkpoint(TRUNCATE);")
        .await
        .context("encrypt_in_place: WAL checkpoint failed")?;

    let tmp_path = path.with_extension("db.encrypting-tmp");
    let _ = std::fs::remove_file(&tmp_path); // best-effort cleanup of a prior interrupted attempt

    let attach_sql = format!(
        "ATTACH DATABASE '{}' AS encrypted_export KEY \"x'{}'\";",
        tmp_path.display(),
        key_hex
    );
    conn.execute(attach_sql.as_str())
        .await
        .context("encrypt_in_place: ATTACH failed")?;
    conn.execute("SELECT sqlcipher_export('encrypted_export');")
        .await
        .context("encrypt_in_place: sqlcipher_export failed")?;
    conn.execute("DETACH DATABASE encrypted_export;")
        .await
        .context("encrypt_in_place: DETACH failed")?;
    drop(conn);

    let backup_path = path.with_extension(format!(
        "db.plaintext-backup-{}",
        chrono::Utc::now().format("%Y%m%d%H%M%S")
    ));
    std::fs::rename(path, &backup_path)
        .context("encrypt_in_place: failed to move plaintext original aside")?;
    for suffix in ["-wal", "-shm"] {
        let sidecar = std::path::PathBuf::from(format!("{}{}", path.display(), suffix));
        let _ = std::fs::remove_file(sidecar); // checkpointed to empty; safe to drop
    }
    std::fs::rename(&tmp_path, path)
        .context("encrypt_in_place: failed to move encrypted export into place")?;

    tracing::info!(
        db = %path.display(),
        backup = %backup_path.display(),
        "migrated meridian.db from plaintext to SQLCipher encryption at rest"
    );
    Ok(())
}

/// Export a plaintext snapshot of an encrypted database to `out_path`, for
/// consumers (currently `meridian-mcp`'s `sql.js` reader) that cannot open a
/// SQLCipher-encrypted file directly. Overwrites `out_path` if it exists.
pub async fn export_plaintext(
    encrypted_db_path: &Path,
    key_hex: &str,
    out_path: &Path,
) -> anyhow::Result<()> {
    validate_key_hex(key_hex)?;
    let uri = encrypted_db_path.display().to_string();
    // See the identical comment in `encrypt_in_place` — ATTACH inherits the
    // main connection's open flags, so `plaintext_export` below can't be
    // created unless this connection was opened with the create flag set.
    let mut conn = SqliteConnectOptions::from_str(&uri)
        .with_context(|| format!("invalid SQLite path: {uri}"))?
        .create_if_missing(true)
        .connect()
        .await
        .context("export_plaintext: failed to open encrypted database")?;

    conn.execute(key_pragma(key_hex).as_str())
        .await
        .context("export_plaintext: PRAGMA key failed")?;
    // A wrong key doesn't error on `PRAGMA key` itself — SQLCipher only
    // discovers a bad key on the first real page read. Force that check now
    // so a wrong key fails loudly here instead of silently exporting garbage.
    conn.execute("SELECT count(*) FROM sqlite_master;")
        .await
        .context("export_plaintext: failed to read database — wrong encryption key?")?;

    let _ = std::fs::remove_file(out_path);
    let attach_sql = format!(
        "ATTACH DATABASE '{}' AS plaintext_export KEY '';",
        out_path.display()
    );
    conn.execute(attach_sql.as_str())
        .await
        .context("export_plaintext: ATTACH failed")?;
    conn.execute("SELECT sqlcipher_export('plaintext_export');")
        .await
        .context("export_plaintext: sqlcipher_export failed")?;
    conn.execute("DETACH DATABASE plaintext_export;")
        .await
        .context("export_plaintext: DETACH failed")?;

    // The ATTACH-created file inherits the process umask, typically 0644. This
    // is the ONE place the SQLCipher rollout deliberately writes a full,
    // unencrypted copy of the activity database, so leaving it group- and
    // world-readable would undo — for that file — exactly the local-multi-user
    // threat the rest of the encryption work exists to cover. It gets the same
    // 0600 the encrypted original deserves.
    //
    // Tightened AFTER the export rather than pre-creating the file: SQLCipher's
    // ATTACH wants to create it itself, and `remove_file` above deliberately
    // clears any stale copy first.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(out_path, std::fs::Permissions::from_mode(0o600)).with_context(
            || {
                format!(
                    "export_plaintext: failed to restrict permissions on {}",
                    out_path.display()
                )
            },
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlx::Row;

    const TEST_KEY: &str = "3a15689f73412c29d7ed3b902a01e33dbd5f767dc37b792e19ac9e2366bf2cd2";
    const OTHER_KEY: &str = "0000000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fn validate_key_hex_rejects_bad_input() {
        assert!(validate_key_hex(TEST_KEY).is_ok());
        assert!(validate_key_hex("too-short").is_err());
        assert!(validate_key_hex(&"g".repeat(64)).is_err()); // not hex
        assert!(validate_key_hex(&"a".repeat(63)).is_err()); // wrong length
    }

    #[tokio::test]
    async fn is_plaintext_sqlite_detects_plain_and_encrypted() {
        let dir = tempfile::tempdir().unwrap();
        let plain_path = dir.path().join("plain.db");
        let enc_path = dir.path().join("enc.db");

        // A plain file created without a key.
        let pool = open_pool_with_key(&plain_path.display().to_string(), None, true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(is_plaintext_sqlite(&plain_path));

        // An encrypted file created with a key.
        let pool = open_pool_with_key(&enc_path.display().to_string(), Some(TEST_KEY), true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(!is_plaintext_sqlite(&enc_path));
    }

    #[tokio::test]
    async fn encrypt_in_place_migrates_and_preserves_data() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("meridian.db");

        // Seed a plaintext DB with data.
        let pool = open_pool_with_key(&db_path.display().to_string(), None, true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (42)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(is_plaintext_sqlite(&db_path));

        encrypt_in_place(&db_path, TEST_KEY).await.unwrap();
        assert!(!is_plaintext_sqlite(&db_path));

        // A plaintext backup was preserved (never deleted).
        let has_backup = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .any(|e| e.file_name().to_string_lossy().contains("plaintext-backup"));
        assert!(has_backup, "expected a preserved plaintext backup file");

        // Correct key reads the migrated data back intact.
        let pool = open_pool_with_key(&db_path.display().to_string(), Some(TEST_KEY), false, &[])
            .await
            .unwrap();
        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(row.get::<i64, _>(0), 42);
        pool.close().await;

        // Wrong key must never silently return the real data — whether that
        // surfaces as an outright connect failure, a query error, or (as
        // observed in practice — SQLCipher can stall rather than error
        // cleanly when a later pragma tries to touch an undecryptable page)
        // simply never producing a usable connection in reasonable time, all
        // three are acceptable: the one unacceptable outcome is a readable
        // row 42 coming back on the wrong key.
        let wrong_attempt = tokio::time::timeout(
            std::time::Duration::from_secs(5),
            open_pool_with_key(&db_path.display().to_string(), Some(OTHER_KEY), false, &[]),
        )
        .await;
        match wrong_attempt {
            Err(_elapsed) => {}      // timed out opening — acceptable, not the real key
            Ok(Err(_open_err)) => {} // failed to open — acceptable
            Ok(Ok(wrong)) => {
                let result = sqlx::query("SELECT x FROM t").fetch_one(&wrong).await;
                assert!(result.is_err(), "reading with the wrong key should fail");
                wrong.close().await;
            }
        }
    }

    #[tokio::test]
    async fn export_plaintext_roundtrips_encrypted_data() {
        let dir = tempfile::tempdir().unwrap();
        let enc_path = dir.path().join("enc.db");
        let out_path = dir.path().join("plain-export.db");

        let pool = open_pool_with_key(&enc_path.display().to_string(), Some(TEST_KEY), true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (7)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;

        export_plaintext(&enc_path, TEST_KEY, &out_path)
            .await
            .unwrap();
        assert!(is_plaintext_sqlite(&out_path));

        let pool = open_pool_with_key(&out_path.display().to_string(), None, false, &[])
            .await
            .unwrap();
        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(row.get::<i64, _>(0), 7);
        pool.close().await;

        // This is the one file the encryption work deliberately writes in
        // plaintext, so it must not inherit the umask's usual 0644 - that
        // would leave a full, unencrypted copy of the activity database
        // readable by every other local account.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&out_path).unwrap().permissions().mode() & 0o777;
            assert_eq!(
                mode, 0o600,
                "plaintext export is readable by others: {mode:o}"
            );
        }
    }
}
