//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
//! SQLCipher key application, and plaintext↔encrypted migration for `meridian.db`.
//!
//! # Who calls this
//! - [`open_pool_with_key`] backs both [`crate::db::open_existing`] (tray/dashboard,
//!   no migrations) and the daemon's `setup_db` (`src/db/meridian.rs`), which also
//!   runs migrations afterward through the same pool.
//! - [`is_plaintext_sqlite`] / [`encrypt_in_place`] are called once by the tray on
//!   startup, after it resolves an encryption key (`tray/src-tauri/src/db_key.rs`),
//!   to transparently upgrade an existing plaintext `meridian.db` in place.
//! - [`export_plaintext`] backs the `meridian db-export-plaintext` CLI command
//!   (`src/main.rs`), which `packages/meridian-mcp` shells out to because its
//!   `sql.js` reader (WASM, no SQLCipher support) cannot open an encrypted file
//!   directly.
//!
//! # Key format
//! A key is exactly 64 lowercase/uppercase hex characters — 32 raw bytes / 256
//! bits — generated by `tray/src-tauri/src/db_key.rs`. It is applied via
//! SQLCipher's raw-key syntax (`PRAGMA key = "x'<hex>'"`), NOT as a passphrase:
//! this skips PBKDF2 key derivation (we already hand SQLCipher full-entropy key
//! material, so KDF stretching only adds latency, not security) and avoids any
//! string-escaping ambiguity a passphrase would raise.
//!
//! # Related
//! - [`crate::db`] — the pool opener this module's key-application logic backs.

use anyhow::{bail, Context};
use sqlx::sqlite::{SqliteConnectOptions, SqlitePoolOptions};
use sqlx::{ConnectOptions, Connection, Executor, SqlitePool};
use std::path::Path;
use std::str::FromStr;

/// The plain SQLite file-header magic (`"SQLite format 3\0"`). A SQLCipher-encrypted
/// file has no recognizable header — its first bytes are ciphertext.
const SQLITE_MAGIC: &[u8; 16] = b"SQLite format 3\0";

/// Validate that `key_hex` is exactly 64 hex characters (32-byte raw key).
///
/// Applied to any key before it is interpolated into a `PRAGMA key` string —
/// this is the one place that string gets built from external input (an env
/// var or a keychain entry), so validating the character set here is what
/// keeps that interpolation safe rather than a raw-SQL injection risk.
pub fn validate_key_hex(key_hex: &str) -> anyhow::Result<()> {
    if key_hex.len() != 64 || !key_hex.bytes().all(|b| b.is_ascii_hexdigit()) {
        bail!(
            "encryption key must be exactly 64 hex characters (32-byte raw key), got {} chars",
            key_hex.len()
        );
    }
    Ok(())
}

fn key_pragma(key_hex: &str) -> String {
    format!("PRAGMA key = \"x'{key_hex}'\"")
}

/// The standard connection pragmas every read-write `meridian.db` pool applies,
/// in order, AFTER `PRAGMA key`.
///
/// Shared by [`open_pool_with_key`] and [`open_pool_with_key_lazy`] so a pragma
/// added for one opener can never be silently missed by the other — the two
/// differ only in *when* they connect, never in how a connection is set up.
const BASE_PRAGMAS: [&str; 3] = [
    "PRAGMA journal_mode=WAL;",
    "PRAGMA synchronous=NORMAL;",
    "PRAGMA busy_timeout=5000;",
];

/// Open a pool at `uri`, applying the SQLCipher key (if any) as the FIRST
/// statement on every new physical connection, before any other pragma.
///
/// Deliberately does NOT use `SqliteConnectOptions`'s `.journal_mode()` /
/// `.synchronous()` / `.pragma()` builder methods for this: sqlx does not
/// guarantee those run in the order given relative to each other on a fresh
/// connection (launchbadge/sqlx#2009), and SQLCipher requires `PRAGMA key` to
/// be the literal first statement executed against a connection — anything
/// else first (including WAL mode) silently fails against an encrypted file.
/// `after_connect` gives full, explicit control over statement order, and runs
/// on every new physical connection the pool opens (required — SQLCipher's key
/// is per-connection state, not per-file).
pub async fn open_pool_with_key(
    uri: &str,
    key_hex: Option<&str>,
    create_if_missing: bool,
    extra_pragmas: &'static [(&'static str, &'static str)],
) -> anyhow::Result<SqlitePool> {
    let key_hex = key_unless_plaintext(uri, key_hex);
    if let Some(k) = key_hex {
        validate_key_hex(k)?;
    }
    let opts = SqliteConnectOptions::from_str(uri)
        .with_context(|| format!("invalid SQLite URI: {uri}"))?
        .create_if_missing(create_if_missing);

    let key_owned = key_hex.map(|s| s.to_string());
    let pool = SqlitePoolOptions::new()
        // A stale/wrong key can make SQLCipher stall (rather than error
        // cleanly) on the first pragma that touches an undecryptable page,
        // observed directly while testing this module. sqlx's own default
        // acquire timeout is 30s; a bad key on the daemon's hot path
        // shouldn't be able to hang startup that long. 10s still comfortably
        // covers a slow disk on the correct-key path.
        .acquire_timeout(std::time::Duration::from_secs(10))
        .after_connect(move |conn, _meta| {
            let key_owned = key_owned.clone();
            Box::pin(async move {
                if let Some(k) = &key_owned {
                    conn.execute(key_pragma(k).as_str()).await?;
                }
                for pragma in BASE_PRAGMAS {
                    conn.execute(pragma).await?;
                }
                for (name, value) in extra_pragmas {
                    conn.execute(format!("PRAGMA {name}={value};").as_str())
                        .await?;
                }
                Ok(())
            })
        })
        .connect_with(opts)
        .await
        .with_context(|| format!("failed to open SQLite at {uri}"))?;
    Ok(pool)
}

/// Build a pool at `uri` **without connecting**, applying the same key and
/// pragmas as [`open_pool_with_key`] on each connection the pool later opens
/// on demand.
///
/// # Why this exists
/// The tray opens `meridian.db` once during Tauri `setup` and shares the handle
/// with every DB-backed command and the capture consumers. On a **first
/// launch** it reaches that point seconds before `ensure_backend_installed`
/// starts the daemon — and the daemon is what CREATES `meridian.db`. An eager
/// open therefore fails with "unable to open database file", and because the
/// tray stores the result as an `Option` there is nothing that ever retries:
/// the whole process runs to shutdown with `None`, silently returning empty
/// data from every command and dropping every captured frame on the floor.
/// Connecting lazily makes that self-healing — the first acquire after the
/// daemon creates the file succeeds, with no restart and no retry loop.
///
/// # Why the key decision moves into `after_connect`
/// [`key_unless_plaintext`] probes the file header to decide whether the key
/// applies at all. [`open_pool_with_key`] can evaluate that once up front
/// because it has just proven the file is openable. A lazy pool has not: at
/// build time the file routinely does not exist yet, and a decision cached
/// from that moment would be made against nothing. Re-resolving per connection
/// means the pool always keys (or declines to key) against the file as it
/// actually is when the connection is made.
///
/// # Must be called from inside a Tokio runtime
/// `async` even though it never awaits, and that is load-bearing: sqlx's
/// `connect_lazy_with` spawns the pool's maintenance task while *building* the
/// handle, so it panics with "this functionality requires a Tokio context" when
/// constructed outside a runtime. Being `async` forces every caller through an
/// executor (`block_on` / `.await`) instead of leaving that requirement to a
/// comment nobody reads — which is exactly how it was first shipped broken, as
/// a synchronous call in Tauri's `setup()` that panicked the tray on launch.
///
/// Infallible-to-connect by construction — the only error it can return is a
/// malformed `uri` or `key_hex`. `create_if_missing` is always false: the
/// daemon owns creation and migrations (see [`crate::db`]).
pub async fn open_pool_with_key_lazy(
    uri: &str,
    key_hex: Option<&str>,
) -> anyhow::Result<SqlitePool> {
    if let Some(k) = key_hex {
        validate_key_hex(k)?;
    }
    let opts = SqliteConnectOptions::from_str(uri)
        .with_context(|| format!("invalid SQLite URI: {uri}"))?
        .create_if_missing(false);

    let uri_owned = uri.to_string();
    let key_owned = key_hex.map(|s| s.to_string());
    Ok(SqlitePoolOptions::new()
        .acquire_timeout(std::time::Duration::from_secs(10)) // see open_pool_with_key
        .after_connect(move |conn, _meta| {
            let uri_owned = uri_owned.clone();
            let key_owned = key_owned.clone();
            Box::pin(async move {
                // Resolved here, not at build time — see the doc comment above.
                if let Some(k) = key_unless_plaintext(&uri_owned, key_owned.as_deref()) {
                    conn.execute(key_pragma(k).as_str()).await?;
                }
                for pragma in BASE_PRAGMAS {
                    conn.execute(pragma).await?;
                }
                Ok(())
            })
        })
        .connect_lazy_with(opts))
}

/// Open a READ-ONLY pool at `uri`, applying the SQLCipher key (if any) as the
/// first statement on every new connection, same rationale as
/// [`open_pool_with_key`]. Used by the daemon's health checker
/// (`src/health/daemon.rs`), which must never create the file or take a write
/// lock, only inspect it.
pub async fn open_pool_with_key_readonly(
    uri: &str,
    key_hex: Option<&str>,
) -> anyhow::Result<SqlitePool> {
    let key_hex = key_unless_plaintext(uri, key_hex);
    if let Some(k) = key_hex {
        validate_key_hex(k)?;
    }
    let opts = SqliteConnectOptions::from_str(uri)
        .with_context(|| format!("invalid SQLite URI: {uri}"))?
        .read_only(true);

    let key_owned = key_hex.map(|s| s.to_string());
    let pool = SqlitePoolOptions::new()
        .acquire_timeout(std::time::Duration::from_secs(10)) // see open_pool_with_key
        .after_connect(move |conn, _meta| {
            let key_owned = key_owned.clone();
            Box::pin(async move {
                if let Some(k) = &key_owned {
                    conn.execute(key_pragma(k).as_str()).await?;
                }
                Ok(())
            })
        })
        .connect_with(opts)
        .await
        .with_context(|| format!("failed to open SQLite (read-only) at {uri}"))?;
    Ok(pool)
}

/// Does `path` look like a plaintext (unencrypted) SQLite file? `false` for a
/// SQLCipher-encrypted file (no recognizable header), a missing file, or a
/// file too small to hold the 16-byte magic (treated as "not plaintext" so a
/// migration attempt is skipped and the caller's own open surfaces the real
/// problem instead of this heuristic guessing wrong).
pub fn is_plaintext_sqlite(path: &Path) -> bool {
    plaintext_state(path).unwrap_or(false)
}

/// The same probe as [`is_plaintext_sqlite`], but three-valued: `Some(true)`
/// definitely plaintext, `Some(false)` definitely NOT plaintext, and `None`
/// when the file could not be read at all and the answer is simply unknown.
///
/// [`is_plaintext_sqlite`] deliberately collapses `None` to `false`, which is
/// right for its callers (a missing file on a fresh install must not trigger a
/// migration). It is wrong for anything that acts on "the database is safely
/// encrypted", because an unreadable file would masquerade as a confirmed
/// encrypted one. The tray's encryption-warning notice uses this instead, so it
/// can decline to clear a warning it cannot disprove.
pub fn plaintext_state(path: &Path) -> Option<bool> {
    use std::io::Read;
    let mut f = std::fs::File::open(path).ok()?;
    let mut magic = [0u8; 16];
    f.read_exact(&mut magic).ok()?;
    Some(&magic == SQLITE_MAGIC)
}

/// Best-effort extraction of the on-disk file path from a SQLite connection
/// string, for the plaintext check in [`key_unless_plaintext`]. Accepts both a
/// bare filesystem path (as [`encrypt_in_place`] passes) and a `sqlite://…` /
/// `file:…` URI (as the daemon's `setup_db` and the tray's `open_existing`
/// pass — `format!("sqlite://{path}")`), and strips any `?mode=ro&…` query.
/// Returns `None` for `:memory:` (nothing on disk to inspect).
fn sqlite_uri_to_path(uri: &str) -> Option<std::path::PathBuf> {
    let without_scheme = uri
        .strip_prefix("sqlite://")
        .or_else(|| uri.strip_prefix("sqlite:"))
        .or_else(|| uri.strip_prefix("file://"))
        .or_else(|| uri.strip_prefix("file:"))
        .unwrap_or(uri);
    let path = without_scheme
        .split_once('?')
        .map(|(p, _)| p)
        .unwrap_or(without_scheme);
    if path.is_empty() || path == ":memory:" {
        return None;
    }
    Some(std::path::PathBuf::from(path))
}

/// Drop the encryption key when `uri` points at an existing **plaintext** SQLite
/// file; otherwise return `key_hex` unchanged.
///
/// Applying a SQLCipher `PRAGMA key` to a file that is actually plaintext makes
/// SQLCipher stall on the first page-touching pragma until the pool's 10s
/// acquire timeout fires — surfacing to callers as `worklog-generate: open db:
/// … pool timed out while waiting for an open connection`. That desync arises
/// when an [`encrypt_in_place`] migration wrote the encrypted copy but could
/// not complete its final swap (on Windows `std::fs::rename` fails while the
/// daemon still holds `meridian.db` open), leaving the on-disk file plaintext
/// while `MERIDIAN_DB_KEY` stays set in `.env`. Every DB opener the daemon and
/// the CLI subprocesses use routes through [`open_pool_with_key`], so guarding
/// here self-heals an already-stuck machine: a key never applies to a plaintext
/// file, so drop it, open unencrypted, and warn so the stuck migration stays
/// visible. [`is_plaintext_sqlite`] is `false` for a missing file (fresh
/// install → keep the key and create encrypted) and for an encrypted file
/// (ciphertext header → keep the key), so this fires only on the genuine
/// plaintext-with-key desync.
fn key_unless_plaintext<'a>(uri: &str, key_hex: Option<&'a str>) -> Option<&'a str> {
    let key = key_hex?;
    match sqlite_uri_to_path(uri) {
        Some(path) if is_plaintext_sqlite(&path) => {
            tracing::warn!(
                db = %path.display(),
                "meridian.db is plaintext but an encryption key is configured — opening \
                 unencrypted and ignoring the key (a prior encrypt-in-place migration did \
                 not complete; see meridian_core::db_crypto)"
            );
            None
        }
        _ => Some(key),
    }
}

/// Files an interrupted [`encrypt_in_place`] would have left beside `path`:
/// the fully-written encrypted export (`…db.encrypting-tmp`) and any timestamped
/// plaintext backup (`…db.plaintext-backup-<ts>`).
///
/// Used only to tell "fresh install" apart from "crashed mid-migration" when
/// `path` is absent — the two look identical otherwise, and conflating them is
/// how a user ends up staring at an empty app with their data intact on disk
/// two directory entries away.
fn interrupted_migration_leftovers(path: &Path) -> Vec<std::path::PathBuf> {
    let mut found = Vec::new();
    let tmp = path.with_extension("db.encrypting-tmp");
    if tmp.exists() {
        found.push(tmp);
    }
    let (Some(dir), Some(stem)) = (path.parent(), path.file_name()) else {
        return found;
    };
    // `with_extension("db.plaintext-backup-<ts>")` on `meridian.db` replaces the
    // `db` extension, yielding `meridian.db.plaintext-backup-<ts>` — i.e. the
    // full file name plus the suffix. Match that prefix rather than trying to
    // reconstruct a timestamp.
    let prefix = format!("{}.plaintext-backup-", stem.to_string_lossy());
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            if name.to_string_lossy().starts_with(&prefix) {
                found.push(entry.path());
            }
        }
    }
    found
}

/// `std::fs::rename` with a short bounded retry (~1s of linear backoff across 5
/// attempts) via the shared [`crate::retry::retry_transient_blocking`]. On
/// Windows a rename fails with os error 32 ("used by another process") while
/// *any* handle to the source or destination is briefly open — an antivirus
/// scan, the search indexer, or a SQLite handle sqlx's worker thread hasn't
/// finished closing yet; the retry clears those transient holders. A genuinely
/// stuck file (e.g. the daemon holding it for real) still fails, so the caller's
/// fallback/rollback still runs. First-attempt success is the common fast path;
/// Unix renames don't hit this but the retry is harmless there.
///
/// The blocking variant is deliberate: the only caller is
/// `finalize_encryption_swap`, reached from the tray's `block_on(migrate)`
/// startup gate before any other async work is scheduled, so the worst-case
/// backoff blocks nothing but the migration it's part of.
fn rename_with_retry(from: &Path, to: &Path) -> std::io::Result<()> {
    crate::retry::retry_transient_blocking(5, std::time::Duration::from_millis(100), || {
        std::fs::rename(from, to)
    })
}

/// Swap the freshly-written encrypted export at `tmp_path` into `path`, moving
/// the plaintext original to `backup_path` first. Extracted from
/// [`encrypt_in_place`] so the two-rename failure handling is unit-testable
/// without a real Windows share violation (see the module tests). Every rename
/// here goes through [`rename_with_retry`], so a transient Windows lock on any
/// of the moves (including the rollback) retries rather than failing the swap.
///
/// Preserves [`encrypt_in_place`]'s "a failed migration never loses data"
/// invariant across BOTH renames — each of which can fail on the same class of
/// Windows lock (a lingering handle / AV scan) that motivated this whole fix:
/// - First rename (`path` → `backup_path`) fails: the encrypted export is
///   useless without the swap, so drop it and leave the plaintext original
///   exactly where it is ("still plaintext, retry next launch").
/// - Second rename (`tmp_path` → `path`) fails: `path` has ALREADY been moved to
///   `backup_path`, so returning here would strand the user's data under a
///   backup name while the caller (seeing no `meridian.db`) creates a fresh
///   empty one. Roll back by renaming `backup_path` → `path` first, so the state
///   degrades to "still plaintext, data intact" rather than "no database". Only
///   if that rollback ALSO fails do we surface a hard error naming the file to
///   restore by hand — strictly the last resort.
fn finalize_encryption_swap(
    path: &Path,
    tmp_path: &Path,
    backup_path: &Path,
) -> anyhow::Result<()> {
    if let Err(e) = rename_with_retry(path, backup_path) {
        // On Windows `rename` fails with "os error 32" while another process
        // (the running daemon) still holds `meridian.db` open. Remove the
        // multi-GB encrypted export so it doesn't accumulate as an orphan every
        // startup (a real disk-exhaustion risk on a large DB); `key_unless_plaintext`
        // keeps the daemon and CLIs working against the plaintext file meanwhile.
        let _ = std::fs::remove_file(tmp_path);
        tracing::error!(
            error = %e,
            stage = "move_original_aside",
            "encryption swap failed - database left plaintext, will retry next launch"
        );
        return Err(e).context(
            "encrypt_in_place: failed to move plaintext original aside \
             (is meridian.db still open by the daemon?)",
        );
    }
    for suffix in ["-wal", "-shm"] {
        let sidecar = std::path::PathBuf::from(format!("{}{}", path.display(), suffix));
        let _ = std::fs::remove_file(sidecar); // checkpointed to empty; safe to drop
    }
    if let Err(e) = rename_with_retry(tmp_path, path) {
        // `path` was already moved to `backup_path` above; put it back so we
        // never leave the user with no database at all.
        match rename_with_retry(backup_path, path) {
            Ok(()) => {
                let _ = std::fs::remove_file(tmp_path);
                tracing::error!(
                    error = %e,
                    stage = "move_encrypted_into_place",
                    "encryption swap failed - plaintext original restored, will retry next launch"
                );
                Err(e).context(
                    "encrypt_in_place: failed to move encrypted export into place; \
                     restored the plaintext original (will retry next launch)",
                )
            }
            Err(restore_err) => {
                // The only branch that needs a human. Logged at ERROR with no
                // path attached (a home-dir path is user data): the message and
                // the stage are enough to identify it in telemetry, and the
                // returned error carries the path for the local operator.
                tracing::error!(
                    error = %e,
                    restore_error = %restore_err,
                    stage = "restore_original",
                    "encryption swap failed AND rollback failed - the database needs restoring by hand"
                );
                Err(e).context(format!(
                    "encrypt_in_place: failed to move encrypted export into place AND failed \
                 to restore the plaintext original ({restore_err:#}) - the previous data \
                 is intact at {}; restore it by hand",
                    backup_path.display(),
                ))
            }
        }
    } else {
        Ok(())
    }
}

/// Migrate an existing plaintext `meridian.db` to SQLCipher encryption at rest,
/// in place. No-op if `path` doesn't exist yet (fresh install — the caller
/// creates it encrypted from scratch) or is already encrypted.
///
/// Safety: the original file is never modified or removed until the encrypted
/// export has been fully written and verified — on any failure partway through,
/// `path` is left exactly as it was, so a failed migration degrades to "still
/// plaintext, retry next startup" rather than risking data loss. The plaintext
/// original is kept alongside the encrypted result (renamed with a timestamped
/// suffix), not deleted, so a bad migration is always recoverable by hand.
pub async fn encrypt_in_place(path: &Path, key_hex: &str) -> anyhow::Result<()> {
    validate_key_hex(key_hex)?;
    if !path.exists() {
        // "No database" normally means a fresh install, and the caller goes on
        // to create one. But this function ALSO briefly unlinks `path` (see the
        // two renames at the end), so a crash in that window leaves no database
        // AND leftovers beside it. Treating that as a fresh install lets the
        // caller create an empty encrypted DB while the user's real data sits
        // untouched in those leftovers - the data is not lost, but nothing
        // looks for it and nothing says so.
        //
        // Distinguishing the two is just "are there leftovers?", so say so
        // loudly rather than returning Ok. This does NOT recover automatically:
        // choosing between the encrypted export and the plaintext backup is a
        // judgement call about which is newer, and guessing wrong overwrites
        // real data. Surfacing it turns a silent empty-app into a supportable
        // report with the exact filenames to restore.
        for leftover in interrupted_migration_leftovers(path) {
            tracing::error!(
                db = %path.display(),
                leftover = %leftover.display(),
                "meridian.db is missing but an interrupted encryption migration left data \
                 beside it - a new empty database is about to be created. Do not discard \
                 this file; it holds the previous contents"
            );
        }
        return Ok(());
    }
    if !is_plaintext_sqlite(path) {
        return Ok(());
    }

    let uri = path.display().to_string();
    // `create_if_missing(true)` here is a no-op for THIS file (already checked
    // to exist above) — it's needed because SQLite's ATTACH inherits the main
    // connection's open flags, so the encrypted target ATTACHed below can't be
    // created at all unless the main connection itself was opened with the
    // create flag set.
    let mut conn = SqliteConnectOptions::from_str(&uri)
        .with_context(|| format!("invalid SQLite path: {uri}"))?
        .create_if_missing(true)
        .connect()
        .await
        .context("encrypt_in_place: failed to open existing plaintext database")?;

    // Fold the WAL into the main file so the export below sees every committed
    // write, and the plaintext original's -wal/-shm sidecars are safely
    // empty/removable afterward.
    conn.execute("PRAGMA wal_checkpoint(TRUNCATE);")
        .await
        .context("encrypt_in_place: WAL checkpoint failed")?;

    let tmp_path = path.with_extension("db.encrypting-tmp");
    let _ = std::fs::remove_file(&tmp_path); // best-effort cleanup of a prior interrupted attempt

    let attach_sql = format!(
        "ATTACH DATABASE '{}' AS encrypted_export KEY \"x'{}'\";",
        tmp_path.display(),
        key_hex
    );
    conn.execute(attach_sql.as_str())
        .await
        .context("encrypt_in_place: ATTACH failed")?;
    conn.execute("SELECT sqlcipher_export('encrypted_export');")
        .await
        .context("encrypt_in_place: sqlcipher_export failed")?;
    conn.execute("DETACH DATABASE encrypted_export;")
        .await
        .context("encrypt_in_place: DETACH failed")?;
    // Deterministically CLOSE the connection (releasing the OS file handle on
    // both the plaintext original and the encrypted export) before the rename
    // below — a plain `drop(conn)` does NOT: sqlx runs SQLite on a worker
    // thread, so dropping only *queues* the close, and on Windows the handle is
    // frequently still open when the rename runs, failing it with the very
    // os-error-32 this migration exists to survive. `close().await` waits for
    // the sqlite3_close to actually complete. Best-effort — if it errors we
    // still proceed (rename_with_retry covers a lingering handle either way).
    if let Err(e) = conn.close().await {
        tracing::warn!(error = %e, "encrypt_in_place: connection close returned an error; continuing to the swap");
    }

    let backup_path = path.with_extension(format!(
        "db.plaintext-backup-{}",
        chrono::Utc::now().format("%Y%m%d%H%M%S")
    ));
    finalize_encryption_swap(path, &tmp_path, &backup_path)?;

    tracing::info!(
        db = %path.display(),
        backup = %backup_path.display(),
        "migrated meridian.db from plaintext to SQLCipher encryption at rest"
    );
    Ok(())
}

/// Export a plaintext snapshot of an encrypted database to `out_path`, for
/// consumers (currently `meridian-mcp`'s `sql.js` reader) that cannot open a
/// SQLCipher-encrypted file directly. Overwrites `out_path` if it exists.
pub async fn export_plaintext(
    encrypted_db_path: &Path,
    key_hex: &str,
    out_path: &Path,
) -> anyhow::Result<()> {
    validate_key_hex(key_hex)?;
    let uri = encrypted_db_path.display().to_string();
    // See the identical comment in `encrypt_in_place` — ATTACH inherits the
    // main connection's open flags, so `plaintext_export` below can't be
    // created unless this connection was opened with the create flag set.
    let mut conn = SqliteConnectOptions::from_str(&uri)
        .with_context(|| format!("invalid SQLite path: {uri}"))?
        .create_if_missing(true)
        .connect()
        .await
        .context("export_plaintext: failed to open encrypted database")?;

    conn.execute(key_pragma(key_hex).as_str())
        .await
        .context("export_plaintext: PRAGMA key failed")?;
    // A wrong key doesn't error on `PRAGMA key` itself — SQLCipher only
    // discovers a bad key on the first real page read. Force that check now
    // so a wrong key fails loudly here instead of silently exporting garbage.
    conn.execute("SELECT count(*) FROM sqlite_master;")
        .await
        .context("export_plaintext: failed to read database — wrong encryption key?")?;

    let _ = std::fs::remove_file(out_path);
    let attach_sql = format!(
        "ATTACH DATABASE '{}' AS plaintext_export KEY '';",
        out_path.display()
    );
    conn.execute(attach_sql.as_str())
        .await
        .context("export_plaintext: ATTACH failed")?;
    conn.execute("SELECT sqlcipher_export('plaintext_export');")
        .await
        .context("export_plaintext: sqlcipher_export failed")?;
    conn.execute("DETACH DATABASE plaintext_export;")
        .await
        .context("export_plaintext: DETACH failed")?;

    // The ATTACH-created file inherits the process umask, typically 0644. This
    // is the ONE place the SQLCipher rollout deliberately writes a full,
    // unencrypted copy of the activity database, so leaving it group- and
    // world-readable would undo — for that file — exactly the local-multi-user
    // threat the rest of the encryption work exists to cover. It gets the same
    // 0600 the encrypted original deserves.
    //
    // Tightened AFTER the export rather than pre-creating the file: SQLCipher's
    // ATTACH wants to create it itself, and `remove_file` above deliberately
    // clears any stale copy first.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(out_path, std::fs::Permissions::from_mode(0o600)).with_context(
            || {
                format!(
                    "export_plaintext: failed to restrict permissions on {}",
                    out_path.display()
                )
            },
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlx::Row;

    const TEST_KEY: &str = "3a15689f73412c29d7ed3b902a01e33dbd5f767dc37b792e19ac9e2366bf2cd2";
    const OTHER_KEY: &str = "0000000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fn sqlite_uri_to_path_extracts_file_path() {
        use std::path::PathBuf;
        // The daemon/tray form: `format!("sqlite://{path}")`.
        assert_eq!(
            sqlite_uri_to_path("sqlite://C:/Users/x/.meridian/meridian.db"),
            Some(PathBuf::from("C:/Users/x/.meridian/meridian.db"))
        );
        // A POSIX absolute path keeps its leading slash.
        assert_eq!(
            sqlite_uri_to_path("sqlite:///home/u/.meridian/meridian.db"),
            Some(PathBuf::from("/home/u/.meridian/meridian.db"))
        );
        // A bare path (as encrypt_in_place / the tests pass).
        assert_eq!(
            sqlite_uri_to_path("/tmp/plain.db"),
            Some(PathBuf::from("/tmp/plain.db"))
        );
        // Query params are stripped (single and multi-param).
        assert_eq!(
            sqlite_uri_to_path("sqlite://C:/db.sqlite?mode=ro"),
            Some(PathBuf::from("C:/db.sqlite"))
        );
        assert_eq!(
            sqlite_uri_to_path("sqlite:///home/u/x.db?mode=ro&cache=shared"),
            Some(PathBuf::from("/home/u/x.db"))
        );
        // The `file:` scheme (with and without the double slash).
        assert_eq!(
            sqlite_uri_to_path("file:///home/u/x.db"),
            Some(PathBuf::from("/home/u/x.db"))
        );
        assert_eq!(
            sqlite_uri_to_path("file:relative.db"),
            Some(PathBuf::from("relative.db"))
        );
        // In-memory (any spelling) has nothing on disk to inspect.
        assert_eq!(sqlite_uri_to_path("sqlite::memory:"), None);
        assert_eq!(sqlite_uri_to_path(":memory:"), None);
        assert_eq!(sqlite_uri_to_path("sqlite://:memory:"), None);
        // An empty target yields nothing to check.
        assert_eq!(sqlite_uri_to_path(""), None);
        assert_eq!(sqlite_uri_to_path("sqlite://"), None);
    }

    /// The desync a half-finished `encrypt_in_place` leaves — an on-disk
    /// plaintext file while `MERIDIAN_DB_KEY` is still configured — must NOT
    /// stall (pre-fix: SQLCipher hangs on the first pragma until the 10s
    /// acquire timeout → "pool timed out"). The guard drops the key, opens
    /// plaintext, and reads the data back well under that timeout.
    #[tokio::test]
    async fn open_pool_ignores_key_on_plaintext_file() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("meridian.db");

        // Seed a plaintext DB with data (no key).
        let pool = open_pool_with_key(&db_path.display().to_string(), None, true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (99)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(is_plaintext_sqlite(&db_path));

        // Reopen the SAME plaintext file WITH a key configured. Must not stall.
        let opened = tokio::time::timeout(
            std::time::Duration::from_secs(5),
            open_pool_with_key(&db_path.display().to_string(), Some(TEST_KEY), false, &[]),
        )
        .await
        .expect("opening a plaintext file with a key set must not stall")
        .expect("plaintext open should succeed with the key dropped");
        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&opened)
            .await
            .unwrap();
        assert_eq!(row.get::<i64, _>(0), 99);
        opened.close().await;

        // The read-only opener must apply the same guard.
        let ro = tokio::time::timeout(
            std::time::Duration::from_secs(5),
            open_pool_with_key_readonly(&db_path.display().to_string(), Some(TEST_KEY)),
        )
        .await
        .expect("read-only opening a plaintext file with a key set must not stall")
        .expect("plaintext read-only open should succeed with the key dropped");
        let row = sqlx::query("SELECT x FROM t").fetch_one(&ro).await.unwrap();
        assert_eq!(row.get::<i64, _>(0), 99);
        ro.close().await;
    }

    /// The inverse invariant that keeps the guard honest: an actually
    /// ENCRYPTED file with a key set must still open encrypted and read its
    /// data. If the guard ever dropped the key here, every encrypted DB would
    /// fail to decrypt — so this pins that it only fires on plaintext files.
    #[tokio::test]
    async fn open_pool_keeps_key_on_encrypted_file() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("meridian.db");

        // Create an encrypted db with data.
        let pool = open_pool_with_key(&db_path.display().to_string(), Some(TEST_KEY), true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (7)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(!is_plaintext_sqlite(&db_path), "file should be ciphertext");

        // Reopen WITH the key — the guard must keep it (file is not plaintext).
        let opened = open_pool_with_key(&db_path.display().to_string(), Some(TEST_KEY), false, &[])
            .await
            .expect("encrypted open with the correct key should succeed");
        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&opened)
            .await
            .unwrap();
        assert_eq!(row.get::<i64, _>(0), 7);
        opened.close().await;

        // Read-only likewise keeps the key.
        let ro = open_pool_with_key_readonly(&db_path.display().to_string(), Some(TEST_KEY))
            .await
            .expect("encrypted read-only open with the correct key should succeed");
        let row = sqlx::query("SELECT x FROM t").fetch_one(&ro).await.unwrap();
        assert_eq!(row.get::<i64, _>(0), 7);
        ro.close().await;
    }

    /// A fresh install (file does not exist yet) with a key + create_if_missing
    /// must still create an ENCRYPTED file. The guard keys off an *existing*
    /// plaintext file, so a missing path must not drop the key and leave a new
    /// db created in the clear — otherwise new users would silently never get
    /// encryption at rest.
    #[tokio::test]
    async fn open_pool_creates_encrypted_on_missing_file() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("fresh.db");
        assert!(!db_path.exists());

        let pool = open_pool_with_key(&db_path.display().to_string(), Some(TEST_KEY), true, &[])
            .await
            .expect("fresh encrypted create should succeed");
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (1)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;

        // The new file must be ciphertext, not created in the clear.
        assert!(
            !is_plaintext_sqlite(&db_path),
            "a fresh db opened with a key must be encrypted"
        );

        // ...and it round-trips with the correct key.
        let reopened =
            open_pool_with_key(&db_path.display().to_string(), Some(TEST_KEY), false, &[])
                .await
                .expect("reopen with the correct key should succeed");
        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&reopened)
            .await
            .unwrap();
        assert_eq!(row.get::<i64, _>(0), 1);
        reopened.close().await;
    }

    /// The tray's first-launch regression, end to end: a pool built while
    /// `meridian.db` does not exist yet must NOT be permanently dead. It may
    /// fail while the file is absent, but the *same handle* has to start
    /// working once the daemon creates the database — no reopen, no restart.
    ///
    /// Guards the bug this opener was added for: the tray built its pool
    /// seconds before the daemon created the file, cached the failure as
    /// `None`, and ran its whole session with every DB command returning empty
    /// and every captured frame discarded.
    #[tokio::test]
    async fn lazy_pool_recovers_once_the_database_appears() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("meridian.db");
        let uri = db_path.display().to_string();
        assert!(!db_path.exists());

        // Built against nothing — this must still hand back a usable handle.
        // (Not asserting that a query fails while the file is absent: sqlx
        // retries a failed connect until the 10s acquire timeout, so such an
        // assertion would just make this test sleep for ten seconds. That
        // retry window is itself useful here — a command issued during the
        // first-launch gap tends to succeed rather than error.)
        let pool = open_pool_with_key_lazy(&uri, Some(TEST_KEY))
            .await
            .expect("building a lazy pool must not require the file to exist");

        // The daemon creates and populates the database (encrypted, as it does
        // whenever MERIDIAN_DB_KEY is set).
        let daemon = open_pool_with_key(&uri, Some(TEST_KEY), true, &[])
            .await
            .expect("daemon-side create should succeed");
        sqlx::query("CREATE TABLE capture_frames (id INTEGER PRIMARY KEY)")
            .execute(&daemon)
            .await
            .unwrap();
        sqlx::query("INSERT INTO capture_frames (id) VALUES (7)")
            .execute(&daemon)
            .await
            .unwrap();
        daemon.close().await;

        // The ORIGINAL handle now works — this is the whole point.
        let row = sqlx::query("SELECT id FROM capture_frames")
            .fetch_one(&pool)
            .await
            .expect("the lazy pool must connect once the database exists");
        assert_eq!(row.get::<i64, _>(0), 7);
        pool.close().await;
    }

    /// The lazy opener resolves the key/plaintext question per connection, so a
    /// plaintext database is opened unencrypted even though the pool was built
    /// with a key — and built before the file existed, so nothing could have
    /// been probed up front. Same guarantee [`key_unless_plaintext`] gives the
    /// eager opener, at the point a lazy pool can actually make it.
    #[tokio::test]
    async fn lazy_pool_drops_the_key_for_a_plaintext_database() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("meridian.db");
        let uri = db_path.display().to_string();

        let pool = open_pool_with_key_lazy(&uri, Some(TEST_KEY)).await.unwrap();

        // Create it PLAINTEXT after the pool was built (the stuck
        // encrypt-in-place state: key configured, file still in the clear).
        let plain = open_pool_with_key(&uri, None, true, &[]).await.unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&plain)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (3)")
            .execute(&plain)
            .await
            .unwrap();
        plain.close().await;
        assert!(is_plaintext_sqlite(&db_path));

        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&pool)
            .await
            .expect("a keyed lazy pool must still read a plaintext database");
        assert_eq!(row.get::<i64, _>(0), 3);
        pool.close().await;
    }

    /// First rename (`path` → `backup`) fails: the encrypted export must be
    /// cleaned up and the plaintext original left exactly as it was. Forced
    /// portably by making `backup` an existing non-empty directory, which
    /// `rename` refuses to overwrite with a file.
    #[test]
    fn finalize_swap_cleans_up_when_first_rename_fails() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("meridian.db");
        let tmp = dir.path().join("meridian.db.encrypting-tmp");
        let backup = dir.path().join("backup-dir");
        std::fs::create_dir(&backup).unwrap();
        std::fs::write(backup.join("occupant"), b"x").unwrap(); // non-empty → rename fails

        std::fs::write(&path, b"ORIGINAL-PLAINTEXT").unwrap();
        std::fs::write(&tmp, b"ENCRYPTED-EXPORT").unwrap();

        let err = finalize_encryption_swap(&path, &tmp, &backup).unwrap_err();
        assert!(!tmp.exists(), "stale encrypted export must be removed");
        assert_eq!(
            std::fs::read(&path).unwrap(),
            b"ORIGINAL-PLAINTEXT",
            "plaintext original must be left intact"
        );
        assert!(
            format!("{err:#}").contains("move plaintext original aside"),
            "unexpected error: {err:#}"
        );
    }

    /// Second rename (`tmp` → `path`) fails AFTER the first already moved
    /// `path` → `backup`: the original must be rolled back into place so we
    /// never leave "no database" for the caller to replace with an empty one.
    /// Forced portably by pointing `tmp` at a file that does not exist.
    #[test]
    fn finalize_swap_rolls_back_when_second_rename_fails() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("meridian.db");
        let backup = dir.path().join("meridian.db.plaintext-backup-x");
        let tmp = dir.path().join("does-not-exist.tmp"); // rename(tmp, path) → ENOENT

        std::fs::write(&path, b"ORIGINAL-PLAINTEXT").unwrap();

        let err = finalize_encryption_swap(&path, &tmp, &backup).unwrap_err();
        assert!(
            path.exists(),
            "the plaintext original must be restored, not stranded under the backup name"
        );
        assert_eq!(
            std::fs::read(&path).unwrap(),
            b"ORIGINAL-PLAINTEXT",
            "restored data must match the original"
        );
        assert!(
            !backup.exists(),
            "backup should have been renamed back to path"
        );
        assert!(
            format!("{err:#}").contains("restored the plaintext original"),
            "unexpected error: {err:#}"
        );
    }

    #[test]
    fn rename_with_retry_succeeds_and_surfaces_persistent_failure() {
        let dir = tempfile::tempdir().unwrap();
        let a = dir.path().join("a");
        let b = dir.path().join("b");
        std::fs::write(&a, b"x").unwrap();
        // Happy path: renames (first attempt).
        rename_with_retry(&a, &b).unwrap();
        assert!(b.exists() && !a.exists());
        // A persistent failure (missing source) still surfaces an Err after the
        // retries are exhausted, so the caller's fallback/rollback runs.
        let missing = dir.path().join("nope");
        assert!(rename_with_retry(&missing, &b).is_err());
    }

    /// The happy path: both renames succeed — plaintext original preserved under
    /// the backup name, encrypted export now at `path`.
    #[test]
    fn finalize_swap_succeeds_and_preserves_backup() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("meridian.db");
        let tmp = dir.path().join("meridian.db.encrypting-tmp");
        let backup = dir.path().join("meridian.db.plaintext-backup-x");

        std::fs::write(&path, b"PLAINTEXT").unwrap();
        std::fs::write(&tmp, b"CIPHERTEXT").unwrap();

        finalize_encryption_swap(&path, &tmp, &backup).unwrap();
        assert_eq!(
            std::fs::read(&path).unwrap(),
            b"CIPHERTEXT",
            "encrypted export moved into place"
        );
        assert_eq!(
            std::fs::read(&backup).unwrap(),
            b"PLAINTEXT",
            "plaintext backup preserved"
        );
        assert!(!tmp.exists(), "tmp consumed by the rename");
    }

    #[test]
    fn validate_key_hex_rejects_bad_input() {
        assert!(validate_key_hex(TEST_KEY).is_ok());
        assert!(validate_key_hex("too-short").is_err());
        assert!(validate_key_hex(&"g".repeat(64)).is_err()); // not hex
        assert!(validate_key_hex(&"a".repeat(63)).is_err()); // wrong length
    }

    #[tokio::test]
    async fn is_plaintext_sqlite_detects_plain_and_encrypted() {
        let dir = tempfile::tempdir().unwrap();
        let plain_path = dir.path().join("plain.db");
        let enc_path = dir.path().join("enc.db");

        // A plain file created without a key.
        let pool = open_pool_with_key(&plain_path.display().to_string(), None, true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(is_plaintext_sqlite(&plain_path));

        // An encrypted file created with a key.
        let pool = open_pool_with_key(&enc_path.display().to_string(), Some(TEST_KEY), true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(!is_plaintext_sqlite(&enc_path));
    }

    #[tokio::test]
    async fn encrypt_in_place_migrates_and_preserves_data() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("meridian.db");

        // Seed a plaintext DB with data.
        let pool = open_pool_with_key(&db_path.display().to_string(), None, true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (42)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;
        assert!(is_plaintext_sqlite(&db_path));

        encrypt_in_place(&db_path, TEST_KEY).await.unwrap();
        assert!(!is_plaintext_sqlite(&db_path));

        // A plaintext backup was preserved (never deleted).
        let has_backup = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .any(|e| e.file_name().to_string_lossy().contains("plaintext-backup"));
        assert!(has_backup, "expected a preserved plaintext backup file");

        // Correct key reads the migrated data back intact.
        let pool = open_pool_with_key(&db_path.display().to_string(), Some(TEST_KEY), false, &[])
            .await
            .unwrap();
        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(row.get::<i64, _>(0), 42);
        pool.close().await;

        // Wrong key must never silently return the real data — whether that
        // surfaces as an outright connect failure, a query error, or (as
        // observed in practice — SQLCipher can stall rather than error
        // cleanly when a later pragma tries to touch an undecryptable page)
        // simply never producing a usable connection in reasonable time, all
        // three are acceptable: the one unacceptable outcome is a readable
        // row 42 coming back on the wrong key.
        let wrong_attempt = tokio::time::timeout(
            std::time::Duration::from_secs(5),
            open_pool_with_key(&db_path.display().to_string(), Some(OTHER_KEY), false, &[]),
        )
        .await;
        match wrong_attempt {
            Err(_elapsed) => {}      // timed out opening — acceptable, not the real key
            Ok(Err(_open_err)) => {} // failed to open — acceptable
            Ok(Ok(wrong)) => {
                let result = sqlx::query("SELECT x FROM t").fetch_one(&wrong).await;
                assert!(result.is_err(), "reading with the wrong key should fail");
                wrong.close().await;
            }
        }
    }

    /// The crash window in `encrypt_in_place` briefly unlinks `meridian.db`.
    /// If the process dies there, the next run sees no database and the caller
    /// creates an empty one - while the real data sits beside it in the
    /// encrypted export and the plaintext backup. Absence alone cannot be
    /// treated as "fresh install"; the leftovers are what distinguish them.
    #[test]
    fn leftovers_distinguish_a_crashed_migration_from_a_fresh_install() {
        let dir = tempfile::tempdir().unwrap();
        let db = dir.path().join("meridian.db");

        // Fresh install: nothing beside it.
        assert!(interrupted_migration_leftovers(&db).is_empty());

        // Names must match exactly what `encrypt_in_place` writes.
        let tmp = db.with_extension("db.encrypting-tmp");
        let backup = db.with_extension("db.plaintext-backup-20260728120000");
        std::fs::write(&tmp, b"encrypted").unwrap();
        std::fs::write(&backup, b"plaintext").unwrap();

        let found = interrupted_migration_leftovers(&db);
        assert!(
            found.contains(&tmp),
            "encrypted export not found: {found:?}"
        );
        assert!(
            found.contains(&backup),
            "plaintext backup not found: {found:?}"
        );

        // An unrelated neighbour must not be mistaken for a leftover, or the
        // error would fire on genuinely fresh installs.
        std::fs::write(dir.path().join("meridian.db-wal"), b"x").unwrap();
        std::fs::write(dir.path().join("other.db"), b"x").unwrap();
        assert_eq!(interrupted_migration_leftovers(&db).len(), 2);
    }

    #[tokio::test]
    async fn export_plaintext_roundtrips_encrypted_data() {
        let dir = tempfile::tempdir().unwrap();
        let enc_path = dir.path().join("enc.db");
        let out_path = dir.path().join("plain-export.db");

        let pool = open_pool_with_key(&enc_path.display().to_string(), Some(TEST_KEY), true, &[])
            .await
            .unwrap();
        sqlx::query("CREATE TABLE t (x INTEGER)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query("INSERT INTO t (x) VALUES (7)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;

        export_plaintext(&enc_path, TEST_KEY, &out_path)
            .await
            .unwrap();
        assert!(is_plaintext_sqlite(&out_path));

        let pool = open_pool_with_key(&out_path.display().to_string(), None, false, &[])
            .await
            .unwrap();
        let row = sqlx::query("SELECT x FROM t")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(row.get::<i64, _>(0), 7);
        pool.close().await;

        // This is the one file the encryption work deliberately writes in
        // plaintext, so it must not inherit the umask's usual 0644 - that
        // would leave a full, unencrypted copy of the activity database
        // readable by every other local account.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&out_path).unwrap().permissions().mode() & 0o777;
            assert_eq!(
                mode, 0o600,
                "plaintext export is readable by others: {mode:o}"
            );
        }
    }
}
