//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
//
// Settings → Worklogs. Its own tab (not buried in Notifications) because this is
// one of the two or three choices that actually change what Meridian DOES with
// your day, not just how it tells you about it. Same setting, same copy tone as
// the one-time <WorklogAutoGenerateDialog> nudge on the Timeline — this is where
// you come back to change your mind.
//
// Draft-only, always. Auto-generate never approves or posts to your tracker -
// that stays a deliberate click in the day-task panel, same as today. The only
// choice here is WHEN Meridian checks (once a day, at the picked local time);
// the 30-minute qualifying threshold is fixed, not user-configurable.

'use client'

import { useState } from 'react'
import { Switch } from '@/components/ui/Switch'
import { TextInput } from '@/components/ui/TextInput'
import type { RuntimeSettings } from '@/lib/settings'
import type { IntegrationsResponse } from '@/lib/api-types'
import { TRACKERS, availableTrackerNames } from '@/lib/integrations'
import { SectionCard, SectionHeader, FieldRow, SaveButton, type SaveStatus } from './fields'

const PRESETS = [
  { time: '13:00', label: '1:00 PM' },
  { time: '18:00', label: '6:00 PM' },
  { time: '21:00', label: '9:00 PM' },
] as const

function timeLabel(hhmm: string): string {
  const preset = PRESETS.find((p) => p.time === hhmm)
  if (preset) return preset.label
  const [h, m] = hhmm.split(':').map(Number)
  const period = h >= 12 ? 'PM' : 'AM'
  const h12 = ((h + 11) % 12) + 1
  return `${h12}:${String(m).padStart(2, '0')} ${period}`
}

export function WorklogSection({ settings, patch, save, integrations }: {
  settings: RuntimeSettings
  patch: (changes: Partial<RuntimeSettings>) => void
  save: (fields: Partial<RuntimeSettings>, setStatus?: (s: SaveStatus) => void) => Promise<void>
  integrations: IntegrationsResponse | null
}) {
  const [status, setStatus] = useState<SaveStatus>('idle')
  const enabled = settings.worklog_auto_generate_time != null
  const time = settings.worklog_auto_generate_time ?? '18:00'
  // Nothing to draft against without a tracker connected - there's no ticket to
  // match or propose against, so offering the toggle would just be a dead end.
  const hasTracker = !!integrations && TRACKERS.some((t) => integrations[t.id])

  return (
    <div className="max-w-[640px] flex flex-col gap-5">
      <div>
        <p className="mt-label" style={{ color: 'var(--color-state-proposal)' }}>Drafts</p>
        <h1 className="mt-title-lg mt-1.5" style={{ color: 'var(--t-title)' }}>Worklogs</h1>
        <p className="mt-body-sm mt-2 max-w-[520px]" style={{ color: 'var(--t-muted)' }}>
          Meridian drafts worklogs from your day&apos;s work, ready to review at a time you pick.
        </p>
      </div>

      {!hasTracker ? (
        <SectionCard>
          <SectionHeader>Auto-generate</SectionHeader>
          <p className="mt-body-sm" style={{ color: 'var(--t-muted)' }}>
            Connect a tracker first - {availableTrackerNames()}.
          </p>
        </SectionCard>
      ) : (
        <SectionCard>
          <SectionHeader>Auto-generate</SectionHeader>
          <FieldRow
            label="Auto-draft worklogs"
            description={enabled ? `Drafts ready by ${timeLabel(time)}.` : 'Off - generate each one yourself.'}
          >
            <Switch
              checked={enabled}
              onCheckedChange={(v) => patch({ worklog_auto_generate_time: v ? '18:00' : null, worklog_auto_generate_prompted: true })}
            />
          </FieldRow>

          {enabled && (
            <>
              <FieldRow label="Check time" description="Once a day.">
                <div className="flex items-center gap-1.5 p-1 rounded-xl bg-wrap flex-wrap">
                  {PRESETS.map((p) => (
                    <button key={p.time} type="button" onClick={() => patch({ worklog_auto_generate_time: p.time })}
                      className="rounded-lg transition-colors"
                      style={{
                        padding: '6px 12px', fontSize: 12, fontWeight: 600,
                        color: time === p.time ? '#fff' : 'var(--t-muted)',
                        background: time === p.time ? 'var(--color-state-proposal)' : 'transparent',
                        border: 'none', cursor: 'pointer',
                      }}>
                      {p.label}
                    </button>
                  ))}
                </div>
              </FieldRow>
              <FieldRow label="Custom time" description="">
                <TextInput type="time" width={110} value={time} onChange={(v) => patch({ worklog_auto_generate_time: v })} />
              </FieldRow>
              <p className="text-[11px]" style={{ color: 'var(--t-faint)' }}>
                Still working on a task? Regenerate anytime from its detail panel.
              </p>
            </>
          )}

          <SaveButton
            status={status}
            onClick={() => save({
              worklog_auto_generate_time: settings.worklog_auto_generate_time,
              worklog_auto_generate_prompted: settings.worklog_auto_generate_prompted,
            }, setStatus)}
          />
        </SectionCard>
      )}
    </div>
  )
}
