//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
//
// The entire one-pager Meridian Timeline app. ui/app/page.tsx renders this
// directly (no DashboardShell/Sidebar/CommandBar). Owns the selected day, the
// selected hour (Overview ↔ Hour-detail), and which modal is open; calls
// useTimelineData ONCE at the top and threads it down. Applies the persisted
// theme on mount. Fluid app-like layout (h-[100svh], own inner scroll regions)
// — the mock's fake window chrome is intentionally dropped (Tauri provides it).

'use client'

import { useEffect, useState } from 'react'
import { invoke, load, subscribe } from '@/lib/bridge'
import type { RuntimeSettings } from '@/lib/settings'
import { applyTheme } from '@/lib/theme'
import HealthBanner from '@/components/HealthBanner'
import { useTimelineData } from './useTimelineData'
import { dayString, shiftDay, isPending } from './types'
import { Toolbar } from './Toolbar'
import { DayTaskColumn } from './DayTaskColumn'
import type { DayTaskDetail } from './DayTaskDetailPanel'
import { RightPanel } from './RightPanel'
import { useTutorial } from '@/components/tutorial/useTutorial'
import { FloatingDraftsPill } from './FloatingDraftsPill'
import { ReviewModal } from './ReviewModal'
// Board Cleanup temporarily disabled (not deleted) — re-enable by uncommenting
// this import alongside the `'cleanup'` modal-render branch below and
// OverviewPanel.tsx's CTA.
// import { CleanupModal } from './CleanupModal'
import { SettingsModal } from './SettingsModal'
import { PlanModal } from './PlanModal'
import { armResume } from '@/components/plan/useTaskComposer'
import { TasksModal } from './TasksModal'
import { TaskDetailDialog } from './TaskDetailDialog'
import { ReportModal } from './ReportModal'
import { LlmLabScreen } from './llmlab/LlmLabScreen'
import { WhatsNewModal } from './WhatsNewModal'
import { WorklogAutoGenerateDialog } from './WorklogAutoGenerateDialog'
import { DaySummaryOverlay } from '@/components/summary/DaySummaryOverlay'
import type { AppInfo } from '@/lib/api-types'
import type { SettingsSection } from './settings/types'

export type ActiveModal =
  | 'review' | 'cleanup' | 'settings' | 'plan' | 'tasks' | 'report' | 'llmlab' | 'whats-new' | 'summary' | null

export default function MeridianTimelineShell() {
  const [day, setDay] = useState<string>(dayString(0))
  const [selectedHour, setSelectedHour] = useState<number | null>(null)
  // A day-task card clicked in the timeline column — its detail replaces "Today
  // at a glance" in the right panel (same swap the hour/approved-card detail
  // uses), so the timeline keeps the clicked card highlighted and the rest dulled.
  const [selectedDayTask, setSelectedDayTask] = useState<DayTaskDetail | null>(null)
  // Set only when a specific worklog card (not the hour row itself) was
  // clicked — narrows the Hour-detail panel to that one card instead of every
  // ticket in the hour, and suppresses the row-level highlight (the card
  // itself gets the "popped forward" treatment instead).
  const [selectedCardKey, setSelectedCardKey] = useState<string | null>(null)
  const [activeModal, setActiveModal] = useState<ActiveModal>(null)
  // Set when a still-drafted card was clicked directly (as opposed to the
  // floating pill / nav, which review the whole pending queue) — scopes the
  // Review dialog to just that one ticket instead of the full queue.
  const [reviewFocusKey, setReviewFocusKey] = useState<string | null>(null)
  // Which Settings tab to land on when the modal opens — set by callers that
  // deep-link (e.g. the nav pill's "Integrations" item); undefined defaults
  // to Settings' own DEFAULT_SETTINGS_SECTION.
  const [settingsSection, setSettingsSection] = useState<SettingsSection | undefined>(undefined)
  // Set only when Settings was opened to finish a required step, so it can drop its
  // incidental dismissals. See ModalShell's `lock`.
  //
  // TWO STRENGTHS, and the difference is whether a way out exists elsewhere. Inside the
  // walkthrough this is `'required'`: connecting an engine is not optional there, and the
  // tour's own Skip sits above the modal at z-9000 as the escape hatch. Outside it, the
  // same "Draft with AI with no provider" press gets `'soft'` - no Escape or backdrop, but
  // a plainly labelled exit - because there IS no overlay to skip with, and a modal with
  // no way out and no walkthrough around it is simply a trapped app.
  const [settingsLock, setSettingsLock] = useState<'soft' | 'required' | undefined>(undefined)
  // The ticket detail dialog is a separate, stackable layer (not part of
  // ActiveModal) — it can open on top of the Tasks/Plan modals or straight
  // from the timeline/Overview panel.
  // `editable` is false when opened from a past day's Today's-focus checklist —
  // that day's plan is a record of what was focused on, not something to rewrite.
  const [openTask, setOpenTask] = useState<{ key: string; title?: string; editable: boolean } | null>(null)

  // Build channel, for dev-only surfaces (the LLM Lab). 'dev' only under
  // `tauri dev`/`cargo run` (cfg!(debug_assertions) via get_app_info) - staging
  // and prod builds never see the Lab button or modal, and its backing commands
  // are additionally refused there (commands/llm_lab.rs).
  const [channel, setChannel] = useState<string | null>(null)
  // One-time "let Meridian auto-generate worklogs" nudge — shown the first time
  // the Timeline loads with `worklog_auto_generate_prompted` still false. Covers
  // both a brand-new install (right after finishing setup, when the app first
  // launches into the Timeline) and a pre-existing one upgrading into this
  // feature (the flag defaults to false via `#[serde(default)]`, so it just
  // pops up next time they open the app) — one trigger point instead of a
  // wizard step plus a separate daemon-side re-prompt. Gated on having a
  // tracker connected — there's nothing to draft against otherwise, so asking
  // would just be confusing.
  const [showWorklogPrompt, setShowWorklogPrompt] = useState(false)
  const [worklogPrompted, setWorklogPrompted] = useState<boolean | null>(null)

  const data = useTimelineData(day)
  const { items, isSolo, connectedProviderName, connectedProviderIds, isToday, integrations } = data
  const pendingCount = items.filter(isPending).length
  const hasTracker = !!integrations && !isSolo

  // Apply the persisted theme on mount (before any round-trip resolves elsewhere).
  useEffect(() => {
    load<RuntimeSettings>('/api/settings', 'get_settings')
      .then(s => {
        applyTheme(s.theme)
        setWorklogPrompted(s.worklog_auto_generate_prompted)
      })
      .catch(() => {})
    load<AppInfo>('/api/version', 'get_app_info')
      .then(info => setChannel(info.channel))
      .catch(() => {})
  }, [])

  // Arm the worklog auto-generate nudge as soon as we know BOTH that it's never
  // been answered and that there's actually a tracker to draft against — fires
  // right away (subject to the "no other modal open" render gate below), not on
  // a delay.
  useEffect(() => {
    if (worklogPrompted !== false || !hasTracker) return
    setShowWorklogPrompt(true)
  }, [worklogPrompted, hasTracker])

  // NoticeBar lives at the root layout, outside this tree, so its
  // "Fix in Tasks" CTA reaches the Tasks modal via a window event instead of
  // props.
  useEffect(() => {
    const openTasks = () => setActiveModal('tasks')
    window.addEventListener('meridian:open-tasks', openTasks)
    return () => window.removeEventListener('meridian:open-tasks', openTasks)
  }, [])


  // THE LOCK BELONGS TO THE VISIT THAT SET IT. Clearing it in SettingsModal's `onClose` was
  // not enough: the walkthrough's Skip closes the modal by setting `activeModal` directly
  // (useTutorial's `finish`), which never runs that handler - so the flag survived, and the
  // NEXT ordinary Settings open, from the toolbar, came up locked with its sidebar blurred
  // for no reason the user could see. Tying it to the modal actually being open makes it
  // correct regardless of who closed it, or how.
  useEffect(() => {
    if (activeModal !== 'settings') setSettingsLock(undefined)
  }, [activeModal])

  // Tray-side openers (the daily plan auto-open, notification click-throughs)
  // steer this window to a specific view. subscribe()'s prime is the pull half
  // (`take_pending_deep_link` — a fresh window misses any event emitted before
  // its listener exists, so the tray parks the target in managed state), and
  // its listener is the push half (`dashboard-navigate`, for a window that is
  // already open and won't remount). Targets are the former route paths the
  // notification producers still use as `deep_link`s.
  useEffect(() => {
    const navigate = (target: string | null) => {
      if (target === '/plan') {
        setActiveModal('plan')
      } else if (target === '/worklogs') {
        setReviewFocusKey(null)
        setActiveModal('review')
      } else if (target === '/whats-new') {
        setActiveModal('whats-new')
      }
    }
    return subscribe<string | null>('/deep-link', 'take_pending_deep_link', 'dashboard-navigate', navigate)
  }, [])

  // Changing day resets the selected hour (its detail no longer applies).
  function shift(delta: number) {
    setSelectedHour(null)
    setSelectedCardKey(null)
    setSelectedDayTask(null)
    setDay(d => shiftDay(d, delta))
  }

  // Row-level selection (Quiet/solo rows, or blank space in a row) — shows
  // every ticket in the hour and clears any single-card selection.
  function selectHour(hour: number | null) {
    setSelectedHour(hour)
    setSelectedCardKey(null)
    // An hour's detail and a day-task's detail both own the right panel; the
    // latest click wins.
    if (hour !== null) setSelectedDayTask(null)
  }

  // A day-task claims the right panel; clear any hour detail so they don't fight
  // over it.
  function selectDayTask(detail: DayTaskDetail | null) {
    setSelectedDayTask(detail)
    if (detail) { setSelectedHour(null); setSelectedCardKey(null) }
  }

  // First-run walkthrough. Deliberately a THIN seam: it owns its own full
  // surface (`tutorial.screen`, an opaque layer over this whole view) and its
  // own example data, so nothing in the real timeline or right panel knows it
  // exists. All this shell gives it is the ability to open real modals — the
  // planner, Settings — which are the only places the walkthrough touches the
  // actual product. See components/tutorial/.
  const tutorial = useTutorial({
    setActiveModal,
    setSettingsSection,
    ready: !data.loading,
  })

  // "Draft with AI" pressed with no provider installed. The composer raises this
  // rather than taking a callback, because it is rendered two modals deep
  // (PlanModal → PlanView → TaskComposer) and threading an opener through both
  // would put a Settings concern in two components that have nothing to do with
  // Settings. Same window-event pattern as `meridian:open-tasks` above.
  useEffect(() => {
    const connectAi = () => {
      setSettingsSection('intelligence')
      // Just the FACT that they were sent here. SettingsModal owns what that means -
      // it makes the step required, labels the corner, and releases itself once a
      // provider is actually written. An exit label chosen here would be a promise
      // this component is in no position to keep.
      setSettingsLock(tutorial.running ? 'required' : 'soft')
      setActiveModal('settings')
    }
    window.addEventListener('meridian:connect-ai', connectAi)
    return () => window.removeEventListener('meridian:connect-ai', connectAi)
  }, [tutorial.running])

  // Bumped after a day-task is dismissed/merged so DayTaskColumn (which owns its
  // own fetch) reloads; the corrected task also leaves the detail panel.
  const [dayTaskRefresh, setDayTaskRefresh] = useState(0)
  function onDayTaskCorrected() {
    setSelectedDayTask(null)
    setDayTaskRefresh(n => n + 1)
  }

  // Closing the planner restarts the daemon's plan-nudge hold-back clock
  // (fire-and-forget; only meaningful on a day the auto-open fired — the
  // command's marker guard handles that), so the "Plan your day" reminder
  // lands an hour after the DISMISSAL, not the auto-open.
  function closePlan() {
    invoke('plan_dismissed').catch(() => {})
    setActiveModal(null)
  }

  // Marks the running app version "seen" so the once-per-version auto-open
  // (poll::whats_new_auto_open) doesn't fire again — whether this close came
  // from the auto-open or a manual nav-pill open, viewing it counts as seen.
  function closeWhatsNew() {
    invoke('mark_whats_new_seen_cmd').catch(() => {})
    setActiveModal(null)
  }

  // Opens the same swipeable Review dialog the pill/nav use, scoped to just
  // one ticket, instead of the right-side Hour-detail panel. Two callers:
  // a still-drafted card clicked directly on the timeline (TimelineColumn —
  // drafts never show in the right panel at all), and the right panel's own
  // "Edit" action on an approved/posted card (RightPanel/HourDetailPanel/
  // TimelineCard's DetailBody) — editing any state routes through this one
  // dialog rather than a separate inline editor.
  function openReview(cardKey: string) {
    setReviewFocusKey(cardKey)
    setActiveModal('review')
  }

  return (
    <div className="relative h-[100svh] overflow-hidden flex flex-col" style={{ background: 'var(--win-bg)' }}>
      <HealthBanner />

      <Toolbar
        day={day}
        isToday={isToday}
        onShiftDay={shift}
        isSolo={isSolo}
        connectedProviderName={connectedProviderName}
        connectedProviderIds={connectedProviderIds}
        onOpenSettings={(section) => { setSettingsSection(section); setActiveModal('settings') }}
        onOpenReport={() => setActiveModal('report')}
        showLlmLab={channel === 'dev'}
        onOpenLlmLab={() => setActiveModal('llmlab')}
        onOpenWhatsNew={() => setActiveModal('whats-new')}
        onOpenSummary={() => setActiveModal('summary')}
      />

      <div className="flex flex-1 min-h-0">
        <div className="relative flex-1 min-w-0 min-h-0 flex flex-col">
          <DayTaskColumn day={day} isToday={isToday}
            selectedId={selectedDayTask?.id ?? null} onSelect={selectDayTask}
            refreshToken={dayTaskRefresh}
            hourStatus={data.hourStatus} capturing={data.capturing} isSolo={isSolo}
            gaps={data.today?.gaps} />

          {!isSolo && (
            <FloatingDraftsPill count={pendingCount}
              onClick={() => { setReviewFocusKey(null); setActiveModal('review') }} />
          )}
        </div>
        <div className="shrink-0 border-l min-h-0" style={{ width: 388, borderColor: 'var(--t-hair)', background: 'var(--t-panel)' }}>
          <RightPanel
            data={data}
            selectedHour={selectedHour}
            selectedCardKey={selectedCardKey}
            dayTaskDetail={selectedDayTask}
            onCloseDayTask={() => setSelectedDayTask(null)}
            onDayTaskCorrected={onDayTaskCorrected}
            onSelectHour={selectHour}
            onOpen={setActiveModal}
            onOpenTask={(key, title, editable) => setOpenTask({ key, title, editable: editable ?? true })}
            onEditWorklog={openReview}
            onOpenSettings={(section) => { setSettingsSection(section); setActiveModal('settings') }}
          />
        </div>
      </div>

      {activeModal === 'review' && (
        <ReviewModal items={items} actions={data.actions} focusKey={reviewFocusKey}
          onClose={() => { setActiveModal(null); setReviewFocusKey(null) }} />
      )}
      {/* Board Cleanup — temporarily disabled (not deleted); re-enable by
          uncommenting this alongside OverviewPanel.tsx's CTA.
      {activeModal === 'cleanup' && (
        <CleanupModal onClose={() => { setActiveModal(null); data.refetchTasks() }} />
      )}
      */}
      {activeModal === 'settings' && (
        <SettingsModal
          // The lock is one-shot: it belongs to the visit that set it, so
          // clearing it on close stops the next ordinary Settings open (from the
          // toolbar) inheriting a locked ×.
          lock={settingsLock}
          onClose={() => setActiveModal(null)}
          // The connect flow finished. Hand the user straight back to the planner they
          // were pulled out of, with the note they typed and the draft they already
          // asked for - rather than dropping them on the timeline to work out for
          // themselves that they now have to start over.
          onLockSatisfied={() => {
            armResume()
            setActiveModal('plan')
          }}
          initialSection={settingsSection}
          // Close Settings before restarting: the walkthrough opens this very
          // modal in two of its beats, so replaying from inside it would have
          // it opening a modal that is already open.
          onReplayTour={() => { setActiveModal(null); tutorial.replay() }} />
      )}
      {activeModal === 'report' && <ReportModal onClose={() => setActiveModal(null)} />}
      {activeModal === 'llmlab' && channel === 'dev' && (
        <LlmLabScreen onClose={() => setActiveModal(null)} />
      )}
      {activeModal === 'whats-new' && <WhatsNewModal onClose={closeWhatsNew} />}
      {/* The summary owns the whole surface (one screen) and navigates days
          itself, reusing the shell's own day state so closing it leaves you on
          whatever day you read last. */}
      {activeModal === 'summary' && (
        <DaySummaryOverlay
          day={day}
          isToday={isToday}
          onShiftDay={shift}
          onClose={() => setActiveModal(null)}
          onOpenSettings={(section) => { setSettingsSection(section); setActiveModal('settings') }}
          onOpenTask={(key, title) => setOpenTask({ key, title, editable: true })}
        />
      )}
      {activeModal === 'plan' && <PlanModal onClose={closePlan} />}
      {activeModal === 'tasks' && (
        <TasksModal onClose={() => setActiveModal(null)} onOpenTask={(key, title) => setOpenTask({ key, title, editable: true })} />
      )}
      {openTask && (
        <TaskDetailDialog taskKey={openTask.key} fallbackTitle={openTask.title} day={day}
          editableTask={openTask.editable} onClose={() => setOpenTask(null)} />
      )}
      {/* Deferred, never dropped, while any other modal/dialog has the user's
          attention — it retries on the next render once the app is idle again. */}
      {showWorklogPrompt && !activeModal && !openTask && !tutorial.running && (
        <WorklogAutoGenerateDialog onDone={() => setShowWorklogPrompt(false)} />
      )}

      {/* The walkthrough, in two layers: an opaque surface that REPLACES the
          view with an example day (so the user's real work is never narrated
          over), and the narration overlay above everything including modals.
          Both are null when it is not running. */}
      {tutorial.screen}
      {tutorial.overlay}
    </div>
  )
}
