//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
//
// The entire one-pager Meridian Timeline app. ui/app/page.tsx renders this
// directly (no DashboardShell/Sidebar/CommandBar). Owns the selected day, the
// selected hour (Overview ↔ Hour-detail), and which modal is open; calls
// useTimelineData ONCE at the top and threads it down. Applies the persisted
// theme on mount. Fluid app-like layout (h-[100svh], own inner scroll regions)
// — the mock's fake window chrome is intentionally dropped (Tauri provides it).

'use client'

import { useEffect, useState } from 'react'
import { invoke, load, subscribe } from '@/lib/bridge'
import type { RuntimeSettings } from '@/lib/settings'
import { applyTheme } from '@/lib/theme'
import HealthBanner from '@/components/HealthBanner'
import { AlertDialog } from '@/components/ConfirmDialog'
import { useTimelineData } from './useTimelineData'
import { dayString, shiftDay, isPending } from './types'
import { Toolbar } from './Toolbar'
import { DayTaskColumn } from './DayTaskColumn'
import type { DayTaskDetail } from './DayTaskDetailPanel'
import { RightPanel } from './RightPanel'
import { useTutorial } from '@/components/tutorial/useTutorial'
import { FloatingDraftsPill } from './FloatingDraftsPill'
import { ReviewModal } from './ReviewModal'
// Board Cleanup temporarily disabled (not deleted) — re-enable by uncommenting
// this import alongside the `'cleanup'` modal-render branch below and
// OverviewPanel.tsx's CTA.
// import { CleanupModal } from './CleanupModal'
import { SettingsModal } from './SettingsModal'
import { PlanModal } from './PlanModal'
import { armResume } from '@/components/plan/useTaskComposer'
import { TasksModal } from './TasksModal'
import { TaskDetailDialog } from './TaskDetailDialog'
import { ReportModal } from './ReportModal'
import { LlmLabScreen } from './llmlab/LlmLabScreen'
import { WhatsNewModal } from './WhatsNewModal'
import { WorklogAutoGenerateDialog } from './WorklogAutoGenerateDialog'
import { DaySummaryOverlay } from '@/components/summary/DaySummaryOverlay'
import type { AppInfo } from '@/lib/api-types'
import type { SettingsSection } from './settings/types'

export type ActiveModal =
  | 'review' | 'cleanup' | 'settings' | 'plan' | 'tasks' | 'report' | 'llmlab' | 'whats-new' | 'summary' | null

export default function MeridianTimelineShell() {
  const [day, setDay] = useState<string>(dayString(0))
  const [selectedHour, setSelectedHour] = useState<number | null>(null)
  // A day-task card clicked in the timeline column — its detail replaces "Today
  // at a glance" in the right panel (same swap the hour/approved-card detail
  // uses), so the timeline keeps the clicked card highlighted and the rest dulled.
  const [selectedDayTask, setSelectedDayTask] = useState<DayTaskDetail | null>(null)
  // Set only when a specific worklog card (not the hour row itself) was
  // clicked — narrows the Hour-detail panel to that one card instead of every
  // ticket in the hour, and suppresses the row-level highlight (the card
  // itself gets the "popped forward" treatment instead).
  const [selectedCardKey, setSelectedCardKey] = useState<string | null>(null)
  const [activeModal, setActiveModal] = useState<ActiveModal>(null)
  // Set when a still-drafted card was clicked directly (as opposed to the
  // floating pill / nav, which review the whole pending queue) — scopes the
  // Review dialog to just that one ticket instead of the full queue.
  const [reviewFocusKey, setReviewFocusKey] = useState<string | null>(null)
  // Which Settings tab to land on when the modal opens — set by callers that
  // deep-link (e.g. the nav pill's "Integrations" item); undefined defaults
  // to Settings' own DEFAULT_SETTINGS_SECTION.
  const [settingsSection, setSettingsSection] = useState<SettingsSection | undefined>(undefined)
  // Set only when Settings was opened to finish a required step, so it can drop its
  // incidental dismissals. See ModalShell's `lock`.
  //
  // TWO STRENGTHS, and the difference is whether a way out exists elsewhere. Inside the
  // walkthrough this is `'required'`: connecting an engine is not optional there, and the
  // tour's own Skip sits above the modal at z-9000 as the escape hatch. Outside it, the
  // same "Draft with AI with no provider" press gets `'soft'` - no Escape or backdrop, but
  // a plainly labelled exit - because there IS no overlay to skip with, and a modal with
  // no way out and no walkthrough around it is simply a trapped app.
  const [settingsLock, setSettingsLock] = useState<'soft' | 'required' | undefined>(undefined)
  // The ticket detail dialog is a separate, stackable layer (not part of
  // ActiveModal) — it can open on top of the Tasks/Plan modals or straight
  // from the timeline/Overview panel.
  // `editable` is false when opened from a past day's Today's-focus checklist —
  // that day's plan is a record of what was focused on, not something to rewrite.
  const [openTask, setOpenTask] = useState<{ key: string; title?: string; editable: boolean } | null>(null)

  // Build channel, for dev-only surfaces (the LLM Lab). 'dev' only under
  // `tauri dev`/`cargo run` (cfg!(debug_assertions) via get_app_info) - staging
  // and prod builds never see the Lab button or modal, and its backing commands
  // are additionally refused there (commands/llm_lab.rs).
  const [channel, setChannel] = useState<string | null>(null)
  // One-time "let Meridian auto-generate worklogs" nudge — shown the first time
  // the Timeline loads with `worklog_auto_generate_prompted` still false. Covers
  // both a brand-new install (right after finishing setup, when the app first
  // launches into the Timeline) and a pre-existing one upgrading into this
  // feature (the flag defaults to false via `#[serde(default)]`, so it just
  // pops up next time they open the app) — one trigger point instead of a
  // wizard step plus a separate daemon-side re-prompt. Gated on having a
  // tracker connected — there's nothing to draft against otherwise, so asking
  // would just be confusing.
  const [showWorklogPrompt, setShowWorklogPrompt] = useState(false)
  const [worklogPrompted, setWorklogPrompted] = useState<boolean | null>(null)
  // The same dialog, raised by the walkthrough's closing beats instead. See the
  // render site for why it is separate state rather than the flag above.
  const [tourWorklogSchedule, setTourWorklogSchedule] = useState(false)

  const data = useTimelineData(day)
  const { items, isSolo, connectedProviderName, connectedProviderIds, isToday, integrations } = data
  const pendingCount = items.filter(isPending).length

  // Apply the persisted theme on mount (before any round-trip resolves elsewhere).
  useEffect(() => {
    load<RuntimeSettings>('/api/settings', 'get_settings')
      .then(s => {
        applyTheme(s.theme)
        setWorklogPrompted(s.worklog_auto_generate_prompted)
      })
      .catch(() => {})
    load<AppInfo>('/api/version', 'get_app_info')
      .then(info => setChannel(info.channel))
      .catch(() => {})
  }, [])

  // Arm the worklog auto-generate nudge as soon as we know it has never been
  // answered — fires right away (subject to the "no other modal open" render gate
  // below), not on a delay.
  //
  // NOT gated on a tracker any more. It used to also require `hasTracker`, which
  // meant a solo user was never offered the feature at all — and Settings → Worklogs
  // showed them a dead-end card instead, so there was no second way to find it
  // either. Drafting doesn't need a tracker: a personal day-task is drafted exactly
  // like a real ticket and the draft lands on that task's own row. Only POSTING to a
  // real ticket needs one. See `src/pm_worklog/auto_generate.rs`, which carried the
  // same wrong gate at the backend end.
  useEffect(() => {
    if (worklogPrompted !== false) return
    setShowWorklogPrompt(true)
  }, [worklogPrompted])

  // Retire the shell's own trigger the instant the TOUR arms its copy of the
  // ask — not only once that copy is answered. Answering (Turn on / X /
  // backdrop) already clears both flags via the tour dialog's own `onDone`
  // (see the render site below), but a SKIP while that dialog is still up
  // unmounts it through `finish()` resetting `tourWorklogSchedule` directly,
  // never reaching `onDone`. Without this, `showWorklogPrompt` stayed latched
  // true from the initial settings load, and the instant `tutorial.running`
  // flipped false the shell popped the identical dialog right back up, seconds
  // after the tour's own copy had just closed. The tour has already put the
  // same question in front of the user once either way, so there is nothing
  // left for the shell's own trigger to do this session — an unanswered skip
  // still re-arms it cleanly next launch, since `worklog_auto_generate_prompted`
  // stays false in the DB.
  useEffect(() => {
    if (tourWorklogSchedule) setShowWorklogPrompt(false)
  }, [tourWorklogSchedule])

  // NoticeBar lives at the root layout, outside this tree, so its pm.* CTA
  // reaches this shell through a window event rather than props.
  //
  // The event used to be `meridian:open-tasks` (a "Fix in Tasks →" button).
  // That button now says "Reconnect →" and opens Settings → Integrations,
  // which is where the same notice's own `remedy` text and its toast's
  // click-through both send the user. The old listener was removed with its
  // last dispatcher — a listener kept alive by a comment asserting it is live
  // is the same drift this change is cleaning up.
  useEffect(() => {
    const openSettings = (e: Event) => {
      const section = (e as CustomEvent<SettingsSection>).detail
      setSettingsSection(section)
      setActiveModal('settings')
    }
    window.addEventListener('meridian:open-settings', openSettings)
    return () => window.removeEventListener('meridian:open-settings', openSettings)
  }, [])


  // THE LOCK BELONGS TO THE VISIT THAT SET IT. Clearing it in SettingsModal's `onClose` was
  // not enough: the walkthrough's Skip closes the modal by setting `activeModal` directly
  // (useTutorial's `finish`), which never runs that handler - so the flag survived, and the
  // NEXT ordinary Settings open, from the toolbar, came up locked with its sidebar blurred
  // for no reason the user could see. Tying it to the modal actually being open makes it
  // correct regardless of who closed it, or how.
  useEffect(() => {
    if (activeModal !== 'settings') setSettingsLock(undefined)
  }, [activeModal])

  // Tray-side openers (the daily plan auto-open, notification click-throughs)
  // steer this window to a specific view. subscribe()'s prime is the pull half
  // (`take_pending_deep_link` — a fresh window misses any event emitted before
  // its listener exists, so the tray parks the target in managed state), and
  // its listener is the push half (`dashboard-navigate`, for a window that is
  // already open and won't remount). Targets are the former route paths the
  // notification producers still use as `deep_link`s.
  //
  // EVERY value in `meridian_core::notifications::deep_links::ALL` must have an
  // arm here, plus the retired spellings in `LEGACY` (rows already sitting in
  // users' outboxes still carry those, and a producer change never rewrites
  // them). `ui/__tests__/deep-links.test.ts` reads those Rust constants and
  // fails the build if one is unhandled.
  //
  // This used to be three arms with no `else`, while producers emitted seven.
  // The missing four just fell through — so the [View] button on every fault
  // toast opened the default view, and `/tasks?integrations=1` went on being
  // emitted for months after that route was deleted. Nothing failed, because a
  // link that resolves to nothing looks exactly like one that works. Hence the
  // `else`: an unrecognised target is now loud, and still lands somewhere sane.
  useEffect(() => {
    const navigate = (target: string | null) => {
      if (target === null) return
      // `undefined` means "whatever Settings defaults to" — see the
      // settingsSection state declaration.
      const openSettings = (section?: SettingsSection) => {
        setSettingsSection(section)
        setActiveModal('settings')
      }
      switch (target) {
        case '/plan':
          setActiveModal('plan')
          break
        case '/worklogs':
          setReviewFocusKey(null)
          setActiveModal('review')
          break
        case '/whats-new':
          setActiveModal('whats-new')
          break
        case '/today':
          // The dashboard itself — close whatever is covering it.
          setActiveModal(null)
          break
        case '/summary':
          // `DaySummaryOverlay` reads the shell's own `day`, so the day is reset
          // here rather than left as-is. The push half of this listener targets a
          // dashboard that is ALREADY open, where the user may have shifted back
          // to an earlier day — opening the summary on that day would show them a
          // different day's review than the one the toast was about. The only
          // producer (`day_summary.ready`) is scoped to the current local day and
          // its row expires at local midnight, so today is always what it meant.
          setDay(dayString(0))
          setActiveModal('summary')
          break
        case '/settings':
          openSettings()
          break
        // Both spellings mean "reconnect a tracker". `/tasks?integrations=1`
        // is the pre-fold route every pm.* sync fault used to emit.
        case '/settings/integrations':
        case '/tasks?integrations=1':
          openSettings('integrations')
          break
        // There is no in-app log viewer. What a user can actually do about a
        // fault is quote their Support ID and export diagnostics, both of which
        // live in Account. `/health` is an older spelling of the same intent.
        case '/logs':
        case '/health':
          openSettings('account')
          break
        default:
          console.warn(`[deep-link] unhandled target ${target} - opening the dashboard`)
          setActiveModal(null)
      }
    }
    return subscribe<string | null>('/deep-link', 'take_pending_deep_link', 'dashboard-navigate', navigate)
  }, [])

  // Changing day resets the selected hour (its detail no longer applies).
  function shift(delta: number) {
    setSelectedHour(null)
    setSelectedCardKey(null)
    setSelectedDayTask(null)
    setDay(d => shiftDay(d, delta))
  }

  // Row-level selection (Quiet/solo rows, or blank space in a row) — shows
  // every ticket in the hour and clears any single-card selection.
  function selectHour(hour: number | null) {
    setSelectedHour(hour)
    setSelectedCardKey(null)
    // An hour's detail and a day-task's detail both own the right panel; the
    // latest click wins.
    if (hour !== null) setSelectedDayTask(null)
  }

  // A day-task claims the right panel; clear any hour detail so they don't fight
  // over it.
  function selectDayTask(detail: DayTaskDetail | null) {
    setSelectedDayTask(detail)
    if (detail) { setSelectedHour(null); setSelectedCardKey(null) }
  }

  // First-run walkthrough. Deliberately a THIN seam: it owns its own full
  // surface (`tutorial.screen`, an opaque layer over this whole view) and its
  // own example data, so nothing in the real timeline or right panel knows it
  // exists. All this shell gives it is the ability to open real modals — the
  // planner, Settings — which are the only places the walkthrough touches the
  // actual product. See components/tutorial/.
  const tutorial = useTutorial({
    setActiveModal,
    setSettingsSection,
    // The tour opens two REQUIRED Settings steps of its own (connect a tracker,
    // connect an AI). It sets the lock itself rather than this shell inferring
    // one, because only the script knows which of its opens are asks it intends
    // to hold the user on and which are just showing them where something lives.
    setSettingsLock,
    setShowWorklogSchedule: setTourWorklogSchedule,
    ready: !data.loading,
  })

  // "Draft with AI" pressed with no provider installed. The composer raises this
  // rather than taking a callback, because it is rendered two modals deep
  // (PlanModal → PlanView → TaskComposer) and threading an opener through both
  // would put a Settings concern in two components that have nothing to do with
  // Settings. Same window-event pattern as `meridian:open-settings` above.
  useEffect(() => {
    const connectAi = () => {
      setSettingsSection('intelligence')
      // Just the FACT that they were sent here. SettingsModal owns what that means -
      // it makes the step required, labels the corner, and releases itself once a
      // provider is actually written. An exit label chosen here would be a promise
      // this component is in no position to keep.
      setSettingsLock(tutorial.running ? 'required' : 'soft')
      setActiveModal('settings')
    }
    window.addEventListener('meridian:connect-ai', connectAi)
    return () => window.removeEventListener('meridian:connect-ai', connectAi)
  }, [tutorial.running])

  // Bumped after a day-task is dismissed/merged so DayTaskColumn (which owns its
  // own fetch) reloads; the corrected task also leaves the detail panel.
  const [dayTaskRefresh, setDayTaskRefresh] = useState(0)
  function onDayTaskCorrected() {
    setSelectedDayTask(null)
    setDayTaskRefresh(n => n + 1)
  }

  // Closing the planner restarts the daemon's plan-nudge hold-back clock
  // (fire-and-forget; only meaningful on a day the auto-open fired — the
  // command's marker guard handles that), so the "Plan your day" reminder
  // lands an hour after the DISMISSAL, not the auto-open.
  function closePlan() {
    invoke('plan_dismissed').catch(() => {})
    setActiveModal(null)
  }

  // Marks the running app version "seen" so the once-per-version auto-open
  // (poll::whats_new_auto_open) doesn't fire again — whether this close came
  // from the auto-open or a manual nav-pill open, viewing it counts as seen.
  function closeWhatsNew() {
    invoke('mark_whats_new_seen_cmd').catch(() => {})
    setActiveModal(null)
  }

  // Opens the same swipeable Review dialog the pill/nav use, scoped to just
  // one ticket, instead of the right-side Hour-detail panel. Two callers:
  // a still-drafted card clicked directly on the timeline (TimelineColumn —
  // drafts never show in the right panel at all), and the right panel's own
  // "Edit" action on an approved/posted card (RightPanel/HourDetailPanel/
  // TimelineCard's DetailBody) — editing any state routes through this one
  // dialog rather than a separate inline editor.
  function openReview(cardKey: string) {
    setReviewFocusKey(cardKey)
    setActiveModal('review')
  }

  return (
    <div className="relative h-[100svh] overflow-hidden flex flex-col" style={{ background: 'var(--win-bg)' }}>
      <HealthBanner />

      <Toolbar
        day={day}
        isToday={isToday}
        onShiftDay={shift}
        isSolo={isSolo}
        connectedProviderName={connectedProviderName}
        connectedProviderIds={connectedProviderIds}
        onOpenSettings={(section) => { setSettingsSection(section); setActiveModal('settings') }}
        onOpenReport={() => setActiveModal('report')}
        showLlmLab={channel === 'dev'}
        onOpenLlmLab={() => setActiveModal('llmlab')}
        onOpenWhatsNew={() => setActiveModal('whats-new')}
        onOpenSummary={() => setActiveModal('summary')}
      />

      <div className="flex flex-1 min-h-0">
        <div className="relative flex-1 min-w-0 min-h-0 flex flex-col">
          <DayTaskColumn day={day} isToday={isToday}
            selectedId={selectedDayTask?.id ?? null} onSelect={selectDayTask}
            refreshToken={dayTaskRefresh}
            hourStatus={data.hourStatus} capturing={data.capturing} isSolo={isSolo}
            gaps={data.today?.gaps} />

          {!isSolo && (
            <FloatingDraftsPill count={pendingCount}
              onClick={() => { setReviewFocusKey(null); setActiveModal('review') }} />
          )}
        </div>
        <div className="shrink-0 border-l min-h-0" style={{ width: 388, borderColor: 'var(--t-hair)', background: 'var(--t-panel)' }}>
          <RightPanel
            data={data}
            selectedHour={selectedHour}
            selectedCardKey={selectedCardKey}
            dayTaskDetail={selectedDayTask}
            onCloseDayTask={() => setSelectedDayTask(null)}
            onDayTaskCorrected={onDayTaskCorrected}
            onSelectHour={selectHour}
            onOpen={setActiveModal}
            onOpenTask={(key, title, editable) => setOpenTask({ key, title, editable: editable ?? true })}
            onEditWorklog={openReview}
            onOpenSettings={(section) => { setSettingsSection(section); setActiveModal('settings') }}
          />
        </div>
      </div>

      {activeModal === 'review' && (
        <ReviewModal items={items} actions={data.actions} focusKey={reviewFocusKey}
          onClose={() => { setActiveModal(null); setReviewFocusKey(null) }} />
      )}
      {/* Board Cleanup — temporarily disabled (not deleted); re-enable by
          uncommenting this alongside OverviewPanel.tsx's CTA.
      {activeModal === 'cleanup' && (
        <CleanupModal onClose={() => { setActiveModal(null); data.refetchTasks() }} />
      )}
      */}
      {activeModal === 'settings' && (
        <SettingsModal
          // The lock is one-shot: it belongs to the visit that set it, so
          // clearing it on close stops the next ordinary Settings open (from the
          // toolbar) inheriting a locked ×.
          lock={settingsLock}
          onClose={() => setActiveModal(null)}
          // The connect flow finished. Hand the user straight back to the planner they
          // were pulled out of, with the note they typed and the draft they already
          // asked for - rather than dropping them on the timeline to work out for
          // themselves that they now have to start over.
          // RESUME ONLY THE AI DETOUR. `armResume` means "the user was mid-compose
          // when we pulled them out - keep their note and re-run the draft they
          // already asked for", which is true of exactly one lock: the AI one,
          // reached by pressing Draft with no provider connected.
          //
          // The TRACKER lock is reached from the walkthrough's team-or-solo
          // question, before the composer has been opened at all. Arming resume
          // there suppressed the composer's `resetComposer()` on mount, so it came
          // back holding whatever stale title and description were last in the
          // module store - a task the user had not written, appearing in a box they
          // were about to be asked to write in.
          onLockSatisfied={() => {
            if (settingsSection !== 'integrations') armResume()
            setActiveModal('plan')
          }}
          initialSection={settingsSection}
          // Close Settings before restarting: the walkthrough opens this very
          // modal in two of its beats, so replaying from inside it would have
          // it opening a modal that is already open.
          onReplayTour={() => { setActiveModal(null); tutorial.replay() }}
          onReplayTourFromDay={tutorial.replayFromDay
            ? () => { setActiveModal(null); tutorial.replayFromDay?.() }
            : null} />
      )}
      {activeModal === 'report' && <ReportModal onClose={() => setActiveModal(null)} />}
      {activeModal === 'llmlab' && channel === 'dev' && (
        <LlmLabScreen onClose={() => setActiveModal(null)} />
      )}
      {activeModal === 'whats-new' && <WhatsNewModal onClose={closeWhatsNew} />}
      {/* The summary owns the whole surface (one screen) and navigates days
          itself, reusing the shell's own day state so closing it leaves you on
          whatever day you read last. */}
      {activeModal === 'summary' && (
        <DaySummaryOverlay
          day={day}
          isToday={isToday}
          onShiftDay={shift}
          onClose={() => setActiveModal(null)}
          onOpenSettings={(section) => { setSettingsSection(section); setActiveModal('settings') }}
          onOpenTask={(key, title) => setOpenTask({ key, title, editable: true })}
        />
      )}
      {activeModal === 'plan' && <PlanModal onClose={closePlan} />}
      {activeModal === 'tasks' && (
        <TasksModal onClose={() => setActiveModal(null)} onOpenTask={(key, title) => setOpenTask({ key, title, editable: true })} />
      )}
      {openTask && (
        <TaskDetailDialog taskKey={openTask.key} fallbackTitle={openTask.title} day={day}
          editableTask={openTask.editable} onClose={() => setOpenTask(null)} />
      )}
      {/* Deferred, never dropped, while any other modal/dialog has the user's
          attention — it retries on the next render once the app is idle again. */}
      {showWorklogPrompt && !activeModal && !openTask && !tutorial.running && (
        <WorklogAutoGenerateDialog onDone={() => setShowWorklogPrompt(false)} />
      )}
      {/* THE SAME DIALOG, PLACED BY THE TOUR. The gate above deliberately holds it
          back for the whole walkthrough - it would otherwise fire on the first
          Timeline load, i.e. straight over the title sequence. But the ask itself
          belongs in the tour more than anywhere else: it asks what time to wrap up
          a day, which is meaningless until the user has watched a day get wrapped
          up, and by the closing beats they have. Separate state rather than
          reusing the flag above, so "the shell decided to ask" and "the script
          asked" cannot be confused for one another - and so the tour's copy of it
          renders regardless of whether the shell's own trigger conditions (a
          tracker connected, never prompted) happen to hold. */}
      {/* ANSWERED IS ANSWERED, whichever copy asked. Both write the same
          `worklog_auto_generate_prompted`, but `showWorklogPrompt` was latched
          true back when settings loaded and nothing here cleared it - so a user
          who set their time at the tour's closing beat had the identical dialog
          reappear the moment the tour ended, asking again for something they had
          just answered. (`worklogPrompted` is read once on mount, so the
          re-render cannot notice the write either.)

          The reverse case is the one that must keep working and does: SKIP the
          tour before this beat and the ask was never answered, so the gate above
          raises it as soon as `tutorial.running` goes false. That is the
          walkthrough's only genuinely one-shot setup step, and skipping must not
          cost it. */}
      {tourWorklogSchedule && (
        <WorklogAutoGenerateDialog onDone={() => {
          setTourWorklogSchedule(false)
          setShowWorklogPrompt(false)
        }} />
      )}

      {/* The walkthrough, in two layers: an opaque surface that REPLACES the
          view with an example day (so the user's real work is never narrated
          over), and the narration overlay above everything including modals.
          Both are null when it is not running. */}
      {tutorial.screen}
      {tutorial.overlay}

      {/* A failed worklog action (approve/reject/post/edit). Rendered last so it
          sits above whatever modal it was triggered from. This used to be an
          `alert()`, which is inert in the packaged tray — the failure was
          invisible and the row just snapped back with no explanation. */}
      {data.actionError && (
        <AlertDialog
          title="That did not go through"
          body={data.actionError}
          onDismiss={data.clearActionError}
        />
      )}
    </div>
  )
}
