//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
//
// One-time nudge, shown on the Timeline the first time it loads after
// `worklog_auto_generate_prompted` is still false (right after a new user
// finishes setup, or the next time an existing install upgrades into this
// feature — one flag, one trigger point, no wizard step and no daemon-side
// auto-open needed). Bespoke hero-card chrome rather than <ModalShell>'s
// title-bar treatment: this is an invitation, not a workspace, so it reads more
// like a considered note from the product than another panel to manage.
//
// Asks for exactly one thing: what time this should be READY - not "when does
// your day end", which was the old wording and asked the user to work out the
// link between their working hours and a feature they had not used yet.
// Once a day, at that time,
// Meridian scans and auto-DRAFTS (never posts) a worklog for anything you've
// spent more than 30 tracked minutes on that isn't already drafted — AND composes
// that day's summary over the result. The copy names both, because it used to
// name only the worklogs, and "Not now" was quietly switching off the summary
// screen as well. Deliberately minimal otherwise — no marketing voice.

'use client'

import { useState } from 'react'
import { mutate } from '@/lib/bridge'
import { TextInput } from '@/components/ui/TextInput'
import type { RuntimeSettings } from '@/lib/settings'

const PRESETS = [
  { time: '13:00', label: '1:00 PM' },
  { time: '18:00', label: '6:00 PM' },
  { time: '21:00', label: '9:00 PM' },
] as const

/** Whether a value from the custom-time input is a time we can actually save.
 *
 *  `<input type="time">` reports `''` for a partially typed or cleared value -
 *  the user is mid-keystroke, or has just wiped the field. Committing that would
 *  write an empty string to `worklog_auto_generate_time`, which is NOT null, so
 *  the feature reads as switched ON everywhere (here, in Settings, in the
 *  daemon's gate) while naming a time that can never come round. The selection
 *  the user made would silently not be the one saved.
 *
 *  Exported for its unit test - the repo has no React render harness. */
export function isSavableTime(hhmm: string): boolean {
  const m = /^(\d{2}):(\d{2})$/.exec(hhmm)
  if (!m) return false
  return Number(m[1]) <= 23 && Number(m[2]) <= 59
}

function timeLabel(hhmm: string): string {
  const preset = PRESETS.find((p) => p.time === hhmm)
  if (preset) return preset.label
  const [h, m] = hhmm.split(':').map(Number)
  const period = h >= 12 ? 'PM' : 'AM'
  const h12 = ((h + 11) % 12) + 1
  return `${h12}:${String(m).padStart(2, '0')} ${period}`
}

export function WorklogAutoGenerateDialog({ onDone }: { onDone: () => void }) {
  const [time, setTime] = useState<string>('18:00')
  const [busy, setBusy] = useState<'on' | 'later' | null>(null)
  // WHAT IS ON SCREEN IS WHAT GETS SAVED. `time` is the single source for both
  // the confirmation line and the commit, so the two cannot disagree - and while
  // it is not a real time there is nothing to turn on, rather than an empty
  // string written as though it were a schedule.
  const valid = isSavableTime(time)

  const commit = (fields: Partial<RuntimeSettings>, which: 'on' | 'later') => {
    setBusy(which)
    mutate<RuntimeSettings>('/api/settings', 'update_settings', fields, 'PUT')
      .catch((e) => console.error('Failed to save worklog auto-generate choice', e))
      .finally(onDone)
  }

  return (
    <div className="absolute inset-0 z-50 flex items-center justify-center p-6 rise"
      style={{ background: 'rgba(20,16,40,0.5)', backdropFilter: 'blur(4px)' }}
      onClick={() => commit({ worklog_auto_generate_prompted: true }, 'later')}>
      <div className="mer-pop w-full flex flex-col bg-panel"
        style={{
          maxWidth: 440, borderRadius: 22, border: '1px solid var(--t-card-border)',
          boxShadow: 'var(--mt-modal-shadow)', overflow: 'hidden',
        }}
        onClick={(e) => e.stopPropagation()}>
        <div style={{ padding: '30px 30px 26px' }}>
          <div className="flex items-start justify-between">
            <span className="flex items-center justify-center shrink-0" style={{
              width: 44, height: 44, borderRadius: 14,
              background: 'color-mix(in srgb, var(--color-state-proposal) 14%, transparent)',
              color: 'var(--color-state-proposal)',
            }}>
              <SparkIcon />
            </span>
            <button type="button" aria-label="Close"
              onClick={() => commit({ worklog_auto_generate_prompted: true }, 'later')}
              className="inline-flex items-center justify-center rounded-full bg-wrap shrink-0"
              style={{ width: 28, height: 28, color: 'var(--t-muted)' }}>
              <span className="text-[15px] leading-none">×</span>
            </button>
          </div>

          {/* NAMES BOTH THINGS THIS TIME SETS OFF. It used to be labelled and
              titled for worklogs alone, which describes half of what happens:
              the same pass also composes the daily summary - the screen the
              walkthrough spends its whole back half inside - and someone who
              answered "Not now" to a dialog about worklogs had, without being
              told, also switched off the summary they had just been shown. */}
          <p className="mt-label mt-4" style={{ color: 'var(--color-state-proposal)' }}>
            Daily summary and worklogs
          </p>
          {/* ASKS FOR THE DELIVERY TIME, NOT THE END OF THE DAY. It used to read
              "When does your day end?" - a question about the USER, answered with
              a shrug, and one whose connection to the thing being switched on the
              reader has to make for themselves. What is actually being set is
              when this arrives, so that is what it asks. */}
          <h1 className="mt-2" style={{
            font: '800 22px var(--font-sans)', letterSpacing: '-0.02em', lineHeight: 1.2,
            color: 'var(--t-title)',
          }}>
            When do you want these ready?
          </h1>
          <p className="mt-body-sm mt-2.5" style={{ color: 'var(--t-muted)', lineHeight: 1.55 }}>
            Meridian writes them for you by that time and tells you they are waiting. You approve
            before anything is posted.
          </p>

          <div data-tour="worklog-schedule-times"
            className="flex items-center gap-1.5 mt-5 p-1 rounded-xl bg-wrap w-fit flex-wrap">
            {PRESETS.map((p) => (
              <button key={p.time} type="button" onClick={() => setTime(p.time)}
                className="rounded-lg transition-colors"
                style={{
                  padding: '7px 14px', fontSize: 12.5, fontWeight: 600,
                  color: time === p.time ? '#fff' : 'var(--t-muted)',
                  background: time === p.time ? 'var(--color-state-proposal)' : 'transparent',
                  border: 'none', cursor: 'pointer',
                }}>
                {p.label}
              </button>
            ))}
            <TextInput type="time" width={100} value={time} onChange={setTime} />
          </div>
          <p className="text-[11px] mt-2" style={{ color: valid ? 'var(--t-faint)' : 'var(--color-state-pending)' }}>
            {valid
              ? `Summary and drafts ready by ${timeLabel(time)}.`
              : 'Pick a time to turn this on.'}
          </p>
        </div>

        <div className="flex flex-col gap-2" style={{ padding: '0 30px 26px' }}>
          <button type="button" disabled={busy !== null || !valid} data-tour="worklog-schedule-on"
            onClick={() => commit({ worklog_auto_generate_time: time, worklog_auto_generate_prompted: true }, 'on')}
            className="w-full rounded-xl font-semibold"
            style={{
              padding: '11px 0', fontSize: 13.5, color: '#fff',
              background: 'var(--color-state-proposal)', border: 'none',
              opacity: !valid || (busy && busy !== 'on') ? 0.6 : 1,
              cursor: busy || !valid ? 'default' : 'pointer',
            }}>
            {busy === 'on' ? 'Turning on…' : 'Turn on'}
          </button>
          {/* NO "Not now" BUTTON. Declining is already the × and the backdrop,
              both of which commit the same thing - so a third control offered
              nothing but a second way to do nothing, and gave a one-question
              dialog the shape of a decision with two weighted sides. The line
              below says the choice is reversible, which is the reassurance the
              button was standing in for. */}
          <p className="text-center" style={{ fontSize: 10.5, color: 'var(--t-faint)' }}>
            Change anytime in Settings → Worklogs.
          </p>
        </div>
      </div>
    </div>
  )
}

function SparkIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
      <path d="M12 2.5 14 9l6.5 2-6.5 2-2 6.5-2-6.5L3.5 11 10 9l2-6.5Z"
        fill="currentColor" />
    </svg>
  )
}
