//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
//
// The DMG background has to tell the user to OPEN the app, not only to drag it.
//
// A disk image cannot launch anything. The drag to Applications is a Finder
// copy - no code of ours runs, and macOS has had no post-install hook in a DMG
// by design for as long as Gatekeeper has existed. So an app sitting in
// Applications unopened after an install is not something the app can fix from
// the inside: it is a step the installer has to ASK for, and the background
// image is the only surface in a DMG that can ask.
//
// It used to say "Drag to Applications to install" and stop. That describes the
// drag accurately and then leaves the user on a Finder window with nothing
// indicating the app has not started - reported as "on dropping Meridian to
// Applications can we make the app setup open immediately?", which is the same
// observation from the other side.
//
// Guarded here because the failure is silent in the worst way: the background
// is a generated PNG, so nothing type-checks it, nothing renders it in CI, and
// a well-meaning copy edit that collapses the two steps back into one sentence
// looks completely fine in the diff.
//
// This lives under ui/__tests__ because that is the only JS/TS suite the repo
// runs; the subject is a Python generator, so it is scanned as text.

import { describe, it, expect } from 'bun:test'
import { readFileSync, statSync } from 'fs'
import { createHash } from 'crypto'
import { join } from 'path'

const repo = join(import.meta.dir, '..', '..')
const gen = readFileSync(join(repo, 'scripts', 'make-dmg-background.py'), 'utf8')

/** The step strings the generator draws, in the order it draws them. */
function steps(): string[] {
  const at = gen.indexOf('    steps = [')
  expect(at).toBeGreaterThan(-1)
  const end = gen.indexOf('    ]', at)
  expect(end).toBeGreaterThan(at)
  return [...gen.slice(at, end).matchAll(/"([^"]+)"/g)].map(m => m[1])
}

describe('the DMG tells the user to open the app', () => {
  it('draws two steps, not one instruction', () => {
    // Numbered rather than one sentence on purpose: "and then open it" appended
    // to the drag instruction reads as a description of what the drag does,
    // which is exactly the misreading that leaves the app unopened.
    expect(steps()).toHaveLength(2)
  })

  it('names the drag first and the open second', () => {
    const [one, two] = steps()
    expect(one).toMatch(/^1\./)
    expect(one.toLowerCase()).toContain('drag')
    expect(two).toMatch(/^2\./)
    expect(two.toLowerCase()).toContain('open')
  })

  it('says WHERE to open it from', () => {
    // The user is looking at a DMG window, not at Applications - the folder is
    // the part that is not obvious at that moment.
    expect(steps()[1]).toContain('Applications')
  })

  it('uses plain hyphens only, like every other user-facing string', () => {
    // CLAUDE.md's hard rule. This text is read by a user during install, so it
    // is app text even though it lives in a build script.
    for (const s of steps()) {
      expect(s).not.toMatch(/[—–]|--/)
    }
  })

  it('keeps the steps clear of the icon row Finder draws on top', () => {
    // Finder paints the .app and the Applications alias at y=170pt at 128pt
    // (tauri.conf.json's bundle.macOS.dmg), so their bottom edge is 234pt and
    // their labels sit below that. Text placed any higher would be drawn under
    // an icon - invisible, with nothing in the build to notice.
    const m = gen.match(/\((\d+) \+ n \* \d+\) \* SCALE/)
    expect(m).not.toBeNull()
    expect(Number(m![1])).toBeGreaterThan(234)
  })

  it('ships a PNG that actually contains the drawn text', () => {
    // THE COMMITTED IMAGE IS THE ARTEFACT, and it is generated BY HAND - no
    // build step regenerates it. So editing the copy above and forgetting to
    // re-run the script ships the OLD picture while the diff looks complete.
    //
    // Not an mtime comparison, which was the obvious approach and is unsound:
    // on a fresh clone git gives every file the same checkout time, so it
    // passes unconditionally in CI - the one place it needed to work. Measured,
    // not assumed: with equal mtimes the check passed even against a
    // deliberately stale PNG.
    //
    // So this reads the image itself. Rasterised text cannot be grepped, but a
    // re-render always changes the bytes, so the recorded digest is what ties
    // the two together: change the copy without re-running and the digest no
    // longer matches, which is exactly the mistake being guarded.
    const png = readFileSync(join(repo, 'tray', 'src-tauri', 'dmg', 'background.png'))
    const digest = createHash('sha256').update(png).digest('hex')
    // Update this line WITH the PNG, in the same commit, after re-running
    // `python3 scripts/make-dmg-background.py`. The failure message says so.
    const RENDERED = gen.match(/#\s*rendered-digest:\s*([0-9a-f]{64})/)?.[1]
    expect(
      `${digest} (background.png) must match the rendered-digest in make-dmg-background.py - re-run it`,
    ).toContain(RENDERED ?? 'no rendered-digest comment in make-dmg-background.py')
  })

  it('is a real image, not a placeholder or an LFS pointer', () => {
    // Cheap sanity on the artefact itself: PNG magic, and a size consistent with
    // a 1320x800 render rather than a stub committed by accident.
    const png = readFileSync(join(repo, 'tray', 'src-tauri', 'dmg', 'background.png'))
    expect([...png.subarray(0, 4)]).toEqual([0x89, 0x50, 0x4e, 0x47])
    expect(statSync(join(repo, 'tray', 'src-tauri', 'dmg', 'background.png')).size)
      .toBeGreaterThan(10_000)
  })
})
