//ambient dev tool that watches what you do and updates your PM tickets automatically, boosting developer productivity
import { describe, it, expect } from 'bun:test'
import { readFileSync } from 'fs'
import {
  sampleTasks, sampleDayString, sampleOverview, samplePlanItems,
  FOCUS_TASK_ID, DRAFT_TASK_ID, OFFPLAN_TASK_ID,
} from '../components/tutorial/sampleDay'
import { fmtSetupElapsed, INTRO_LINES } from '../components/tutorial/script'
import { isSavableTime } from '../components/timeline/WorklogAutoGenerateDialog'
import { trayIsAtTheTop } from '../components/tutorial/TutorialTray'

// THE SCRIPT IS TWO FILES. `script.ts` holds part one (the user's own empty day:
// the plan, the tracker branch, the composer) and hands off to `scriptDay.ts` for
// part two (the example day: the replay, the summary, the worklog, the close-out).
// Every assertion below is about the tour as one narrative, and several of them
// check ORDER, so the two are concatenated in the order they actually run rather
// than read separately.
const SCRIPT_SRC =
  readFileSync(new URL('../components/tutorial/script.ts', import.meta.url), 'utf8')
  + readFileSync(new URL('../components/tutorial/scriptDay.ts', import.meta.url), 'utf8')

// The example day is fed to the REAL DayTaskColumn via its `tasks` prop, so a
// shape mismatch does not fail loudly — it renders a subtly broken timeline in
// front of a brand-new user, during the one run where the product is trying to
// establish that it can be trusted to describe their work accurately. These
// tests exist because that failure is silent.

describe('sample day shape', () => {
  const tasks = sampleTasks()

  it('derives minutes from its own segments', () => {
    // Hand-written minutes would drift from the segments they claim to
    // summarise; the Rust fold computes this deterministically and so must this.
    for (const t of tasks) {
      const summed = t.segments.reduce((a, s) => {
        const [sh, sm] = s.start.split(':').map(Number)
        const [eh, em] = s.end.split(':').map(Number)
        return a + (eh * 60 + em) - (sh * 60 + sm)
      }, 0)
      expect(t.minutes).toBe(summed)
    }
  })

  it('emits ascending, well-formed HH:MM segments', () => {
    for (const t of tasks) {
      let prev = -1
      for (const s of t.segments) {
        expect(s.start).toMatch(/^\d{2}:\d{2}$/)
        expect(s.end).toMatch(/^\d{2}:\d{2}$/)
        const [sh, sm] = s.start.split(':').map(Number)
        const [eh, em] = s.end.split(':').map(Number)
        const start = sh * 60 + sm
        const end = eh * 60 + em
        expect(end).toBeGreaterThan(start)
        expect(start).toBeGreaterThan(prev)
        prev = end
      }
    }
  })

  it('labels hours as YYYY-MM-DDTHH matching first_hour/last_hour', () => {
    const day = sampleDayString()
    for (const t of tasks) {
      expect(t.hours.length).toBeGreaterThan(0)
      for (const h of t.hours) expect(h.startsWith(`${day}T`)).toBe(true)
      const nums = t.hours.map((h) => Number(h.slice(-2)))
      expect(t.first_hour).toBe(Math.min(...nums))
      expect(t.last_hour).toBe(Math.max(...nums))
    }
  })

  it('dates the example in the past, never today', () => {
    // The example runs to 17:20. Dated "today", a mid-afternoon install would
    // show the user hours of work they can see they have not done yet.
    const today = new Date()
    const p = (n: number) => String(n).padStart(2, '0')
    const todayStr = `${today.getFullYear()}-${p(today.getMonth() + 1)}-${p(today.getDate())}`
    expect(sampleDayString()).not.toBe(todayStr)
    expect(sampleDayString() < todayStr).toBe(true)
  })

  it('keeps the cards the script targets by id', () => {
    // The script points and waits on these specific ids; renaming or
    // reordering the list without updating them would leave beats pointing at
    // nothing, which degrades to a silent 6s stall rather than an error.
    expect(tasks.find((t) => t.id === FOCUS_TASK_ID)).toBeDefined()
    expect(tasks.find((t) => t.id === DRAFT_TASK_ID)).toBeDefined()
  })

  it('gives the focus card two sittings and the draft card a ticket', () => {
    // These are not decorative: the focus beat's whole claim is "worked in two
    // sittings", and the draft beat's is "maps to a ticket".
    expect(tasks.find((t) => t.id === FOCUS_TASK_ID)!.segments.length).toBe(2)
    expect(tasks.find((t) => t.id === DRAFT_TASK_ID)!.linked_ticket).toBeTruthy()
  })

  it('includes work with no ticket at all', () => {
    // Load-bearing for expectation-setting: it teaches, with a card rather
    // than a sentence, that Meridian does not force everything onto a ticket.
    expect(tasks.some((t) => t.linked_ticket === null)).toBe(true)
  })
})

// The right panel sits beside the example timeline during the whole
// walkthrough, so its numbers are read against the cards. Anything that adds up
// differently reads as the product miscounting the very day it is using to
// prove it counts accurately.
describe('sample overview', () => {
  const tasks = sampleTasks()
  const ov = sampleOverview()

  it('counts Focus as wall-clock time, not the sum of task minutes', () => {
    // This is the one that was actually wrong: two example tasks run
    // concurrently (a talk playing while a test suite ran), so summing task
    // minutes reports 10h 25m for a day whose real footprint is 7h 5m. The
    // marketing demo unions the segments (`unionMinutes`); so must this.
    const summed = tasks.reduce((a, t) => a + t.minutes, 0) * 60
    expect(ov.engagedSeconds).toBe(425 * 60)
    expect(ov.engagedSeconds).toBeLessThan(summed)
  })

  it('keeps app time as its own figures, not derived from the tasks', () => {
    // Apps and tasks are different cuts of a day; these are the demo's own
    // `appMinutes`. Deriving them from the task list would invent a precision
    // neither the demo nor the real app has.
    const byApp = Object.fromEntries(ov.appSessions.map((s) => [s.app, s.dur / 60]))
    expect(byApp).toEqual({
      'Claude Code': 148, 'Google Chrome': 96, GitHub: 74, Slack: 62, 'System Settings': 12,
    })
    // Blank `cat` so these never leak into the category donut.
    for (const s of ov.appSessions) expect(s.cat).toBe('')
  })

  it('keeps category time as a per-task sum covering every card', () => {
    expect(ov.catSessions.length).toBe(tasks.length)
    const total = ov.catSessions.reduce((a, s) => a + s.dur, 0)
    expect(total).toBe(tasks.reduce((a, t) => a + t.minutes, 0) * 60)
    // Blank `app` so these never leak into Time by app.
    for (const s of ov.catSessions) expect(s.app).toBe('')
  })

  it('posts nothing, because the tracker ask has not happened yet', () => {
    // A "synced to Jira" pill on a card would show the end state before the
    // beat that asks the user to connect a tracker, making the ask look moot.
    expect(tasks.every((t) => !t.posted_provider)).toBe(true)
    expect(ov.greetingBody).not.toContain('logged')
    expect(ov.greetingBody).toContain('7h 5m')
  })

  it('counts every ticketed card as a waiting draft', () => {
    expect(ov.pendingCount).toBe(tasks.filter((t) => t.linked_ticket).length)
    expect(ov.pendingCount).toBeGreaterThan(0)
  })

  it('leaves one focus item unfinished', () => {
    // A plan that came out exactly as written is not what a real day looks
    // like, and the timeline has no card for the third item on purpose.
    expect(ov.focusItems.length).toBeGreaterThan(0)
    expect(ov.focusItems.some((t) => !t.is_terminal)).toBe(true)
    expect(ov.focusItems.some((t) => t.is_terminal)).toBe(true)
  })
})

// The walkthrough's two halves are a sequencing property of one async function,
// so nothing type-checks the order. Getting it wrong is silent and only visible
// by sitting through a two-minute run — hence a source-order guard.
describe('walkthrough structure', () => {
  const src = SCRIPT_SRC
  const at = (needle: string) => {
    const i = src.indexOf(needle)
    if (i < 0) throw new Error(`not found in script.ts: ${needle}`)
    return i
  }

  it('collects the plan and the tracker BEFORE showing the example day', () => {
    // Part one has to run on the user's own empty timeline. If the example is
    // switched on first, the real (blank) day they return to reads as broken —
    // which is the exact failure the example exists to prevent.
    expect(at('data-tour="plan-open"')).toBeLessThan(at('s.showExample(true)'))
    expect(at('s.ask(')).toBeLessThan(at('s.showExample(true)'))
  })

  it('hands the example day back before the closing line', () => {
    // Ending while the example is still on screen would leave invented tasks
    // sitting on the user's timeline after the overlay is gone.
    expect(at('s.showExample(false)')).toBeLessThan(src.lastIndexOf("s.say('')"))
  })

  it('dims the screen for the plan beat and nowhere else', () => {
    // `dim` blurs everything else AND swallows clicks outside the target, so a
    // beat that dims is a beat the user cannot walk away from. That is right
    // exactly once — the daily plan, which every later beat assumes exists.
    // Spreading it to beats the user could reasonably skip turns a walkthrough
    // into a hostage situation.
    const dims = [...src.matchAll(/s\.spotlight\(([^)]*\{[^)]*dim[^)]*\})\)/g)]
    expect(dims.length).toBe(1)
    expect(dims[0][1]).toContain('plan-open')
  })

  it('pairs every dim with a later clear', () => {
    // A dim left fenced around nothing blurs and locks the entire window. The
    // hook clears it whenever the spotlight clears, so the guard is just that
    // the beat does clear its spotlight afterwards.
    expect(at('s.spotlight(null)')).toBeGreaterThan(at('dim: true'))
  })

  it('branches the worklog stretch on a board that is CONNECTED, not on the answer', () => {
    // A solo user must not be told Meridian posts to a board they never
    // connected - the product would contradict it within the hour. But the flag
    // that used to decide it was carried down from a question in part one and
    // then rewritten by the connect flow's outcome, and any break in that chain
    // sent a user WITH a board to the one-line consolation instead of the
    // Generate/Approve/Posted stretch the whole tour exists to land. Silent, and
    // it looks like the tour simply skipping its best part.
    const draft = src.slice(at('── 5. The worklog, end to end'))
    expect(draft).toContain('if (board) {')
    expect(src).toContain('async function hasBoard(')
    expect(src).toContain("connectedTrackers(res).length > 0")
    // The answer survives as the fallback for the one case the read cannot
    // settle - it threw - where what the user told us beats guessing.
    expect(src).toContain("return usesTracker === 'tracker'")
  })

  it('keeps the title sequence, and nothing standing in front of the replay', () => {
    // `s.intro` stays: it runs before any product is on screen, and it is the beat
    // that says "this is a tour" before the tour takes the window.
    const body = src.slice(at('export async function runScript'))
    expect(body).toContain('s.intro(')

    // The REPLAY gets no preamble at all. There was a card here (`replayIntro`)
    // behind a "Show me" button, describing what was about to happen instead of
    // letting it happen - in front of a timeline that was blank at that moment,
    // so it explained nothing, over nothing. The replay is twelve seconds long
    // and narrates itself; anything in front of it is a step between the user and
    // the one thing this half exists to show.
    expect(src).not.toContain('replayIntro')
    // Nothing at all between flipping to the example day and the sweep starting.
    const between = src.slice(at('s.showExample(true)'), at('await s.replayDay(['))
    expect(between).not.toMatch(/\bawait s\./)
  })

  it('says what this is, and that it is short, without promising a number', () => {
    // The reassurance is load-bearing - a tour that takes over the whole window
    // needs to say it ends. The NUMBER is not: the tour now owns connecting a
    // tracker (an OAuth round-trip on someone else's site) and an AI CLI, so
    // most of its duration is spent outside this app. "About 2 minutes" was
    // visibly wrong for anyone connecting Jira, and a first-run screen that
    // breaks a promise in its second sentence costs more than the number bought.
    const intro = INTRO_LINES.join(' ')
    expect(intro).toMatch(/take you around/i)
    expect(intro).toMatch(/quick|short/i)
    expect(intro).not.toMatch(/\d+\s*minute/i)
  })

  it('keeps the title card to two short lines', () => {
    // Each word is revealed on its own step, so length is duration: the open is
    // a title card, and a third line (or a long one) turns it into a slideshow
    // in front of someone who has not seen the product yet.
    expect(INTRO_LINES.length).toBe(2)
    for (const l of INTRO_LINES) expect(l.split(/\s+/).length).toBeLessThanOrEqual(10)
  })

  it('goes from the title card straight to the plan, with nothing in between', () => {
    // No explain-the-product beat between them. A tour that opens with a
    // paragraph about what Meridian is spends the user's attention before
    // asking for anything, and every sentence in it means more once their own
    // tasks are on screen. What the product does gets SHOWN, later, on their
    // own plan.
    const between = src.slice(at('await s.intro('), at('dim: true'))
    expect(between).not.toMatch(/s\.next\(/)
  })

  it('uses plain hyphens in the intro, per the user-facing text rule', () => {
    for (const l of INTRO_LINES) expect(l).not.toMatch(/[—–]|--/)
  })

  it('advances narration on Next, not on a timer', () => {
    // A voiceover plays over these lines, so hardcoded millisecond guesses
    // cannot be synced to it — and a reader slower than the guess loses the
    // sentence. `pause` is allowed only for mechanical gaps (a modal's open
    // transition), which are all well under a second and a half. The title
    // sequence is the one exception, and it is timed inside TutorialIntro
    // precisely because it has nothing on screen for a reader to lose.
    const body = src.slice(at('export async function runScript'))
    expect(body).toContain('s.next(')
    for (const m of body.matchAll(/s\.pause\((\d+)\)/g)) {
      expect(Number(m[1])).toBeLessThanOrEqual(1500)
    }
  })

  // Most first runs have no AI provider connected, so pressing "Draft with AI"
  // produces a connect card instead of a draft. These pin the detour that
  // handles it — every one of them is invisible to a type checker.
  describe('the no-provider detour off the draft beat', () => {
    // Anchored on the branch body, not on the first `ai-connect` mention: that
    // mention is now the PROBE that runs before the draft ring (see the
    // already-asking test below), which sits outside the detour proper.
    const detour = () => src.slice(at("ai = 'connected-in-tour'"), at('2c. The draft landing'))

    it('branches on what actually appeared, not on an assumption', () => {
      // Without the branch the tour narrates "a title and a description, from
      // one line" over a screen showing neither - the most confusing thing a
      // walkthrough can do.
      expect(src).toMatch(/await s\.appeared\('\[data-tour="ai-connect"\]', 4000\)/)
      expect(at(`await s.appeared('[data-tour="ai-connect"]', 4000)`))
        .toBeGreaterThan(at('data-tour="task-draft"'))
      expect(at("ai = 'connected-in-tour'")).toBeLessThan(at('2c. The draft landing'))
    })

    it('rings the connect card, not Draft with AI, when the card is already up', () => {
      // The notice is component state that survives the planner being closed and
      // reopened, so on a replay the tour reaches the draft beat with "Meridian
      // needs an AI engine" already on screen. Ringing Draft there points at the
      // one button that cannot do what the narration describes - pressing it just
      // re-raises the same card.
      const c = code(src)
      // The probe runs first…
      expect(c.indexOf('askingAlready')).toBeLessThan(c.indexOf(`s.spotlight('[data-tour="task-draft"]')`))
      // …and the whole draft ring is inside its negation.
      const ring = c.slice(c.indexOf('if (!askingAlready)'), c.indexOf('await s.appeared(\'[data-tour="ai-connect"]\', 4000)'))
      expect(ring).toContain('data-tour="task-draft"')
      // …while the detour still runs on either route into it.
      expect(c).toMatch(/if \(askingAlready \|\| await s\.appeared/)
    })

    it('lets the card arrive and be read before pointing at it', () => {
      // The composer holds a "Checking your AI…" beat and the card fades in over
      // ~600ms. A spotlight landing during that is a second surprise on top of
      // the first. The pause must come BEFORE the spotlight, not after.
      const d = detour()
      expect(d.indexOf('s.pause(')).toBeLessThan(d.indexOf('s.spotlight('))
      const first = Number(d.match(/s\.pause\((\d+)\)/)?.[1])
      expect(first).toBeGreaterThanOrEqual(1000)
    })

    it('waits for the planner to come BACK, not for a modal to be closed', () => {
      // The app returns itself: once the provider is written, SettingsModal fires
      // `onLockSatisfied`, the shell arms a resume and reopens the planner, and the
      // draft the user already asked for runs on its own. Waiting on a close button
      // would race that - and that button is DISABLED until the step is done, so the
      // tour would have been waiting on a control that cannot be pressed.
      const d = detour()
      expect(d).toContain('data-tour="task-note"')
      expect(d).not.toContain("s.openModal('plan')")
      expect(d).not.toContain('modal-close')
    })

    it('rejoins the normal beats instead of re-asking for the draft click', () => {
      // The draft is already running by the time the planner is back. Asking for a
      // click that has effectively happened leaves the tour waiting on a button whose
      // work is done, with the fields filling in behind the instruction to press it.
      const d = detour()
      expect(d).not.toMatch(/waitForClick\('\[data-tour="task-draft"\]'/)
      // …and the beat it falls into is the one that watches the title fill.
      expect(at('2c. The draft landing')).toBeLessThan(at('waitForValue(\'[data-tour="task-title"]\''))
    })

    it('never dims - the detour is skippable, unlike the plan beat', () => {
      expect(detour()).not.toContain('dim')
    })

    it('waits on the subscription gate without taking a side', () => {
      // Settings opens LOCKED here, which puts the picker on its subscription question
      // rather than the provider grid. The tour must wait on EITHER answer and must not
      // ring one of them: the recommendation is the badge's job, and a spotlight on one
      // card makes the other read as the wrong answer.
      const d = detour()
      expect(d).toContain('gate-subscription')
      expect(d).toContain('gate-free')
      expect(d).not.toMatch(/spotlight\([^)]*gate-/)
    })

    it('has no beat at all for anyone already connected', () => {
      // TWO ways to arrive connected, and both used to get a beat that only made
      // a privacy claim - the writing runs on your machine, nothing reaches our
      // servers. Nothing was being ASKED in either, so the tour stopped to
      // assert something at the exact point the user is counting the beats left.
      // Beat 9 now exists only for the case that still needs an answer.
      expect(src).toContain("ai = 'connected-in-tour'")   // connected during the draft beat
      expect(src).toContain("ai = 'already-working'")     // set up before the tour began
      expect(src).toContain('if (ai === null) {')
      expect(at('if (ai === null) {')).toBeGreaterThan(at('── 9. AI ask'))
      // The claim itself is gone, not relocated.
      expect(src).not.toContain('never sits on our servers')
    })

    it('opens the provider picker only when nothing is connected', () => {
      // The case the single boolean got wrong: a working provider drafts
      // successfully, so the connect card never appears and the old flag stayed
      // false - and the beat told someone already set up to go and pick one.
      const beat9 = src.slice(at('── 9. AI ask'), at('── 10.'))
      expect(beat9.indexOf('openSettings')).toBeGreaterThan(beat9.indexOf('if (ai === null) {'))
    })
  })
})

describe('fmtSetupElapsed', () => {
  it('reads as seconds under a minute', () => {
    expect(fmtSetupElapsed(9)).toBe('9s')
    expect(fmtSetupElapsed(59)).toBe('59s')
  })

  it('drops a zero seconds remainder', () => {
    expect(fmtSetupElapsed(120)).toBe('2m')
  })

  it('keeps a non-zero remainder', () => {
    expect(fmtSetupElapsed(134)).toBe('2m 14s')
  })
})

// The tour now owns BOTH configuration asks — a project tool and an AI engine —
// because the setup wizard no longer has either step (app/setup/steps.tsx keeps
// INTEGRATIONS_STEP/PROVIDER_STEP defined but out of ALL_STEPS). If a beat here
// regresses, a first-run user is never asked at all, and the failure is silent:
// the app simply never syncs and never drafts.
describe('the tracker branch, moved to the front', () => {
  const src = SCRIPT_SRC
  const at = (n: string) => { const i = src.indexOf(n); if (i < 0) throw new Error(`missing: ${n}`); return i }
  const shell = readFileSync(import.meta.dir + '/../components/timeline/MeridianTimelineShell.tsx', 'utf8')
  const modal = readFileSync(import.meta.dir + '/../components/timeline/SettingsModal.tsx', 'utf8')
  const section = readFileSync(import.meta.dir + '/../components/timeline/settings/IntegrationsSection.tsx', 'utf8')
  const engine = readFileSync(import.meta.dir + '/../components/tutorial/engine.ts', 'utf8')
  const planView = readFileSync(import.meta.dir + '/../components/plan/PlanView.tsx', 'utf8')

  it('asks team-or-solo inside the planner, before the composer', () => {
    // Asked last, every earlier beat was written for a user we had not identified -
    // someone on a Jira board was walked through hand-writing a task while their
    // real tickets sat unimported two clicks away.
    expect(at("usesTracker = await s.ask(")).toBeLessThan(at('data-tour="task-note"'))
    expect(at('data-tour="plan-open"')).toBeLessThan(at("usesTracker = await s.ask("))
  })

  it('asks exactly once', () => {
    // The old late beat is gone. A second ask reads as the app having forgotten,
    // on the one screen whose whole job is to look attentive.
    expect(src.match(/await s\.ask\(/g)?.length ?? 0).toBe(1)
    expect(src).not.toContain("s.openSettings('integrations')")
  })

  it('locks the tracker step, and names it in the title', () => {
    expect(src).toContain("s.openSettings('integrations', { lock: true })")
    expect(modal).toContain("section === 'integrations' ? 'Connect your project tool'")
  })

  it('always offers a way out of that lock', () => {
    // A required step with five providers and no exit assumes every user is on
    // one of them. The person most likely to be stuck is exactly the one this is
    // easiest to mis-sell to. It renders with the gate, not after a failure.
    expect(section).toContain('data-tour="tracker-decline"')
    expect(section).toContain("I don&apos;t use a project tool")
    expect(modal).toContain("onDecline={() => release('declined')}")
  })

  it('releases the lock on a connected tracker, not on a visit', () => {
    expect(modal).toContain("TRACKERS.some((t) => integrations?.[t.id])) release('connected')")
  })

  it('says something different when they declined', () => {
    // Greeting "I don't use one" with "connected" would be the app reporting
    // something that did not happen, on the screen whose job was to find out.
    expect(src).toContain("const declined = consumeLockOutcome() === 'declined'")
    expect(modal).toContain('No problem - taking you back to your tasks')
    expect(engine).toContain('export const consumeLockOutcome')
  })

  it('stops telling them to pick a tool the moment they say they have none', () => {
    // The lock resolves on the click; the planner returns ~1.1s later. Waiting on
    // the PLANNER meant that in between, the tour was still saying "pick your tool
    // and sign in" to someone who had just said they do not have one - instruction
    // contradicting the decision, while the app was busy agreeing with it.
    const beat = src.slice(src.indexOf('Pick your tool and sign in'))
    const handback = beat.indexOf('lock-handback')
    const planner = beat.indexOf('plan-today')
    expect(handback).toBeGreaterThan(-1)
    expect(handback).toBeLessThan(planner)
    // And the stale line is cleared, not merely followed by another one.
    expect(beat.slice(handback, planner)).toContain("s.say('')")
  })

  it('explains the no-tracker path on a card that takes the screen', () => {
    // The one moment the tour just lost the feature it was selling. Said small and
    // in passing ("let's write this one by hand instead") a user concludes they
    // picked the broken path - when writing a task here IS the flow, and the
    // tracker only ever added import and posting.
    // Comment-stripped: the note explaining WHY the old wording was wrong quotes
    // it, and would trip the assertion that it is gone. (`code` is declared lower
    // in this file; test bodies run after the module finishes evaluating.)
    const stripped = code(src)
    const branch = stripped.slice(
      stripped.indexOf('if (declined) {'),
      stripped.indexOf('} else {', stripped.indexOf('if (declined) {')),
    )
    expect(branch).toContain('{ center: true }')
    expect(branch).toContain("Meridian's AI turns it into a proper task")
    expect(branch).not.toContain('by hand')
  })

  it('waits for whichever planner layout the answer produces', () => {
    // No tracker means PlanView renders its hero composer, and `plan-today` never
    // mounts - so waiting on that selector alone stranded a declined user for the
    // full ten-minute fallback.
    expect(src).toContain('[data-tour="plan-today"], [data-tour="task-note"]')
  })

  it('SHOWS the drag rather than blocking on it', () => {
    // This used to be "drag the ones you are doing today" plus a Done button. A
    // first-time user does not know a card can be picked up until they have seen
    // one move, so the tour was blocking - inside a modal - on the one gesture it
    // had given them no reason to believe in. Some pressed Done on an empty plan.
    expect(src).toContain("await s.demoDrag(BOARD_CARD, '[data-tour=\"plan-today\"]')")
    expect(src).toContain('const BOARD_CARD = \'[data-tour="plan-board"] [data-plan-card]\'')
    expect(src).not.toContain("'Done')")
    // No count afterwards either: some mornings are one ticket and some are six.
    expect(src).toContain("s.spotlight('[data-tour=\"plan-today\"]')")
  })

  it('lands the demonstrated drag as a REAL, saved move', () => {
    // A demonstration that reverts the moment it ends teaches the user that
    // nothing on this screen is real. The tour presses the product's own "+ Add"
    // button rather than reaching into plan state, so the card it just flew
    // across is genuinely in their plan - and so this cannot drift from the add
    // path when that changes.
    const hook = readFileSync(new URL('../components/tutorial/useTutorial.tsx', import.meta.url), 'utf8')
    const drag = hook.slice(hook.indexOf('demoDrag: async'), hook.indexOf('pause: (ms) =>'))
    expect(drag).toContain('button[aria-label^="Add "]')
    // …and the click lands BEFORE the ghost clears. The other order leaves the
    // column empty for a frame, which reads as the drop having missed.
    expect(drag.indexOf('add.click()')).toBeLessThan(drag.indexOf('setGhost(null)'))
  })

  it('gives New task the weight of a primary action', () => {
    // It was a 14%-alpha chip the size of a sort toggle, one row above three more
    // grey controls - the only way to author a task in the planner, reading as the
    // fourth filter. Solid accent puts it in the same class as "Add to today",
    // which is right: they are the two controls on this screen that CREATE.
    const board = readFileSync(new URL('../components/plan/PlanBoardColumn.tsx', import.meta.url), 'utf8')
    const btn = board.slice(board.indexOf('data-tour="plan-new-task"'), board.indexOf('New task', board.indexOf('data-tour="plan-new-task"')))
    expect(btn).toContain("background: 'var(--color-state-proposal)'")
    expect(btn).toContain("color: '#fff'")
    expect(btn).not.toContain('14%')
  })

  it('gives both columns a real heading', () => {
    // "Today" and "Your tasks" say which half is your day and which half is your
    // board - the only structural labels on the screen. As `.mt-label` micro-caps
    // they read as field labels for the controls underneath instead.
    for (const f of ['PlanTodayColumn', 'PlanBoardColumn']) {
      const s = readFileSync(new URL(`../components/plan/${f}.tsx`, import.meta.url), 'utf8')
      expect(s).toContain("font: '800 16px var(--font-sans)'")
    }
  })

  it('shows that tasks can be written here too, not only imported', () => {
    // Someone who just imported a board assumes tasks come FROM the board and
    // this is a viewer. That belief is the difference between Meridian being a
    // mirror and being where they work.
    expect(src).toContain('data-tour="plan-new-task"')
    expect(at('data-tour="plan-today"')).toBeLessThan(at('data-tour="plan-new-task"'))
  })

  it('does not pre-fill Today while the tour is demonstrating the drag', () => {
    // The app would otherwise have already performed the move the next beat asks
    // for, and on a fresh board the seed is often one stale ticket the user does
    // not recognise sitting in their plan.
    expect(planView).toContain('isTutorialRunning() ? [] : d.suggestions.map(fromAvailable)')
    expect(engine).toContain('export const isTutorialRunning')
  })

  it('lets the script decide which Settings opens are locks', () => {
    // Only the script knows which of its opens are asks it intends to hold the
    // user on and which merely show them where something lives.
    expect(shell).toContain('setSettingsLock,')
    expect(src).not.toContain("openSettings('intelligence', { lock: true })")
  })
})

// ── Overlay chrome ──────────────────────────────────────────────────────────
//
// Three bugs that all shipped looking deliberate, which is why each gets a test
// rather than a fix and a shrug. None of them threw, none broke layout, and all
// three were visible only if you knew what the code was supposed to be doing.

/** Source with comments stripped. Every rule below is about what the file DOES,
 *  and each of these fixes left a comment explaining the bug it removed - so
 *  asserting against the raw text makes the explanation re-trip the test it
 *  documents. Crude on purpose: it only has to survive this repo's own comments,
 *  not arbitrary JS (a `//` inside a string literal would fool it). */
const code = (src: string) =>
  src.replace(/\/\*[\s\S]*?\*\//g, '').split('\n').filter(l => !/^\s*\/\//.test(l)).join('\n')

describe('the tour aims at the replica, not the dashboard behind it', () => {
  const engine = code(readFileSync(new URL('../components/tutorial/engine.ts', import.meta.url), 'utf8'))
  const hook = code(readFileSync(new URL('../components/tutorial/useTutorial.tsx', import.meta.url), 'utf8'))
  const ov = code(readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8'))
  const scr = code(readFileSync(new URL('../components/tutorial/TutorialScreen.tsx', import.meta.url), 'utf8'))

  it('marks its own surface', () => {
    // The walkthrough draws OVER the live dashboard rather than replacing it, so
    // both carry the same `data-tour` hooks - and the shell renders first.
    expect(engine).toContain("TOUR_SURFACE_ATTR = 'data-tour-surface'")
    expect(scr).toContain('TOUR_SURFACE_ATTR')
  })

  it('resolves every tour selector through it', () => {
    // A bare document query returns the HIDDEN original, so the ring and the
    // cursor land on its coordinates - near the replica but not on it, since the
    // real toolbar carries chrome the replica does not - and the beat can only
    // finish on its fallback timer, because the control the user can actually
    // press was never the one measured.
    for (const f of [hook, ov]) {
      expect(f).not.toContain('document.querySelector')
    }
    // In the engine the only bare query left is `tourTarget`'s own fallback.
    expect(engine.split('document.querySelector').length - 1).toBe(2)
    expect(engine).toContain('const el = tourTarget(selector)')
    expect(ov).toContain('const el = tourTarget(selector)')
    expect(hook).toContain('tourTarget(`[data-task-id=')
  })

  it('keeps the ring mounted so it can travel between beats', () => {
    // The script clears the spotlight between almost every pair of beats, and
    // this used to answer null the instant it did - unmounting the ring, so the
    // next beat mounted a NEW element at the new coordinates. A fresh element
    // has nothing to transition from, so the `transition` was dead on arrival
    // and every move was a hard cut however long the duration said.
    expect(ov).toContain('rect: DOMRect | null; live: boolean')
    expect(ov).toContain('{ringBox && (')
    expect(ov).toContain('opacity: ringLive ? 1 : 0')
    // And `live`, not the retained box, is what the caption logic reads.
    expect(ov).toContain('const ring = ringLive ? ringBox : null')
  })

  it('fades the narration between sentences rather than swapping words', () => {
    // The bubble stays put, so a text change in place is the change the eye is
    // least likely to notice and most likely to find abrupt.
    expect(ov.split('key={caption}').length - 1).toBe(2)
    expect(ov).toContain('mer-tour-say')
  })

  it('fades a pane arriving in a slot another pane just left', () => {
    const scrTop = readFileSync(new URL('../components/tutorial/TutorialScreen.tsx', import.meta.url), 'utf8')
    const card = readFileSync(new URL('../components/tutorial/TutorialSummaryCard.tsx', import.meta.url), 'utf8')
    const css = readFileSync(new URL('../app/globals.css', import.meta.url), 'utf8')
    // Keyed on WHICH view, never on the task id - re-selecting a card must not
    // re-animate a panel that is already there.
    expect(scrTop).toContain("key={replayMinute !== null ? 'replay' : selected ? 'task' : 'panel'}")
    expect(card).toContain("key={task ? 'task' : 'home'}")
    expect(css).toContain('.mer-tour-pane')
    expect(css).toContain('.mer-tour-pane { animation: none; }')
  })

  it('portals the worklog dialog out of the animated column', () => {
    // The dialog is `fixed inset-0` so it centres on the WINDOW while being
    // called from deep inside the 388px right-hand column - and `fixed` only
    // means that while no ancestor has a transform (which becomes the containing
    // block, fencing the dialog into the column) and no ancestor animates
    // opacity (which opens a stacking context, letting the timeline paint over
    // it). Both shipped, from two different animations on that column. A portal
    // to `document.body` removes the class of bug rather than the instances, so
    // nobody has to know this rule before animating a pane.
    const dlg = readFileSync(new URL('../components/timeline/WorklogDraftDialog.tsx', import.meta.url), 'utf8')
    expect(dlg).toContain("import { createPortal } from 'react-dom'")
    expect(dlg).toContain('return createPortal(')
    // Resolved after mount: `document` does not exist during the static export's
    // prerender, and this only ever renders in response to a click.
    expect(dlg).toContain('useEffect(() => { setHost(document.body) }, [])')
    expect(dlg).toContain('if (!host) return null')
  })

  it('still falls back to the whole document', () => {
    // Plenty of anchors are deliberately outside the surface: the real settings
    // modal, the worklog schedule dialog, every modal the tour opens for real.
    expect(engine).toContain('?? document.querySelector(selector)')
  })
})

describe('the tour overlay draws what it means to', () => {
  const overlay = code(readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8'))
  const screen = code(readFileSync(new URL('../components/tutorial/TutorialScreen.tsx', import.meta.url), 'utf8'))

  it('speaks in one voice, on its own surface, wherever it speaks', () => {
    // Both bubbles take the SAME surface constant, and neither styles its own.
    // They drifted apart once already - one inverted, one not, at different
    // sizes - which is how the tour ended up with two voices.
    const anchored = overlay.slice(overlay.indexOf('function AnchoredCaption'),
      overlay.indexOf('function DimCutout'))
    expect(anchored).toContain('...CAPTION_SURFACE')
    expect(anchored).not.toContain('background:')
    expect(overlay.match(/\.\.\.CAPTION_SURFACE/g)?.length).toBe(2)
  })

  it('keeps the narration inverted, at body size', () => {
    // The tour speaks on its OWN surface: a light card here is a white box on a
    // white page, and inside a modal - which is `--t-card` itself - it vanishes.
    // Tried the other way round once, on the reasoning that light type on a dark
    // fill blooms under macOS font smoothing. It does, but the bubble stopped
    // reading as the guide and started reading as content, which is worse.
    expect(overlay).toContain("background: 'var(--t-title)'")
    expect(overlay).toContain("color: 'var(--t-card)'")
    // Body weight and size, not something larger. At 15px/600 the bubble
    // competes with the headings it is pointing at - and heavier inverted type
    // is exactly what softens.
    expect(overlay).toContain("font: '500 13px/1.5 var(--font-sans)'")
    // Set once, on the shared constant - never per bubble, which is how the two
    // variants ended up disagreeing.
    const bubbles = overlay.slice(overlay.indexOf('Narration, pinned bottom-centre'))
    expect(bubbles).not.toContain("className=\"mt-body\"")
  })

  it('names the button it is pointing at, not the mechanism behind it', () => {
    // "Every day rolls up into one screen" describes a mechanism and leaves the
    // reader to work out what they are about to see. The pill under the cursor
    // says "Daily summary".
    expect(SCRIPT_SRC).toContain('Your whole day, summarised. Open it.')
    expect(code(SCRIPT_SRC)).not.toContain('rolls up into one screen. Open it.')
  })

  it('never color-mixes against --win-bg', () => {
    // --win-bg is a linear-gradient, and color-mix() takes colours. The whole
    // declaration is therefore invalid and CSS drops it silently, leaving a
    // backdrop-filter blurring the page without dimming it - which reads as an
    // intentional soft-focus rather than as a missing scrim. Three separate
    // surfaces had it.
    expect(overlay).not.toContain('color-mix(in srgb, var(--win-bg)')
    expect(screen).not.toContain('color-mix(in srgb, var(--win-bg)')
  })

  it('does not put mer-pop on the element that centres the narration bar', () => {
    // .mer-pop animates `transform` with fill `both`, so it overwrites an inline
    // translateX(-50%) permanently: the bar rendered half its own width right of
    // centre and overlapped whatever modal was open. Centring and the animation
    // must live on different elements.
    // Stated as a property of the whole file rather than of one block: ANY
    // element carrying both loses its positioning transform the moment the
    // animation starts, so the rule is "never on the same element", full stop.
    for (const line of overlay.split('\n')) {
      if (line.includes('mer-pop')) expect(line).not.toContain('translateX')
    }
    // Both halves still exist - the fix separated them, it did not drop either.
    expect(overlay).toContain("transform: 'translateX(-50%)'")
    expect(overlay).toContain('className="mer-pop"')
  })

  it('hides the ring and cursor behind a centred beat', () => {
    // A centred beat scrims the page, so a ring around something invisible and a
    // cursor gliding toward it are noise on top of a question.
    expect(overlay).toContain('useAnchor(centered || cursorPoint ? null : cursorAt)')
    expect(overlay).toContain('const cursor = centered ? null : (cursorPoint ?? anchored)')
    expect(overlay).toContain('useRect(centered ? null : spotlight)')
  })
})

describe('the tour cursor retracts', () => {
  const hook = readFileSync(new URL('../components/tutorial/useTutorial.tsx', import.meta.url), 'utf8')

  it('parks on every interaction end and surface change', () => {
    // The cursor means "click HERE". Left set after the click it lands on, it
    // then glides across the screen toward a control the tour has finished with -
    // which is how a cursor ended up drifting at the plan nudge while the connect
    // modal was open. Every exit path funnels through one helper.
    // Clears the demoDrag point override too - a stale one would pin the cursor
    // to a spot on the screen and silently outrank every later `point`.
    expect(hook).toContain('const parkCursor = () => { setCursorAt(null); setCursorPoint(null) }')
    // stageAsk (both ask and next), waitForClick, waitForValue, openModal,
    // openSettings — five call sites plus the declaration.
    expect(hook.match(/parkCursor\(\)/g)?.length).toBeGreaterThanOrEqual(5)
    expect(hook).toContain('openModal: (m) => { parkCursor(); setActiveModal(m) }')
  })
})

describe('the locked integrations gate', () => {
  const section = code(readFileSync(new URL('../components/timeline/settings/IntegrationsSection.tsx', import.meta.url), 'utf8'))

  it('has exactly one way out, and it is a real button', () => {
    // There were two: the working opt-out, and a bold accent-coloured <span>
    // reading "Skip this" with no handler. On the locked screen that dead link is
    // the first thing a stuck user presses, and pressing it does nothing - which
    // is how someone concludes they are trapped.
    expect(section).not.toContain('Skip this')
    expect(section).toContain('data-tour="tracker-decline"')
    expect(section.match(/onClick=\{onDecline\}/g)?.length).toBe(1)
  })

  it('uses plain hyphens in the copy it shows', () => {
    // CLAUDE.md hard rule for user-facing app text. `section` is already
    // comment-stripped, so this sees only what ships.
    expect(section).not.toMatch(/[—–]/)
  })
})

describe('a gated settings section does not title itself', () => {
  // Whoever owns the frame owns the title. Under a lock the modal header states
  // the ask ("Connect your project tool" / "Connect your AI engine"), so a second
  // heading right beneath it reads as a different question rather than the same
  // one restated - and on a screen the user cannot leave, an unexplained second
  // question is expensive.
  const gated = (p: string) =>
    code(readFileSync(new URL(p, import.meta.url), 'utf8'))

  it('drops the integrations heading under gate', () => {
    const s = gated('../components/timeline/settings/IntegrationsSection.tsx')
    const guard = s.indexOf('{!gate && (')
    expect(guard).toBeGreaterThan(-1)
    // The heading must sit INSIDE that guard - between it and its closing `)}`,
    // not merely somewhere later in the file.
    const block = s.slice(guard, s.indexOf(')}', guard))
    expect(block).toContain('Connect your board')
    expect(block).toContain('Project management')
  })

  it('and the intelligence section already did', () => {
    // The precedent this follows. If it ever regresses, the two gates drift and
    // the reason for the rule above stops being discoverable from either.
    const s = gated('../components/timeline/settings/IntelligenceSection.tsx')
    expect(s).toContain('{gate ? (')
    expect(s).toContain('LLM_INTRO_TITLE')
  })
})

describe('the plan saves itself', () => {
  const view = code(readFileSync(new URL('../components/plan/PlanView.tsx', import.meta.url), 'utf8'))
  const col = code(readFileSync(new URL('../components/plan/PlanTodayColumn.tsx', import.meta.url), 'utf8'))

  it('writes on every change instead of behind a button', () => {
    // Dragging a ticket into a column labelled "Today" IS saying it is today's
    // work. A button to agree with yourself afterwards had one real effect:
    // letting people lose the plan by closing the modal before pressing it.
    expect(view).toContain("metaAction('confirm', next.map(t => t.key))")
    expect(col).not.toContain('onConfirm')
    expect(col).not.toContain('Save changes')
    expect(col).not.toContain('Edit plan')
  })

  it('stays editable after saving', () => {
    // The trap in auto-save: keep the old confirmed-means-locked rule and the
    // FIRST drag freezes the column, so a second one needs "Edit plan" first.
    expect(view).toContain('const editable = !skipped')
    expect(view).not.toContain('const proposed =')
  })

  it('keeps the plan cap on the one write path', () => {
    // Every add still funnels through commit, so the guard cannot be bypassed by
    // the route that now also persists.
    const commit = view.slice(view.indexOf('const commit = useCallback'), view.indexOf('const editable'))
    expect(commit).toContain('MAX_PLAN_TASKS')
    expect(commit).toContain('setCapHit(true)')
    // The refusal must return BEFORE the write.
    expect(commit.indexOf('setCapHit(true)')).toBeLessThan(commit.indexOf("metaAction('confirm'"))
  })

  it('still lets the user skip the day', () => {
    // Skipping is a real decision, unlike confirming what you just did.
    expect(col).toContain('onSkip')
    expect(col).toContain('onReopen')
  })
})

describe('the walkthrough points at the way out', () => {
  const src = SCRIPT_SRC

  it('rings the close button it tells the user to press', () => {
    // Both closing lines end with "close this when you are done" and then pointed
    // at nothing, leaving the user to hunt a corner control at the end of a beat
    // where every other instruction came with a ring.
    expect(src).toContain('s.spotlight(\'[data-tour="modal-close"]\')')
    expect(src).toContain('await s.point(\'[data-tour="modal-close"]\')')
  })

  it('keeps the dev jump-to-the-day pill out of a packaged build', () => {
    // It skips PAST the compulsory AI-connect step, which the timeline, the
    // summaries and the worklogs all need - shipped, it would be a supported way
    // to end up with a product that generates nothing. Gated at the source (the
    // prop is null, so the button is never rendered) rather than hidden with CSS.
    const hook = readFileSync(new URL('../components/tutorial/useTutorial.tsx', import.meta.url), 'utf8')
    expect(hook).toContain('onSkipToDay={TOUR_DEV_TOOLS ? skipToDay : null}')
    expect(hook).toContain("export const TOUR_DEV_TOOLS = process.env.NODE_ENV !== 'production'")
    const overlay = readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8')
    expect(overlay).toContain('{onSkipToDay && (')

    // And it ABORTS the running script before restarting. Without the `finish`,
    // clearing the started latch just starts a second script beside the first,
    // both driving one stage and taking turns writing the caption.
    expect(hook).toMatch(/const skipToDay = useCallback\(\(\) => \{\s*finish\(\)\s*replayFromDay\(\)/)
  })
})

describe('the first-run journey holds together on every branch', () => {
  const src = code(SCRIPT_SRC)
  const shell = code(readFileSync(new URL('../components/timeline/MeridianTimelineShell.tsx', import.meta.url), 'utf8'))

  it('does not promise a board post to someone who said they have none', () => {
    // `usesTracker` is set by the QUESTION ("I'm on a team board"), but beat 7's
    // closing line is about what they CONNECTED. Someone who then pressed "I don't
    // use a project tool" would be promised "Meridian posts these to your board" -
    // a promise the product contradicts within the hour.
    expect(src).toContain("if (declined) usesTracker = 'solo'")
    // Every read in the SECOND half runs after the decline can have downgraded
    // it. (An earlier read exists in part one, inside the branch that sets it -
    // hence the slice rather than a bare indexOf.)
    const afterDecline = src.slice(src.indexOf("if (declined) usesTracker = 'solo'"))
    expect(afterDecline).toContain("usesTracker === 'tracker'")

    // And the worklog demonstration is GATED on it, not merely worded around it:
    // with no board connected the panel deliberately shows "Connect a tracker"
    // WHERE Generate would be, so the beat would have no button to point at.
    // Anchored on a CODE line: `code()` has stripped the beat headers, which are
    // comments.
    const dayHalf = src.slice(src.indexOf('data-tour="detail-done"'))
    expect(dayHalf.indexOf("if (usesTracker === 'tracker') {"))
      .toBeLessThan(dayHalf.indexOf('data-tour="wl-open"'))
  })

  it('only teaches the drag when there is a board to drag from', () => {
    // Connecting a tracker does not guarantee tickets - a new project, a filter
    // matching nothing, or an unfinished sync all leave the board empty, and
    // PlanView then renders the hero composer with no board column. Narrating a
    // drag in front of that reads as the connect having failed.
    //
    // Anchored on a CARD, not on the Today column: that column renders whether or
    // not anything landed in the other one, so guarding on it passed in exactly
    // the case this exists to catch - and demoDrag needs a real card to clone.
    expect(src).toContain('} else if (await waitForTickets(s)) {')
    expect(src).toContain('const got = await s.appeared(BOARD_CARD, 25000)')
  })

  it('waits out the first tracker sync instead of probing for it', () => {
    // `available` is read from the local DB, which a tracker connected thirty
    // seconds ago has not populated. PlanView fires one catch-up sync_tasks on
    // open; that call goes to Jira over the network. The first version gave it
    // 2.5s - roughly a tenth of a first Jira sync - so the tour decided there were
    // no tickets and taught hand-writing a task to someone who had just imported a
    // board, while their tickets arrived behind the modal it had moved on to.
    const plan = readFileSync(new URL('../components/plan/PlanView.tsx', import.meta.url), 'utf8')
    // Once per mount, never a poll - it is an outward API call per tracker.
    expect(plan).toContain('if (autoSyncedRef.current || !trackersLoaded || !data) return')
    expect(plan).toContain('handleSync().finally(() => setFirstSyncDone(true))')
  })

  it('never flashes the write-it-by-hand layout at someone whose board is loading', () => {
    // `available` reads the local DB, so for the first frames after a connect it is
    // empty because the sync has not run, not because the board is. Committing to
    // `boardEmpty` then showed the hero composer - "write your first task by hand" -
    // to someone who had just imported a Jira project, for the second or two before
    // the tickets landed and it swapped underneath them. A layout that changes its
    // mind about what the user's setup IS reads as a half-failed connect.
    const plan = readFileSync(new URL('../components/plan/PlanView.tsx', import.meta.url), 'utf8')
    expect(plan).toContain('&& trackersLoaded && firstSyncDone')
    // …and the layout they DO get says why its board is empty.
    expect(plan).toContain('pulling={!firstSyncDone || syncing}')
    const board = readFileSync(new URL('../components/plan/PlanBoardColumn.tsx', import.meta.url), 'utf8')
    expect(board).toContain("'Pulling in your tickets…'")
  })

  it('stops for the where-it-goes choice, and only when there is one', () => {
    // The only decision on the composer with a consequence outside Meridian: one
    // option files a real ticket a team can see. Undiscovered, it is how someone
    // posts to a shared board by accident, or writes three days of personal notes
    // wondering why nobody sees them. Probed, not assumed - a solo user has no
    // choice to make and gets no beat.
    expect(src).toContain('if (await s.appeared(\'[data-tour="task-where"]\', 1200)) {')
    expect(src).toContain('await s.waitForClick(\'[data-tour="task-where"] [role="radio"]\', 120000)')
    expect(src.indexOf('data-tour="task-where"')).toBeLessThan(src.indexOf('data-tour="task-add"'))
    const composer = readFileSync(new URL('../components/plan/TaskComposer.tsx', import.meta.url), 'utf8')
    expect(composer).toContain('data-tour="task-where"')
  })

  it('does not invite an edit to something the AI just got right', () => {
    // "A title and a description, from one line. Edit anything you like." went up
    // while the model was still writing - asking the user to correct a sentence
    // that had not finished appearing. Said the second after the AI does the job it
    // was sold on, it plants a doubt and stalls someone who now feels they are
    // meant to find something to fix. The boxes are visibly editable anyway.
    expect(src).not.toContain('Edit anything you like')
  })

  it('resumes the composer only for the detour that left it mid-write', () => {
    // armResume means "keep the note, re-run the draft". True of the AI lock, which
    // is entered FROM the composer. False of the tracker lock, which is entered
    // before the composer is ever opened - and arming it there suppressed
    // resetComposer(), so the box came back holding a task the user never wrote.
    expect(shell).toContain("if (settingsSection !== 'integrations') armResume()")
  })

  it('does not point at Add to today until the button can actually be pressed', () => {
    // `canCreate` needs a title of MIN_TITLE_WORDS *and* a description. The model
    // fills the fields in order, so there is a real window where the title has
    // landed and the description has not - "Happy with it? Add it to today" over
    // a greyed-out button reads as the app having stalled.
    const composer = readFileSync(new URL('../components/plan/TaskComposer.tsx', import.meta.url), 'utf8')
    expect(composer).toContain('data-tour="task-desc"')
    const titleWait = src.indexOf('waitForValue(\'[data-tour="task-title"]\'')
    const descWait = src.indexOf('waitForValue(\'[data-tour="task-desc"]\'')
    expect(descWait).toBeGreaterThan(titleWait)
    expect(descWait).toBeLessThan(src.indexOf('data-tour="task-add"'))
  })
})

describe('the day replay - the timeline taught by building it', () => {
  const src = SCRIPT_SRC
  const hook = readFileSync(new URL('../components/tutorial/useTutorial.tsx', import.meta.url), 'utf8')
  const screen = readFileSync(new URL('../components/tutorial/TutorialScreen.tsx', import.meta.url), 'utf8')
  const aside = readFileSync(new URL('../components/tutorial/ReplayAside.tsx', import.meta.url), 'utf8')
  const column = readFileSync(new URL('../components/timeline/DayTaskColumn.tsx', import.meta.url), 'utf8')

  it('stops on the finished day before sending anyone to a card', () => {
    // Nine hours resolve into one screen here, and that screen is the product's
    // whole answer to "where did my day go". Going straight from the last hour to
    // "open the big one in the afternoon" spends the payoff on an errand, while
    // the thing the user just watched get built is still being taken in.
    const after = src.slice(src.indexOf('await s.replayDay(['))
    const showcase = after.indexOf('s.spotlight(\'[data-tour="day-view"]\')')
    expect(showcase).toBeGreaterThan(-1)
    expect(showcase).toBeLessThan(after.indexOf('That is the day.'))
    // The WHOLE view, right-hand breakdown included - the claim is about the day
    // as one finished thing, and the hours/apps/categories are half the answer.
    expect(screen).toContain('data-tour="day-view"')
    // A ring that big cannot park a bubble beside it; the overlay has to fall
    // back to the top bar or the beat narrates off the bottom of the screen.
    const overlay = readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8')
    expect(overlay).toContain('{caption && !centered && ring && ringFits && (')
    expect(overlay).toContain('{caption && !centered && !(ring && ringFits) && (')
  })

  it('parks the caption below its target, off the heading', () => {
    // The bubble used to prefer ABOVE, which is precisely where a labelled block
    // keeps its label - so the caption explaining "WHEN you did it" covered the
    // words "When you did it", and the same for the block below it. Above is now
    // the fallback for targets with no room beneath them.
    const overlay = readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8')
    expect(overlay).toContain('const above = fitsAbove && !fitsBelow')
  })

  it('does not close the panel the user just opened', () => {
    // `selectTask` opens the panel by synthesising a click on the card, and the
    // card's handler TOGGLES - so firing it after a real click shut the panel the
    // instant it opened, and the two ringed beats then narrated a block that was
    // not on screen (with their captions falling back to the top bar, over the
    // timeline). It is the fallback for a user who never clicked, nothing more.
    expect(src).toContain('const opened = await s.waitForClick(card(FOCUS_TASK_ID), 60000)')
    expect(src).toContain('if (!opened) s.selectTask(FOCUS_TASK_ID)')
    // And the panel is CONFIRMED open before anything explains it - the failure is
    // otherwise silent, since a missing ring just relocates the caption.
    expect(src).toContain("await s.appeared('[data-tour=\"detail-when\"]', 1500)")
  })

  it('hands the daily-summary click to the user, with no preamble beat', () => {
    // It used to run a full-screen "Next" beat promising the screen, then click
    // the pill ITSELF - so the user pressed a button that was not the one being
    // described, and then watched the real control get pressed for them. One
    // ring, one short line, and they press it.
    expect(src).not.toContain('That was one task.')
    const open = src.slice(src.indexOf('data-tour="summary-pill"'))
    expect(open).toContain('await s.waitForClick(\'[data-tour="summary-pill"]\', 60000)')
    // The pill in the tutorial toolbar is an inert replica, so the script still
    // owns the render - but only AFTER the user's click, never instead of it.
    expect(open.indexOf('waitForClick')).toBeLessThan(open.indexOf('s.demoSummary(true)'))
    expect(src).not.toContain('s.click()\n  s.spotlight(null)\n  s.demoSummary(true)')
  })

  it('names both halves of the detail panel, one ring each', () => {
    // The panel is where the product answers "how would it possibly know that?",
    // and it answers twice: WHEN is the evidence (real times, and the break kept
    // out of the total), WHAT WAS DONE is the output. This used to be one line
    // ending "that write-up is on the right", which pointed at both and named
    // neither - so the times read as a label and the bullets read as something
    // the user might have typed themselves.
    expect(src).toContain('s.spotlight(\'[data-tour="detail-when"]\')')
    expect(src).toContain('s.spotlight(\'[data-tour="detail-done"]\')')
    expect(src.indexOf('detail-when')).toBeLessThan(src.indexOf('detail-done'))
    const panel = readFileSync(new URL('../components/timeline/DayTaskDetailPanel.tsx', import.meta.url), 'utf8')
    expect(panel).toContain('data-tour="detail-when"')
    expect(panel).toContain('data-tour="detail-done"')
  })

  it('BUILDS the example day instead of presenting it finished', () => {
    // The timeline is the half of the product that happens while the user is not
    // looking, so a finished screenshot teaches the wrong thing entirely - it
    // reads as a report someone filled in. The same day arriving hour by hour off
    // a clock reads as the app doing it, which is the whole claim.
    expect(src).toContain('await s.replayDay([')
    // …and the old "here's what your day will look like" still-frame is gone.
    expect(src).not.toContain("Now here's what your day will look like")
    // The example is revealed for the replay, not before it.
    expect(src.indexOf('s.showExample(true)')).toBeLessThan(src.indexOf('await s.replayDay(['))
  })

  it('runs 9 to 6 and reveals each card as its hour is reached', () => {
    expect(hook).toContain('const HOURS = 9')
    expect(hook).toContain('await tween(h * 60, (h + 1) * 60, PER_HOUR_MS, sig, setReplayMin)')
    // THE WHOLE DAY, ALWAYS. The column fits its vertical scale to the tasks it
    // is handed (buildTimelineScale + taskWindow), so handing it a list that
    // GROWS re-scales the column on every reveal and the timeline appears to
    // zoom out from under the cards already on it. The reveal has to be a
    // property of the card, never of this list — same as the marketing demo,
    // which renders the finished day and only strips an `is-pre` class off it.
    expect(hook).toContain('tasks={example ? SAMPLE_TASKS : NO_TASKS}')
    expect(hook).not.toContain('revealedBy(')
    // Revealed on the FIRST segment's start, matching demo.js's `taskStart <= m`:
    // a card appears whole the moment its work began, because the lesson is "a
    // task showed up", not "a rectangle got longer". Keying it on the card's END
    // instead was tried and reverted - every card then lands well after the work it
    // represents, so the reveal drifts out of step with the rail.
    expect(column).toContain('(l.segments[0]?.startMin ?? l.footLo) <= replayNowMin')
    // Hidden, not unmounted — that is what keeps the geometry still.
    expect(column).toContain('opacity: pre ? 0 : dimmed ? 0.38 : 1,')
    // ...and the header climbs with the cards rather than announcing the
    // finished day's totals over an empty board at 9 AM.
    expect(column).toContain('const shownLaid = revealed === null ? laid : laid.filter(l => revealed.has(l.task.id))')
    expect(column).toContain('{shownCount} task${shownCount === 1 ? \'\' : \'s\'} today')
  })

  it('says it is an example on the hour the first card lands', () => {
    // The one moment someone might mistake the replay for their own day - and the
    // tour has just spent two minutes on their real screen, so the risk is real.
    const marks = src.slice(src.indexOf('await s.replayDay(['), src.indexOf('])', src.indexOf('await s.replayDay([')))
    expect(marks).toMatch(/\{ hour: 9, say: '[^']*example day, not your data/)
  })

  it('puts the clock ON THE RAIL, not in a dial beside it', () => {
    // The replay used to run a clock face in the right panel while the timeline
    // filled silently next to it - which put the passage of time in a decoration
    // and left the product surface looking like it was being filled from
    // offstage. The rail lights hour by hour behind a descending now-line
    // instead, so the time and the work share an axis, as they do in the product.
    expect(screen).toContain('replayNowMin={replayMinute !== null ? 540 + replayMinute : null}')
    expect(column).toContain('replayNowMin?: number | null')
    // The now-line, and hours held back until it reaches them.
    expect(column).toContain('const reached = replayNowMin === null || hour * 60 <= replayNowMin + 1')
    expect(column).toContain('clockLabel(replayNowMin)')
    // No dial anywhere any more.
    expect(screen).not.toContain('ReplayClock')
    expect(aside).not.toContain('rotate(')
  })

  it('puts the replay narration in the panel, off the timeline', () => {
    // The panel's ordinary stats are a FINISHED day's totals - beside a timeline
    // still filling they are the answer printed next to the question - so the
    // replay takes the column over. The NARRATION lives there too, because the
    // overlay bar is centred at the top of the window, i.e. directly on top of
    // the first two hours of the day it is describing.
    expect(screen).toContain('<ReplayAside minute={replayMinute} note={replayNote} />')
    expect(hook).toContain('if (mark) setReplayNote(mark.say)')
    // ...and NOT in the bar, at headline size, over the cards.
    expect(hook).not.toContain('if (mark) setCaption(mark.say)')
    expect(hook).not.toContain('setCaptionBig(true)')
  })

  it('keeps the replay panel down to one line at a time', () => {
    // Nobody reads three paragraphs while watching a column fill itself. The
    // panel carried two standing blocks of prose AND the narration ran over the
    // timeline; all of it competed with the one thing the user was told to watch.
    const paras = [...aside.matchAll(/className="mt-body/g)]
    expect(paras.length).toBe(1)
    for (const m of SCRIPT_SRC.matchAll(/\{ hour: \d+, say: '([^']*)' \}/g)) {
      expect(m[1].length).toBeLessThanOrEqual(80)
    }
  })

  it('reveals arriving cards without moving anything already on screen', () => {
    // This used to be a wrapper class (`mer-replay`) driving a MOUNT animation on
    // `.dt-card`, which only fired per-hour because the task list was growing -
    // the same growing list that re-scaled the column and made the replay look
    // like it was zooming. Both are gone: the day is handed over whole, and the
    // reveal is the card's own opacity.
    expect(screen).toContain('className="relative flex-1 min-w-0 min-h-0 flex flex-col">')
    expect(screen).not.toContain("' mer-replay' : ''")
    // And no scale in the reveal. A card that is already in its final position
    // growing into it is indistinguishable, at speed, from the layout moving.
    expect(screen).not.toContain('@keyframes mer-card-in')
    expect(column).toContain("transform: pre ? 'translateY(7px)' : undefined,")
  })

  it('celebrates exactly once, on the last screen', () => {
    // A tour that congratulates every step congratulates nothing. It used to
    // fire mid-tour, at the seam where the user stops giving Meridian things -
    // a real milestone, but not the finish line. The last beat is the only
    // moment in a first run where "you are done" is literally true.
    const day = readFileSync(new URL('../components/tutorial/scriptDay.ts', import.meta.url), 'utf8')
    const partOne = readFileSync(new URL('../components/tutorial/script.ts', import.meta.url), 'utf8')
    expect(partOne.match(/celebrate: true/g) ?? []).toHaveLength(0)
    expect(day.match(/celebrate: true/g)?.length).toBe(1)
    expect(day.indexOf('celebrate: true')).toBeGreaterThan(day.indexOf('── 13. Handoff'))
    // And it is addressed to the user rather than to the product - the one place
    // the tour says why any of it was built.
    expect(day).toContain('your work stops going unnoticed')
    const overlay = readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8')
    // Deterministic burst - a first-run screen that looks different every time it
    // is seen is a first-run screen that looks unfinished.
    expect(overlay).toContain('mer-tour-fleck')
    expect(overlay).not.toMatch(/Math\.random/)
  })
})

describe('user-facing copy never names a tracker you cannot connect', () => {
  const files = [
    'components/tutorial/script.ts',
    'components/plan/PlanView.tsx',
    // The auto-log CTA moved here when the worklog became its own dialog.
    'components/timeline/WorklogActions.tsx',
  ]

  it('derives every tracker list from the registry', () => {
    // Linear, Trello and Azure DevOps are flagged `comingSoon`. Three separate
    // strings wrote the names out by hand - the worst being the auto-log CTA,
    // which listed all five, so someone on Trello read it as an offer and found
    // the row greyed out. `availableTrackerNames()` has existed for this the
    // whole time.
    for (const f of files) {
      const src = readFileSync(new URL(`../${f}`, import.meta.url), 'utf8')
      const strings = src.split('\n').filter(l => !/^\s*(\/\/|\*)/.test(l)).join('\n')
      expect(strings).toContain('availableTrackerNames()')
      expect(strings).not.toMatch(/Jira, Linear|Linear or GitHub|Linear, GitHub/)
    }
  })

  it('shows only offered logos on the team-or-solo card', () => {
    // A brand mark on a first-run screen is an offer. Someone picks the team-board
    // branch BECAUSE they spotted their tool, then cannot connect it.
    const overlay = readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8')
    expect(overlay).toContain('const offered = availableTrackers()')
    expect(overlay).not.toMatch(/\['jira', 'linear', 'github'\]/)
  })
})

describe('the OAuth wait has a way out that looks like one', () => {
  const src = readFileSync(new URL('../components/IntegrationConnect.tsx', import.meta.url), 'utf8')
  const start = src.indexOf('Waiting for authorization…')
  const block = src.slice(start, src.indexOf("status === 'done'", start))

  it('offers retry as well as cancel', () => {
    // Two ways this stalls, so two exits. A provider-side rejection never
    // redirects back (no error to catch) - but far more often the tab simply
    // never opened, was closed, or landed on the wrong account, and that user
    // wants another go rather than a way out.
    expect(block).toContain('cancelOAuth(tracker); void startOAuth(tracker)')
    expect(block).toContain('Open it again')
    expect(block).toContain('Cancel')
  })

  it('renders them as buttons, not an 11px pseudo-link', () => {
    // The old one was styled like the "Waiting for authorization…" caption above
    // it, on the one screen where the user is already unsure anything is
    // happening - exactly where an escape hatch has to look pressable.
    expect(block).not.toContain('Not going through? Cancel')
    expect(block).toContain("background: 'color-mix(in srgb, var(--color-state-proposal) 12%, transparent)'")
  })

  it('is not gated on two specific providers', () => {
    // Only browser-OAuth trackers reach this branch at all, and being stuck is not
    // provider-specific. cancelOAuth does the provider-specific teardown itself.
    expect(block).not.toContain("tracker.id === 'jira' || tracker.id === 'trello'")
  })
})

describe('deleting a personal task actually removes it from the plan', () => {
  const store = readFileSync(new URL('../components/plan/planStore.ts', import.meta.url), 'utf8')
  const dialog = readFileSync(new URL('../components/timeline/TaskDetailDialog.tsx', import.meta.url), 'utf8')
  const shell = readFileSync(new URL('../components/timeline/MeridianTimelineShell.tsx', import.meta.url), 'utf8')

  it('refreshes every plan reader off the delete broadcast', () => {
    // The delete itself always worked - it stamps `pm_tasks.deleted_at`, and the
    // Rust `load_plan` filters those out. Nothing asked for a fresh read, though:
    // the dialog opened from "Today's focus" is the SHELL's, which wires no
    // `onDeleted`, OverviewPanel has no poll, and PlanView's 30s poll only runs
    // while the planner modal is open. So the row stayed on screen and the delete
    // looked like it had silently failed - and pressing it again did nothing,
    // because server-side it had already worked.
    expect(dialog).toContain("window.dispatchEvent(new CustomEvent('meridian:task-deleted'")
    expect(store).toContain("window.addEventListener('meridian:task-deleted'")
    // Every cached day, not just today: a personal task can sit on more than one
    // day's plan and the deletion is not scoped to one of them.
    expect(store).toContain('[...store.keys()].map(d => refreshPlan(d))')
  })

  it('does not let the drag hold-off swallow that refresh', () => {
    // `paused` exists so a background poll cannot reshuffle a board mid-drag. A
    // delete is a user action whose result must be visible, and a drag cannot be
    // in progress while a modal dialog has the pointer.
    const listener = store.slice(store.indexOf("addEventListener('meridian:task-deleted'"))
    expect(listener).toContain('paused = false')
    expect(listener).toContain('.finally(() => { paused = wasPaused })')
  })

  it('is fixed in the store, not by threading a callback through each opener', () => {
    // Every plan-reading surface has the same problem and there is no bound on how
    // many there will be - the shell's dialog deliberately stays callback-free.
    const dlg = shell.slice(shell.indexOf('<TaskDetailDialog'), shell.indexOf('/>', shell.indexOf('<TaskDetailDialog')))
    expect(dlg).not.toContain('onDeleted')
  })
})

describe('the plan section survives a solo user actually using it', () => {
  const panel = readFileSync(new URL('../components/timeline/OverviewPanel.tsx', import.meta.url), 'utf8')
  const gate = panel.slice(panel.indexOf('{((isToday'), panel.indexOf('{((isToday') + 200)

  it('shows a populated plan to solo users, not just the empty-state nudge', () => {
    // The old gate was `(isToday && plan && focusItems.length === 0) || (!isSolo && …)`,
    // written when a solo user could not have a confirmed plan. Both halves of that
    // assumption died: PlanView's composer writes personal tracker-free tasks, and
    // adding one now confirms the plan immediately (the Confirm button is gone). So
    // the moment a solo user added their first task the whole section vanished -
    // no checklist, no way back into the planner from this panel.
    expect(gate).toContain('(isToday && plan)')
    expect(gate).toContain('focusItems.length > 0')
    // isSolo survives in exactly one place: a PAST day with nothing planned.
    expect(gate).toContain('(!isSolo && !isToday)')
    expect(gate).not.toContain('!isSolo && (focusItems.length > 0')
  })
})

// ── The back half of the tour: the summary, the worklog, and the close-out ────
//
// This half used to be two beats and a card with three numbers on it. It is now
// the majority of the walkthrough, and almost all of it is DOM the script
// addresses by `data-tour` selector - which is exactly the kind of coupling that
// breaks silently. A renamed hook does not throw; it degrades to a beat pointing
// at nothing, then a `waitForClick` that expires into a several-second stall in
// front of a first-time user. These tests are the only thing standing between a
// markup tidy-up and that.

describe('the daily summary the tour teaches', () => {
  const src = SCRIPT_SRC
  // Both halves of the card. It is one screen to the user — the home view and the
  // task view it opens into — and every assertion here is about that screen, so
  // splitting the file must not let a hook go missing from whichever half moved.
  const cardSrc =
    readFileSync(new URL('../components/tutorial/TutorialSummaryCard.tsx', import.meta.url), 'utf8')
    + readFileSync(new URL('../components/tutorial/TutorialSummaryTask.tsx', import.meta.url), 'utf8')
  const screen = readFileSync(new URL('../components/tutorial/TutorialScreen.tsx', import.meta.url), 'utf8')

  it('opens from a button that looks like one, where the real one lives', () => {
    // It was a faint <span> pushed to the far right of an otherwise empty strip.
    // Two failures in one: the beat that flies a cursor into it and clicks looked
    // like the summary opening by itself, and it taught the wrong corner - the
    // real control sits on the LEFT, beside the day label (see Toolbar.tsx).
    const bar = screen.slice(screen.indexOf('function TutorialToolbar'))
    expect(bar).toContain('<button data-tour="summary-pill"')
    expect(bar).not.toContain('<span data-tour="summary-pill"')
    // Same treatment as the real one, so it is recognised afterwards.
    expect(bar).toContain('bg-ctrl')
    // Before the spacer, i.e. on the left. There is no spacer any more at all.
    expect(bar).not.toContain('flex-1')
  })

  it('carries every section the marketing demo shows, not a headline and three stats', () => {
    // The website promises this exact screen (demo.js `summaryHomeBody`), and the
    // product showing a cut-down version of it is the promise being broken in the
    // first five minutes.
    for (const part of ['DAILY SUMMARY', 'You had a very productive day', 'PLANNED DONE',
      'TIME LOGGED', 'URGENT PICKUP', 'Handled the unexpected', 'New learning',
      'TODAY&apos;S PLAN', 'STANDUP - READY TO PASTE']) {
      expect(cardSrc).toContain(part)
    }
  })

  it('names each section in its own beat, in reading order', () => {
    // One paragraph naming four regions of a busy screen is a paragraph nobody
    // maps onto the screen. One ring each, top to bottom.
    //
    // NOT `sum-score`. The numbers were rung and defended ("these are measured,
    // not written") - an answer to a doubt nobody has, since a donut and three
    // counters read as measurements on sight. It only put a paragraph between
    // the sentence about the day and the two things worth remembering from it.
    expect(src).not.toContain('sum-score')
    const order = ['sum-hero', 'sum-cards', 'sum-plan', 'sum-standup']
    let prev = -1
    for (const hook of order) {
      const at = src.indexOf(`s.spotlight('[data-tour="${hook}"]')`)
      expect(at).toBeGreaterThan(prev)
      prev = at
    }
  })

  it('rings only hooks the summary card actually renders', () => {
    // The whole coupling, checked in one place. A renamed hook is silent at
    // runtime: the ring lands nowhere and the wait behind it stalls.
    const hooks = [...src.matchAll(/data-tour="(sum-[a-z-]+)"/g)].map(m => m[1])
    expect(hooks.length).toBeGreaterThan(6)
    // `sum-where` and `sum-update` moved INTO the shipped `DraftDocument` when
    // the two halves became one card, so the anchors the summary rings can live
    // in either file.
    const targets = readFileSync(new URL('../components/timeline/WorklogTargets.tsx', import.meta.url), 'utf8')
    // Either a literal attribute or the name passed through a prop (the plan row
    // stamps its hook conditionally, on one row of three).
    for (const h of new Set(hooks)) {
      expect(
        cardSrc.includes(`data-tour="${h}"`) || cardSrc.includes(`'${h}'`)
        || targets.includes(`data-tour="${h}"`),
      ).toBe(true)
    }
  })

  it('walks a worklog end to end in the REAL panel rather than describing it', () => {
    // Generate, a match with its number showing, approve, confirm, posted - each
    // behind a control the user presses. "It writes my ticket updates for me" is
    // the single claim a new user is most entitled to disbelieve, and it reads as
    // a promise when narrated and as a product when operated.
    // Bounded at beat 6: the off-plan beat drives the SAME controls on the
    // summary now, so an open-ended slice would find its hooks and pass on
    // beat 7's work.
    const flow = src.slice(
      src.indexOf('── 5. The worklog, end to end'),
      src.indexOf('── 6. The daily summary'),
    )
    for (const step of ['wl-generate', 'draft-targets', 'wl-approve',
      'wl-confirm', 'wl-posted']) {
      expect(flow).toContain(step)
    }
    // NOT the re-match control. The match here is a strong one the tour has just
    // called out at 90%, so a beat on "matched the wrong one?" answers a doubt
    // nobody watching has and detours the one thing this stretch lands: approve,
    // and it posts. Picking a target is taught in beat 7 instead, on the off-plan
    // task, where the choice is a real one.
    expect(flow).not.toContain('s.spotlight(\'[data-tour="wl-rematch"]\')')
    expect(flow.indexOf('wl-generate')).toBeLessThan(flow.indexOf('wl-approve'))
    expect(flow.indexOf('wl-approve')).toBeLessThan(flow.indexOf('wl-confirm'))
    // Every one of those hooks is on the SHIPPED surface, not a tutorial
    // lookalike. They live in the worklog DIALOG now (and its action bar), which
    // is why the tour has to open it first.
    const entry = readFileSync(new URL('../components/timeline/WorklogDraftDialog.tsx', import.meta.url), 'utf8')
    const acts = readFileSync(new URL('../components/timeline/WorklogActions.tsx', import.meta.url), 'utf8')
    expect(entry).toContain('data-tour="wl-open"')
    for (const h of ['wl-generate', 'wl-approve', 'wl-confirm', 'wl-posted']) {
      expect(acts).toContain(`data-tour="${h}"`)
    }
    expect(flow.indexOf('wl-open')).toBeLessThan(flow.indexOf('wl-generate'))
  })

  it('never lets the tour fire a real generate or a real post', () => {
    // The example day's task ids exist in no database and its ticket keys belong
    // to another project: the live generate could only error, and the live
    // approve could only file a wrong comment on a stranger's board. So the STATE
    // is scripted and the component is untouched.
    const screen = readFileSync(new URL('../components/tutorial/TutorialScreen.tsx', import.meta.url), 'utf8')
    expect(screen).toContain('worklog={demoWl}')
    expect(screen).toContain('boardTickets={demoTickets}')
    const demo = readFileSync(new URL('../components/tutorial/demoWorklog.ts', import.meta.url), 'utf8')
    // Nothing in the scripted machine may reach the bridge.
    for (const call of ['invoke(', 'mutate(', 'load(']) {
      expect(demo).not.toContain(call)
    }
  })

  it('admits the post was not real', () => {
    // The planner drag is real because it moves the user's own row. This would
    // file a comment on somebody's board against issue keys from a day that never
    // happened - so it does not, and the beat says so rather than letting the
    // tick be found out later by checking the board.
    const flow = src.slice(src.indexOf('── 5. The worklog, end to end'))
    expect(flow).toContain('nothing really went out')
  })

  it('teaches the OFF-PLAN outcome too, and on work that genuinely has no ticket', () => {
    // The first post is the easy case: planned work, matched to the ticket it was
    // planned as. How a tool handles the other kind - the thing that came up - is
    // what decides whether it gets trusted, and a demo that only ever shows a
    // match teaches that the other outcome does not exist.
    const flow = src.slice(src.indexOf('── 7. The work that was NOT on the plan'))
    for (const step of ['sum-offplan', 'sum-offplan-row', 'sum-where', 'wl-rematch',
      'wl-pick', 'wl-approve', 'wl-confirm', 'wl-posted']) {
      expect(flow).toContain(step)
    }
    // The card it opens must really carry no ticket, or "nothing matched, so I
    // wrote you one" is a line the screen behind it contradicts.
    const offPlan = sampleTasks().find((t) => t.id === OFFPLAN_TASK_ID)
    expect(offPlan).toBeDefined()
    expect(offPlan!.linked_ticket).toBeNull()
    // And no plan row carries it either.
    expect(samplePlanItems().some((p) => p.task_key === offPlan!.linked_ticket)).toBe(false)
  })

  it('rings the draft in the order it is laid out, so the ring moves downward', () => {
    // The beats must follow the layout rather than setting their own sequence:
    // a ring that jumps down the card and back up reads as the tour having lost
    // its place. Destination band first, then the update beneath it.
    const flow = src.slice(src.indexOf('── 7. The work that was NOT on the plan'))
    expect(flow.indexOf('sum-where')).toBeLessThan(flow.indexOf('sum-update'))
  })

  it('proposes a NEW ticket, and still offers an existing one', () => {
    // The proposal is a suggestion the user owns. A create-only flow teaches that
    // a wrong draft is final, which is how people quietly stop using drafts.
    expect(cardSrc).toContain('PROPOSED_TICKET')
    expect(cardSrc).toContain("mode === 'propose'")
  })

  it('shows the draft as ONE card, not a stack of tinted panels', () => {
    // It was three: a "WHAT YOU DID" bullet list duplicating the update in a
    // different voice (the exact pairing that got the draft moved out of the
    // task panel), then a framed where-it-goes wrapper around `DraftTargets`'
    // own card, then the update. Then two, in two different tints - which still
    // said "these are separate things to weigh" when they are one object: a
    // ticket and the text that goes on it.
    const body = code(readFileSync(new URL('../components/tutorial/TutorialSummaryTask.tsx', import.meta.url), 'utf8'))
    expect(body).not.toContain('WHAT YOU DID')
    expect(body).not.toContain('sum-did')
    expect(src).not.toContain('sum-did')
    // The single card is the shipped one, not another tutorial-shaped copy.
    expect(body).toContain('<DraftDocument draft={draft}')
    expect(body).not.toContain("border: '1px solid var(--t-card-border)'")
  })

  it('runs that flow on the SHIPPED worklog controls, not a replica of them', () => {
    // It used to be a hand-written copy - its own where-it-goes box, its own
    // picker, its own post button - so the tour taught a screen that exists
    // nowhere, and drifted every time the real one was redesigned. Worse, the
    // override sat in a section header while the primary sat a screen below it:
    // the two halves of one decision, nowhere near each other.
    const view = readFileSync(new URL('../components/tutorial/TutorialSummaryTask.tsx', import.meta.url), 'utf8')
    for (const part of ['DraftTargets', 'UpdateBody', 'DraftActions', 'ConfirmPost',
      'PostedBar', 'WorklogTicketPicker']) {
      expect(view).toContain(part)
    }
    expect(view).toContain("from '@/components/timeline/WorklogActions'")
    // And `DraftActions` is what puts them on one row - override beside primary.
    const acts = readFileSync(new URL('../components/timeline/WorklogActions.tsx', import.meta.url), 'utf8')
    const row = acts.slice(acts.indexOf('export function DraftActions'))
    expect(row.indexOf('data-tour="wl-rematch"')).toBeLessThan(row.indexOf('data-tour="wl-approve"'))
    // One ticket list for both demos, not two that can disagree.
    expect(view).toContain('demoBoardTickets')
    expect(cardSrc).not.toContain('TICKET_POOL')
  })

  it('ties the clicked row to the card whose write-up opens behind it', () => {
    // Positional coupling here would put a beat on one row and a write-up from
    // another the moment the sample plan is reordered.
    expect(cardSrc).toContain('OFFPLAN_TASK_ID')
  })
})

describe('the closing asks: a delivery time, and the off switch', () => {
  const src = SCRIPT_SRC
  const dialog = readFileSync(new URL('../components/timeline/WorklogAutoGenerateDialog.tsx', import.meta.url), 'utf8')
  const shell = readFileSync(new URL('../components/timeline/MeridianTimelineShell.tsx', import.meta.url), 'utf8')
  const tray = readFileSync(new URL('../components/tutorial/TutorialTray.tsx', import.meta.url), 'utf8')

  it('asks for the time only after showing what it produces', () => {
    // The ask is meaningless until you have watched a day get written up. Put in
    // a wizard it gets a shrug and a default.
    expect(src.indexOf('showWorklogSchedule(true)')).toBeGreaterThan(src.indexOf('demoSummary(true)'))
  })

  it('asks when the user wants it READY, not when their day ends', () => {
    // "When does your day end?" is a question about the user, answered with a
    // shrug, and the link between it and the feature being switched on is left
    // for the reader to make. What is being set is a delivery time.
    expect(code(dialog)).not.toContain('When does your day end')
    expect(dialog).toContain('When do you want these auto ready?')
    expect(code(src)).not.toContain('does your day')
  })

  it('offers one button, since declining is already the × and the backdrop', () => {
    // "Not now" was a third control that did exactly what the close button and
    // a backdrop click already do - a second way to do nothing, giving a
    // one-question dialog the shape of a two-sided decision.
    expect(code(dialog)).not.toContain('Not now')
    // Both quiet exits still commit the prompted flag, so it does not reappear.
    expect(dialog.split("worklog_auto_generate_prompted: true }, 'later')").length - 1).toBe(2)
    expect(dialog).toContain('Change anytime in Settings')
  })

  it('saves the time that is on screen, and refuses to save a non-time', () => {
    // `<input type="time">` reports '' for a partly typed or cleared value.
    // Committing that writes an empty string, which is NOT null - so the feature
    // reads as switched ON everywhere while naming a time that never comes
    // round, and the selection the user made is silently not the one saved.
    expect(isSavableTime('18:00')).toBe(true)
    expect(isSavableTime('09:05')).toBe(true)
    expect(isSavableTime('23:59')).toBe(true)
    expect(isSavableTime('')).toBe(false)
    expect(isSavableTime('9:00')).toBe(false)
    expect(isSavableTime('24:00')).toBe(false)
    expect(isSavableTime('12:60')).toBe(false)
    // One source for the confirmation line and the commit, so they cannot drift.
    expect(dialog).toContain('worklog_auto_generate_time: time')
    expect(dialog).toContain('disabled={busy !== null || !valid}')
  })

  it('keeps the narration clear of the dialog it is narrating', () => {
    // A spotlight anchors the caption to what it rings, and everything worth
    // ringing here is inside a dialog centred in the window - so the caption
    // landed on top of the copy the user is being asked to read. No ring while
    // it is up: the caption falls to the top bar, and the cursor still points.
    const beat = src.slice(
      src.indexOf('showWorklogSchedule(true)'),
      src.indexOf('showWorklogSchedule(false)'),
    )
    expect(beat).not.toContain('s.spotlight(\'[data-tour="worklog-schedule')
    expect(beat).toContain('s.point(\'[data-tour="worklog-schedule-on"]\')')
  })

  it('names both things that time sets off, not just the worklogs', () => {
    // It said "Worklogs" and "Auto-draft your worklogs". The same pass composes
    // the daily summary too, so "Not now" was also switching off the screen the
    // user had just been walked through, without being told.
    expect(dialog).toContain('Daily summary and worklogs')
    expect(dialog).not.toContain('Auto-draft your worklogs')
    expect(dialog).toContain('Summary and drafts ready by')
  })

  it('lets the tour raise the real dialog the shell otherwise suppresses', () => {
    // The shell's own trigger fires on the first Timeline load, i.e. over the
    // title sequence - so it stays gated on `!tutorial.running` and the script
    // gets its own way in.
    expect(shell).toContain('!tutorial.running && (')
    expect(shell).toContain('setShowWorklogSchedule: setTourWorklogSchedule')
    expect(shell).toContain('{tourWorklogSchedule && (')
  })

  it('teaches the off switch, and pauses nothing doing it', () => {
    // An ambient recorder that never shows you how to stop it is a thing you
    // switch off at the operating system. But a walkthrough that quietly stopped
    // capture on its way past would leave a new user with a product that does
    // not work - so the replica is inert and the beat says so out loud.
    const beat = src.slice(src.indexOf('── 12. The off switch'))
    expect(beat).toContain('tray-icon')
    expect(beat).toContain('tray-pause')
    expect(beat).toContain('tray-15m')
    expect(beat).toContain('Nothing was really paused')
    expect(tray).not.toContain('invoke')
    expect(tray).not.toContain('mutate')
  })

  it('points at the corner the tray is actually in on this OS', () => {
    // The beat is entirely about WHERE the control lives, and it said "up here
    // in your menu bar" on every platform. Windows has no menu bar - the icon
    // sits in the notification area at the bottom right, by the clock - so a
    // Windows user was being sent to a place their machine does not have.
    expect(trayIsAtTheTop('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)')).toBe(true)
    expect(trayIsAtTheTop('Mozilla/5.0 (Windows NT 10.0; Win64; x64)')).toBe(false)
    // The CORNER follows that answer. The NOUN does not: it is "the tray" on
    // both platforms, which is what the app calls it everywhere else - a user
    // handed "menu bar" or "notification area" has to translate the OS's term
    // back into the product's before they can act on it.
    expect(tray).toContain('...(top ? { top: 44 } : { bottom: 0 })')
    expect(tray).toContain('your tray')
    expect(tray).not.toContain("'your menu bar'")
    expect(src).toContain('Meridian is down here in your tray, always. Click it.')
    expect(src).toContain('Meridian is up here in your tray, always. Click it.')
  })

  it('parks the tray strip clear of the overlay\'s skip pills', () => {
    // The beat asks for a click on the tray icon. The escape hatches sit at the
    // top-right at z-9000, so a strip at `top-0 right-0` put the icon directly
    // underneath "Skip tour" and every click went to Skip instead.
    const overlay = readFileSync(new URL('../components/tutorial/TutorialOverlay.tsx', import.meta.url), 'utf8')
    expect(overlay).toContain('top: 14, right: 16')
    expect(tray).not.toContain('absolute top-0 right-0')
    expect(tray).toContain('top: 44')
  })

  it('mirrors the real popover, including its two-step pause', () => {
    // Pressing "Pause capture" in the real tray reveals the durations rather than
    // pausing on the spot. A replica that paused immediately would teach a
    // gesture that does something different in the product.
    expect(tray).toContain('setShowOpts(true)')
    for (const opt of ['Pause for 15 minutes', 'Pause for 1 hour', 'Pause until tomorrow',
      'Pause indefinitely']) {
      expect(tray).toContain(opt)
    }
  })

  it('ends by saying nothing more is required', () => {
    // The reassurance the whole product depends on and the one a demo cannot
    // show: the alternative reading of an ambient tool is that it needs minding.
    // Short on purpose. This is the last thing said before the off switch, and
    // a paragraph here is a paragraph nobody finishes.
    const close = src.slice(src.indexOf('── 11. Running'))
    expect(close).toContain('Close this window - Meridian keeps going')
  })
})
